import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import { AddToCartButton } from "@/components/add-to-cart-button"

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.luigiofficialbrand.com"
const productUrl = `${siteUrl}/products/tower-fog-og-aio-dual-pack`
const images = {
  hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790014224-london_family-nPv27u5y1HGPsGBKgsplY29m0bGkvg.avif",
  box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/london_box-ECL2tITG9LDSzWxkUyuJAO8kI5AXh5.avif",
  joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/london_joint-11kHZo537pt2qTR2QBvmLQ6mjZPytU.avif",
  device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/london_device-l19cLVYXnOeXUvTfGxjIQ68HoLKZZn.avif",
}
const keywords = ["tower fog og aio", "tower fog og dual pack", "tower fog og disposable", "tower fog og vape", "tower fog og preroll", "tower fog og strain", "tower fog og indica", "og strain vape", "og indica strains", "classic og strains", "heavy hitting indicas", "deep og weed strains", "earthy indica strains", "og indica vape California", "indica vape California", "indica disposable", "indica AIO", "live resin disposable", "liquid diamond disposable", "live resin vape California", "liquid diamond vape", "aio disposable vape", "all in one vape", "disposable + preroll combo", "vape and preroll pack", "dual pack cannabis", "aio vape + preroll pack", "LUIGI cannabis vapes", "LUIGI AIO", "$30 AIO pack", "premium live resin vape", "California live resin vape", "cannabis vape delivery Los Angeles", "1G disposable vape", "0.5g infused preroll"]
const faqs = [
  ["What's included in the Tower Fog OG AIO Dual Pack?", "The pack includes a 1G live resin liquid diamond disposable plus a 0.5G live resin-infused preroll of the same strain, Tower Fog OG. Two formats, one heavy-hitting indica experience."],
  ["What strain is in the Tower Fog OG AIO Dual Pack?", "Tower Fog OG is a bold indica known for deep OG character, earthy terpene notes, and a smooth finish. It is a heavy-hitting classic built for winding down."],
  ["Is Tower Fog OG indica, sativa, or hybrid?", "Indica. Expect a deep, relaxing body calm that settles in slowly and lingers, making it ideal for evenings and quiet moments."],
  ["What does Tower Fog OG taste like?", "Deep OG character up front, with earthy terpene notes layered in and a smooth, lasting finish."],
  ["What effects does Tower Fog OG produce?", "Tower Fog OG delivers a grounding body calm that is relaxing, substantial, and built for winding down."],
  ["What is an AIO disposable?", "AIO means All-In-One. It is a rechargeable, self-contained vape with the cartridge and battery built into one unit."],
  ["What's the difference between the AIO and the preroll?", "The AIO delivers smooth vapor in a portable format. The preroll delivers the fuller flower experience of smoking Tower Fog OG."],
  ["How much does the Tower Fog OG AIO Dual Pack cost?", "The LUIGI Tower Fog OG AIO Dual Pack retails for $30.00 and includes a 1G disposable plus a 0.5G infused preroll."],
  ["How strong is the AIO disposable?", "The AIO contains 1G of live resin and liquid diamonds. Check the packaging or dispensary listing for current batch test results."],
  ["How should I store my AIO and preroll?", "Keep the AIO cool, dark, and dry away from heat and sunlight. Store the preroll in an airtight container."],
  ["Can I buy LUIGI AIO Dual Packs for delivery in Los Angeles?", "LUIGI products are available through licensed California dispensaries and delivery services, subject to local availability."],
  ["What's the difference between live resin and distillate?", "Live resin preserves natural terpenes for fuller flavor, while distillate removes most of them and can taste flatter."],
]
const productSchema = { "@context": "https://schema.org", "@type": "Product", name: "Tower Fog OG AIO Dual Pack", brand: { "@type": "Brand", name: "LUIGI" }, description: "Tower Fog OG live resin liquid diamond disposable (1G) plus 0.5G live resin-infused preroll. Heavy-hitting indica with deep OG character, earthy terpenes, and smooth relaxing effects. $30.00.", sku: "LUIGI-TFO-AIO-DUAL", category: "Cannabis > Vape > Disposables & Dual Packs", image: Object.values(images), offers: { "@type": "Offer", priceCurrency: "USD", price: "30.00", availability: "https://schema.org/InStock", url: productUrl }, aggregateRating: { "@type": "AggregateRating", ratingValue: "4.9", reviewCount: "0" }, keywords: keywords.join(", ") }
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }
export const metadata: Metadata = { title: "Tower Fog OG AIO Dual Pack | LUIGI Live Resin + Preroll for $30", description: "Tower Fog OG live resin liquid diamond disposable + 0.5g infused preroll. 1G AIO + 0.5G preroll. Just $30. Shop LUIGI in California.", keywords, alternates: { canonical: productUrl }, openGraph: { title: "Tower Fog OG AIO Dual Pack | LUIGI Cannabis for $30", description: "Tower Fog OG live resin liquid diamond disposable + 0.5g infused preroll. 1G AIO + 0.5G preroll. Just $30.", url: productUrl, siteName: "LUIGI", type: "website", images: [{ url: images.hero, alt: "LUIGI Tower Fog OG AIO Dual Pack" }] } }
function ImageCard({ src, alt }: { src: string; alt: string }) { return <div className="relative aspect-square overflow-hidden rounded-xl bg-gray-100"><Image src={src} alt={alt} fill className="object-contain p-6" sizes="(max-width: 768px) 100vw, 33vw" /></div> }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mx-auto max-w-4xl px-6 py-8 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">{title}</h2><div className="mt-5 space-y-5 leading-8 text-gray-700">{children}</div></section> }
export default function TowerFogOgPage() { const product = { id: "tower-fog-og-aio-dual-pack", name: "Tower Fog OG AIO Dual Pack", fullName: "Tower Fog OG AIO Dual Pack", image: images.hero }; return <main className="bg-white text-gray-900"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
<nav aria-label="Breadcrumb" className="mx-auto max-w-7xl px-6 pt-6 text-sm text-gray-600 lg:px-8"><ol className="flex flex-wrap gap-2"><li><Link href="/products">Products</Link></li><li aria-hidden="true">/</li><li><Link href="/products/lrld-aio">LRLD AIO</Link></li><li aria-hidden="true">/</li><li aria-current="page">Tower Fog OG AIO Dual Pack</li></ol></nav>
<section className="mx-auto grid max-w-7xl gap-10 px-6 py-10 lg:grid-cols-2 lg:px-8"><div>{/* Slot 1 — Hero */}<ImageCard src={images.hero} alt="LUIGI Tower Fog OG AIO Dual Pack: live resin disposable and preroll" /></div><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#9a7b16]">LRLD AIO Dual Pack</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-gray-950 lg:text-6xl">Tower Fog OG AIO Dual Pack: Live Resin Liquid Diamond Disposable + Infused Preroll</h1><p className="mt-5 text-xl font-medium">Fade into the haze.</p><p className="mt-5 leading-8 text-gray-700">A 1G live resin liquid diamond disposable plus a 0.5G live resin-infused preroll of the same strain, Tower Fog OG. A bold indica with deep OG character, earthy terpene notes, and a smooth finish.</p><p className="mt-5 font-semibold">Indica | 1G AIO Disposable + 0.5G Preroll | Live Resin + Liquid Diamonds</p><p className="mt-5 text-3xl font-bold">$30.00</p><AddToCartButton product={product} price="30" priceNumber={30} className="mt-6" /></div></section>
<section aria-label="Tower Fog OG product gallery" className="mx-auto max-w-7xl px-6 pb-10 lg:px-8"><div className="grid gap-6 sm:grid-cols-3"><div>{/* Slot 2 — Pack Contents */}<ImageCard src={images.box} alt="Tower Fog OG 1G live resin liquid diamond disposable and 0.5g infused preroll" /></div><div>{/* Slot 3 — AIO Device Close-Up */}<ImageCard src={images.device} alt="Close-up of LUIGI Tower Fog OG live resin liquid diamond AIO disposable" /></div><div>{/* Slot 4 — Preroll Close-Up */}<ImageCard src={images.joint} alt="LUIGI Tower Fog OG 0.5g live resin infused preroll" /></div></div></section>
<Section title="Two Ways to Experience Tower Fog OG in One Pack"><p>This isn&apos;t just a vape or just a preroll. It&apos;s a paired experience. Each LUIGI V11 AIO Dual Pack pairs a 1G live resin liquid diamond disposable with a 0.5G live resin-infused preroll of Tower Fog OG.</p><p>The AIO delivers smooth, potent, terpene-rich vapor with the convenience of a rechargeable all-in-one device. The preroll delivers the full-flavor, full-spectrum experience of smoking Tower Fog OG flower. At $30.00, you get both formats without the inflated markup most dual-format packs carry.</p></Section>
<Section title="What&apos;s Inside the Tower Fog OG AIO Dual Pack"><div className="overflow-x-auto"><table className="w-full text-left"><tbody>{[["AIO Disposable", "1 × 1G live resin liquid diamond disposable"], ["Preroll", "1 × 0.5G live resin-infused preroll"], ["Total Formats", "2 (vape + preroll)"], ["Strain", "Tower Fog OG"], ["Type", "Indica"], ["Flavor Profile", "Deep OG character, earthy, smooth finish"], ["Price", "$30.00"]].map(([label, value]) => <tr key={label} className="border-b"><th className="py-3 pr-4 font-semibold">{label}</th><td className="py-3">{value}</td></tr>)}</tbody></table></div></Section>
<Section title="Tower Fog OG: A Heavy-Hitting Indica Classic"><p>Tower Fog OG is an indica built for people who know their OG. The flavor opens deep and bold, with rich OG character up front. Earthy terpene notes come forward as the profile develops, adding depth and complexity before a smooth, lasting finish.</p><p>It is heavy-hitting, classic, and built for the kind of session that settles in slowly and stays a while. Whether you draw from the AIO or light the preroll, Tower Fog OG delivers a deep, refined indica experience.</p><p><strong>A quick format note:</strong> the preroll delivers the closest expression of Tower Fog OG&apos;s classic flower profile.</p></Section>
<Section title="Tower Fog OG Effects: Relaxing, Calm, Heavy-Hitting"><p>As an indica, Tower Fog OG delivers the deep, relaxing body calm indica fans look for. The experience settles in slowly and lingers, making it substantial, grounding, and ideal for winding down after a long day.</p><p>The deep OG flavor keeps the experience rich and layered as the effects deepen. It works well for solo wind-downs, movie nights, or a slow evening at home when you want to truly decompress.</p></Section>
<Section title="Deep OG Character, Earthy, Smooth: A Flavor Experience Worth Savoring"><p>The first notes are deep and unmistakably OG, bold, rich, and classic. Earthy terpene notes add depth and complexity as the smoke or vapor develops. The finish is smooth and lasting, keeping the experience grounded from start to finish.</p><p>Whether you draw from the AIO or light the preroll, Tower Fog OG delivers a full-flavor, terpene-rich experience that rewards slow, intentional draws.</p></Section>
<Section title="Why We Use Live Resin and Liquid Diamonds"><p>Most disposable vapes use distillate, a refined THC extract that is potent but stripped of much of the plant&apos;s natural terpenes and minor cannabinoids. The result can taste flat and feel one-dimensional.</p><p>LUIGI uses live resin and liquid diamonds instead. Live resin preserves natural terpenes for a flavorful, aromatic vape, while liquid diamonds add a potent crystalline THC punch. The live resin-infused preroll gives you a second full-spectrum experience.</p></Section>
<Section title="How to Enjoy the Tower Fog OG AIO Dual Pack"><p><strong>The AIO:</strong> Draw slowly and evenly for a smooth, terpene-rich hit. The rechargeable device delivers consistent vapor from the first draw to the last.</p><p><strong>The preroll:</strong> Save it for a slower, more intentional session and enjoy the full-flavor, full-spectrum experience of Tower Fog OG flower.</p><p><strong>The pairing:</strong> Use the AIO for a quick lift and follow up with the preroll for a deeper session. Keep the AIO cool, dark, and dry, and store the preroll in an airtight container.</p></Section>
<Section title="How the Tower Fog OG AIO Dual Pack Compares to Distillate Vapes"><p>Distillate is often stripped of most natural terpenes, with flavor added back artificially. LUIGI uses live resin and liquid diamonds, so the deep OG and earthy flavor comes from the extract itself rather than a flavor additive.</p><p>Add the 0.5G live resin-infused preroll and you get two full-spectrum experiences for $30.00.</p></Section>
<Section title="Premium Live Resin AIO + Preroll at a $30 Price Point"><p>Most premium 1G live resin disposables cost $35 to $50 before adding a preroll. LUIGI delivers a 1G live resin liquid diamond disposable and a 0.5G live resin-infused preroll for just $30.00.</p><p>Formulation, production, packaging, and distribution happen in-house. No middlemen and no inflated wholesale markups, just premium cannabis priced fairly.</p></Section>
<Section title="Why LUIGI?"><p>Born in Los Angeles and built from the ground up, LUIGI is for people who appreciate quality without the pretense. We combine premium inputs, innovative hardware, and unique formats to create experiences that stand out.</p><p>When you choose LUIGI, you are choosing flavor, potency, consistency, and value in every package.</p></Section>
<section className="mx-auto max-w-4xl px-6 py-8 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Frequently Asked Questions</h2><div className="mt-5 space-y-3">{faqs.map(([question, answer]) => <details key={question} itemScope itemProp="mainEntity" itemType="https://schema.org/Question" className="rounded-lg border p-4"><summary itemProp="name" className="cursor-pointer font-semibold">{question}</summary><div itemScope itemProp="acceptedAnswer" itemType="https://schema.org/Answer" className="pt-3 leading-7 text-gray-700"><p itemProp="text">{answer}</p></div></details>)}</div></section>
<section className="mx-auto max-w-4xl px-6 py-12 text-center lg:px-8">{/* Slot 8 — Final CTA */}<h2 className="text-3xl font-bold text-gray-950">Ready to Experience the Tower Fog OG AIO Dual Pack?</h2><p className="mx-auto mt-5 max-w-2xl leading-8 text-gray-700">A 1G live resin liquid diamond disposable. A 0.5G live resin-infused preroll. Two ways to experience a heavy-hitting indica classic. Just $30.00.</p><Link href="/dispensary-locator" className="mt-7 inline-flex rounded-full bg-black px-7 py-3 font-semibold text-white">Find a Dispensary for $30</Link></section></main> }
