import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import { AddToCartButton } from "@/components/add-to-cart-button"

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.luigiofficialbrand.com"
const productUrl = `${siteUrl}/products/green-crack-aio-dual-pack`
const images = {
  hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790014557-singapore_family-BpZS90ksyS4kyyqGqEnZOh7E2vkyhq.avif",
  box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/signapore_box-vJYN19w2CGadIWW7gMenCzEQxDbyuO.avif",
  joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/singapore_joint-pF4I3illiulkPM9OPI4TQiUlDljeQQ.avif",
  device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/signapore_device-pAPocjv4nIAxC9hS1szF54fSK3OHEa.avif",
}
const faqs = [
  ["What's included in the Green Crack AIO Dual Pack?", "The pack includes a 1G live resin liquid diamond disposable plus a 0.5G live resin-infused preroll of Green Crack. Two formats, one legendary sativa experience."],
  ["What strain is in the Green Crack AIO Dual Pack?", "Green Crack is a sativa-forward strain bred from Skunk #1 and Afghani. Snoop Dogg renamed it after experiencing its energizing punch, and it placed 3rd at the 2015 Denver Cannabis Cup."],
  ["Is Green Crack indica, sativa, or hybrid?", "Sativa. Expect a bright, energetic head-lift with focused and creative effects."],
  ["What does Green Crack taste like?", "Sweet citrus and tropical mango lead the profile, with skunk and earthy notes on the finish."],
  ["What effects does Green Crack produce?", "Consumers report energetic, uplifted, happy, creative, euphoric, and focused effects."],
  ["What is an AIO disposable?", "AIO means All-In-One. It is a rechargeable, self-contained vape with the cartridge and battery in one device."],
  ["How much does the Green Crack AIO Dual Pack cost?", "The LUIGI Green Crack AIO Dual Pack retails for $30.00."],
  ["How should I store my AIO and preroll?", "Keep the AIO cool, dark, and dry. Store the preroll in an airtight container."],
  ["What's the difference between live resin and distillate?", "Live resin preserves natural terpenes for a fuller flavor, while distillate removes most of them."],
]
const productSchema = { "@context": "https://schema.org", "@type": "Product", name: "Green Crack AIO Dual Pack", brand: { "@type": "Brand", name: "LUIGI" }, description: "Green Crack live resin liquid diamond disposable (1G) plus 0.5G live resin-infused preroll. $30.00.", sku: "LUIGI-GC-AIO-DUAL", category: "Cannabis > Vape > Disposables & Dual Packs", offers: { "@type": "Offer", priceCurrency: "USD", price: "30.00", availability: "https://schema.org/InStock", url: productUrl } }
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }

export const metadata: Metadata = {
  title: "Green Crack AIO Dual Pack | LUIGI Live Resin + Preroll for $30",
  description: "Green Crack live resin liquid diamond disposable + 0.5g infused preroll. 1G AIO + 0.5G preroll. Just $30. Shop LUIGI in California.",
  alternates: { canonical: productUrl },
  openGraph: { title: "Green Crack AIO Dual Pack | LUIGI Cannabis for $30", description: "Green Crack live resin liquid diamond disposable + 0.5g infused preroll. 1G AIO + 0.5G preroll. Just $30.", url: productUrl, siteName: "LUIGI", type: "website" },
}
function ImageCard({ src, alt }: { src: string; alt: string }) { return <div className="relative aspect-square overflow-hidden rounded-xl bg-gray-100"><Image src={src} alt={alt} fill className="object-contain p-6" sizes="(max-width: 768px) 100vw, 33vw" /></div> }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mx-auto max-w-4xl px-6 py-8 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">{title}</h2><div className="mt-5 space-y-5 leading-8 text-gray-700">{children}</div></section> }

export default function GreenCrackPage() {
  const product = { id: "green-crack-aio-dual-pack", name: "Green Crack AIO Dual Pack", fullName: "Green Crack AIO Dual Pack", image: images.hero }
  return <main className="bg-white text-gray-900">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <nav aria-label="Breadcrumb" className="mx-auto max-w-7xl px-6 pt-6 text-sm text-gray-600 lg:px-8"><ol className="flex flex-wrap gap-2"><li><Link href="/products">Products</Link></li><li aria-hidden="true">/</li><li><Link href="/products/lrld-aio">LRLD AIO</Link></li><li aria-hidden="true">/</li><li aria-current="page">Green Crack AIO Dual Pack</li></ol></nav>
    <section className="mx-auto grid max-w-7xl gap-10 px-6 py-10 lg:grid-cols-2 lg:px-8"><div>{/* Slot 1 — Hero */}<ImageCard src={images.hero} alt="LUIGI Green Crack AIO Dual Pack: live resin disposable and preroll" /></div><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#9a7b16]">LRLD AIO Dual Pack</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-gray-950 lg:text-6xl">Green Crack AIO Dual Pack: Live Resin Liquid Diamond Disposable + Infused Preroll</h1><p className="mt-5 text-xl font-medium">Let the good times roll.</p><p className="mt-5 leading-8 text-gray-700">A 1G live resin liquid diamond disposable plus a 0.5G live resin-infused pre-roll of Green Crack. A legendary sativa-forward classic with a bold personality and a punchy terpene profile. Big flavor. Classic vibes. Two premium ways to spark it up.</p><p className="mt-5 font-semibold">Sativa | 1G AIO Disposable + 0.5G Preroll | Live Resin + Liquid Diamonds</p><p className="mt-5 text-3xl font-bold">$30.00</p><AddToCartButton product={product} price="30" priceNumber={30} className="mt-6" /></div></section>
    <section aria-label="Green Crack product gallery" className="mx-auto max-w-7xl px-6 pb-10 lg:px-8"><div className="grid gap-6 sm:grid-cols-3">{/* Slot 2 — Pack Contents */}<ImageCard src={images.box} alt="Green Crack 1G live resin liquid diamond disposable and 0.5g infused preroll" />{/* Slot 3 — AIO Device Close-Up */}<ImageCard src={images.device} alt="Close-up of LUIGI Green Crack live resin liquid diamond AIO disposable" />{/* Slot 4 — Preroll Close-Up */}<ImageCard src={images.joint} alt="LUIGI Green Crack 0.5g live resin infused preroll" /></div></section>
    <Section title="Two Ways to Experience Green Crack in One Pack"><p>This isn&apos;t just a vape or just a preroll. It&apos;s a paired experience. Each LUIGI V11 AIO Dual Pack pairs a 1G live resin liquid diamond disposable with a 0.5G live resin-infused preroll of the same strain, Green Crack.</p><p>The AIO delivers smooth, potent, terpene-rich vapor with the convenience of a rechargeable all-in-one device. The preroll delivers the full-flavor, full-spectrum experience of smoking Green Crack flower. Together, they give you two ways to experience the same legendary sativa.</p><p>At $30.00, you get premium inputs and in-house production without the inflated markup most dual-format packs carry.</p></Section>
    <Section title="What&apos;s Inside the Green Crack AIO Dual Pack"><div className="overflow-x-auto"><table className="w-full text-left"><tbody>{[["AIO Disposable","1 × 1G live resin liquid diamond disposable"],["Preroll","1 × 0.5G live resin-infused preroll"],["Strain","Green Crack"],["Type","Sativa"],["Genetics","Skunk #1 × Afghani"],["Effects","Energetic, uplifted, happy, creative, euphoric, focused"],["Flavor","Skunk, citrus, mango, earthy, sweet"],["Price","$30.00"]].map(([label, value]) => <tr key={label} className="border-b"><th className="py-3 pr-4 font-semibold">{label}</th><td className="py-3">{value}</td></tr>)}</tbody></table></div></Section>
    <Section title="Green Crack: A Legendary Sativa with a Story"><p>Green Crack is one of the most iconic sativas in cannabis history. Snoop Dogg renamed the strain Green Crack after experiencing its energizing punch, and it went on to earn 3rd place at the 2015 Denver Cannabis Cup. A cross of Skunk #1 and Afghani, it has earned its place in cannabis lore.</p><p>The flavor is sweet and citrus-forward, with tropical mango layered in and skunk and earthy notes grounding the profile. The effects are energetic and uplifting, with focused, creative energy that keeps you engaged.</p><p><strong>Note:</strong> The preroll delivers the closest expression of Green Crack&apos;s classic flower profile.</p></Section>
    <Section title="Green Crack Effects: Energetic, Focused, Creative"><p>Consumers consistently report energetic, uplifted, happy, creative, euphoric, and focused effects. The high is bright and cerebral, with laser-sharp focus paired with creative bursts and an overall sense of elevated well-being.</p><p>It is smooth and manageable, making it a good fit for daytime sessions, creative work, outdoor adventures, or social afternoons.</p></Section>
    <Section title="Skunk, Citrus, Mango: A Flavor Experience Worth Savoring"><p>Green Crack delivers a bold flavor profile. Sweet citrus leads the experience, tropical mango adds depth, and skunk and earthy undertones round it out with classic cannabis character.</p></Section>
    <Section title="Why We Use Live Resin and Liquid Diamonds"><p>Most disposable vapes use distillate, a refined THC extract that is potent but stripped of natural terpenes and minor cannabinoids. Live resin preserves those natural terpenes, while liquid diamonds add a potent crystalline THC punch.</p><p>Because the pack also includes a live resin-infused preroll, you get two full-spectrum experiences instead of one.</p></Section>
    <Section title="How to Enjoy the Green Crack AIO Dual Pack"><p><strong>The AIO:</strong> Draw slowly and evenly for a smooth, terpene-rich hit. The rechargeable device delivers consistent vapor from the first draw to the last.</p><p><strong>The preroll:</strong> Save it for a slower, more intentional session and enjoy the full-flavor experience of Green Crack flower.</p><p><strong>Storage:</strong> Keep the AIO cool, dark, and dry. Store the preroll in an airtight container.</p></Section>
    <Section title="How the Green Crack AIO Dual Pack Compares to Distillate Vapes"><p>Distillate often has flavor added back artificially. LUIGI uses live resin and liquid diamonds, so Green Crack&apos;s citrus, mango, and skunk character comes from the extract itself.</p><p>Add the 0.5G live resin-infused preroll and you get two full-spectrum experiences for $30.00.</p></Section>
    <Section title="Premium Live Resin AIO + Preroll at a $30 Price Point"><p>Most live resin disposable vapes in California retail between $35 and $50 for 1G. LUIGI delivers both a 1G live resin liquid diamond disposable and a 0.5G live resin-infused preroll for $30.00.</p><p>Formulation, production, packaging, and distribution all happen in-house. No middlemen. No inflated wholesale markups.</p></Section>
    <Section title="Why LUIGI?"><p>Born in Los Angeles and built from the ground up, LUIGI is for people who appreciate quality without the pretense. We combine premium inputs, innovative hardware, and unique formats to create experiences that stand out.</p><p>When you choose LUIGI, you are choosing flavor, potency, consistency, and value in every package.</p></Section>
    <section className="mx-auto max-w-4xl px-6 py-8 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Frequently Asked Questions</h2><div className="mt-5 space-y-3">{faqs.map(([question, answer]) => <details key={question} itemScope itemProp="mainEntity" itemType="https://schema.org/Question" className="rounded-lg border p-4"><summary itemProp="name" className="cursor-pointer font-semibold">{question}</summary><div itemScope itemProp="acceptedAnswer" itemType="https://schema.org/Answer" className="pt-3 leading-7 text-gray-700"><p itemProp="text">{answer}</p></div></details>)}</div></section>
    <section className="mx-auto max-w-4xl px-6 py-12 text-center lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Ready to Experience the Green Crack AIO Dual Pack?</h2><p className="mx-auto mt-5 max-w-2xl leading-8 text-gray-700">A 1G live resin liquid diamond disposable. A 0.5G live resin-infused preroll. Two ways to experience a legendary sativa. Just $30.00.</p><Link href="/dispensary-locator" className="mt-7 inline-flex rounded-full bg-black px-7 py-3 font-semibold text-white">Find a Dispensary for $30</Link></section>
  </main>
}
