import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import { AddToCartButton } from "@/components/add-to-cart-button"

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.luigiofficialbrand.com"
const productUrl = `${siteUrl}/products/manhattan-midnight-aio-dual-pack`
const images = {
  hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790013592-new_york_family-xQxSK50iaUFDFMh4z6z4VIECReNuBD.avif",
  box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new-york_box-EeJZniYXLFoJvCKFXthPAd8nJWmsUC.avif",
  joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new-york_joint-jekLHIDmv9r7OABDNR4Fycvfl5qpwL.avif",
  device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new-york_device-2Xoq8hNuTQGX9jBzp8slNVLzBhywBb.avif",
}
const faqs = [
  ["What's included in the Manhattan Midnight AIO Dual Pack?", "The pack includes a 1G live resin liquid diamond disposable and a 0.5G live resin-infused preroll of Manhattan Midnight."],
  ["What kind of strain is Manhattan Midnight?", "Manhattan Midnight is a balanced hybrid with a rich, evening-friendly profile and a smooth, layered experience."],
  ["What does Manhattan Midnight taste like?", "Expect a deep, earthy flavor with sweet fruit, spice, and a polished finish."],
  ["How much does the Manhattan Midnight AIO Dual Pack cost?", "The LUIGI Manhattan Midnight AIO Dual Pack retails for $30.00."],
  ["What is an AIO disposable?", "AIO means All-In-One. The rechargeable battery and cartridge are built into one simple device."],
  ["How should I store the pack?", "Keep the AIO cool, dark, and dry, and store the preroll in an airtight container."],
]
const productSchema = { "@context": "https://schema.org", "@type": "Product", name: "Manhattan Midnight AIO Dual Pack", brand: { "@type": "Brand", name: "LUIGI" }, description: "Manhattan Midnight live resin liquid diamond disposable plus a 0.5G live resin-infused preroll. $30.00.", sku: "LUIGI-MM-AIO-DUAL", category: "Cannabis > Vape > Disposables & Dual Packs", image: [images.hero, images.box, images.joint, images.device], offers: { "@type": "Offer", priceCurrency: "USD", price: "30.00", availability: "https://schema.org/InStock", url: productUrl } }
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }

export const metadata: Metadata = { title: "Manhattan Midnight AIO Dual Pack | LUIGI Live Resin + Preroll for $30", description: "Shop the Manhattan Midnight 1G live resin liquid diamond disposable with a 0.5G infused preroll from LUIGI for $30.", alternates: { canonical: productUrl }, openGraph: { title: "Manhattan Midnight AIO Dual Pack | LUIGI Cannabis for $30", description: "A 1G live resin AIO and 0.5G infused preroll in one premium dual pack.", url: productUrl, siteName: "LUIGI", type: "website", images: [{ url: images.hero, alt: "LUIGI Manhattan Midnight AIO Dual Pack" }] } }
function ImageCard({ src, alt }: { src: string; alt: string }) { return <div className="relative aspect-square overflow-hidden rounded-xl bg-gray-100"><Image src={src} alt={alt} fill className="object-contain p-6" sizes="(max-width: 768px) 100vw, 33vw" /></div> }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mx-auto max-w-4xl px-6 py-8 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">{title}</h2><div className="mt-5 space-y-5 leading-8 text-gray-700">{children}</div></section> }

export default function ManhattanMidnightPage() {
  const product = { id: "manhattan-midnight-aio-dual-pack", name: "Manhattan Midnight AIO Dual Pack", fullName: "Manhattan Midnight AIO Dual Pack", image: images.hero }
  return <main className="bg-white text-gray-900">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <nav aria-label="Breadcrumb" className="mx-auto max-w-7xl px-6 pt-6 text-sm text-gray-600 lg:px-8"><ol className="flex flex-wrap gap-2"><li><Link href="/products">Products</Link></li><li aria-hidden="true">/</li><li><Link href="/products/lrld-aio">LRLD AIO</Link></li><li aria-hidden="true">/</li><li aria-current="page">Manhattan Midnight AIO Dual Pack</li></ol></nav>
    <section className="mx-auto grid max-w-7xl gap-10 px-6 py-10 lg:grid-cols-2 lg:px-8"><ImageCard src={images.hero} alt="LUIGI Manhattan Midnight AIO Dual Pack with live resin disposable and preroll" /><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#9a7b16]">LRLD AIO Dual Pack</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-gray-950 lg:text-6xl">Manhattan Midnight AIO Dual Pack: Live Resin Liquid Diamond Disposable + Infused Preroll</h1><p className="mt-5 text-xl font-medium">Big city flavor, made for slower moments.</p><p className="mt-5 leading-8 text-gray-700">A 1G live resin liquid diamond disposable paired with a 0.5G live resin-infused preroll. Manhattan Midnight brings a rich, balanced hybrid profile to two easy formats, giving you a convenient AIO for quick sessions and a preroll for a fuller flower experience.</p><p className="mt-5 font-semibold">Hybrid | 1G AIO Disposable + 0.5G Preroll | Live Resin + Liquid Diamonds</p><p className="mt-5 text-3xl font-bold">$30.00</p><AddToCartButton product={product} price="30" priceNumber={30} className="mt-6" /></div></section>
    <section aria-label="Manhattan Midnight product gallery" className="mx-auto max-w-7xl px-6 pb-10 lg:px-8"><div className="grid gap-6 sm:grid-cols-3"><ImageCard src={images.box} alt="Manhattan Midnight dual pack box" /><ImageCard src={images.device} alt="Manhattan Midnight live resin AIO device" /><ImageCard src={images.joint} alt="Manhattan Midnight live resin-infused preroll" /></div></section>
    <Section title="Two Ways to Experience Manhattan Midnight"><p>This is more than a vape or a preroll. It is a paired experience. The 1G AIO delivers smooth, terpene-rich vapor when convenience matters, while the 0.5G infused preroll lets you slow down and enjoy the strain in a more traditional format.</p><p>Both formats are made with the same Manhattan Midnight profile, so you can choose the format that fits the moment without giving up flavor or character.</p><p>At $30.00, the dual pack gives you premium inputs and in-house production without unnecessary markup.</p></Section>
    <Section title="What&apos;s Inside the Manhattan Midnight AIO Dual Pack"><div className="overflow-x-auto"><table className="w-full text-left"><tbody>{[["AIO Disposable", "1 × 1G live resin liquid diamond disposable"], ["Preroll", "1 × 0.5G live resin-infused preroll"], ["Strain", "Manhattan Midnight"], ["Type", "Hybrid"], ["Effects", "Balanced, relaxed, happy, focused"], ["Flavor", "Earthy, sweet, fruity, and lightly spiced"], ["Price", "$30.00"]].map(([label, value]) => <tr key={label} className="border-b"><th className="py-3 pr-4 font-semibold">{label}</th><td className="py-3">{value}</td></tr>)}</tbody></table></div></Section>
    <Section title="Manhattan Midnight: A Rich Hybrid Profile"><p>Manhattan Midnight is built for people who want a balanced experience with depth. Its flavor starts earthy and smooth, then opens into sweeter fruit and subtle spice. The result feels polished rather than overpowering.</p><p>The hybrid profile works well for evening sessions, creative downtime, social plans, or any moment when you want to settle in without feeling disconnected.</p><p>The AIO makes the profile easy to enjoy on the go, while the preroll gives the flower character more room to come through.</p></Section>
    <Section title="Flavor and Effects"><p>Expect a layered blend of earth, sweet fruit, and gentle spice. The inhale is smooth and rounded, with a lingering finish that keeps the profile interesting from the first draw to the last.</p><p>Consumers often look for balanced effects from Manhattan Midnight: a calm body feel, a lighter mood, and enough focus to stay present. As always, start with a small amount and give the experience time to develop.</p></Section>
    <Section title="Why We Use Live Resin and Liquid Diamonds"><p>Many disposable vapes use distillate, which can deliver potency but often loses much of the plant&apos;s original terpene character. Live resin helps preserve those natural aromatic compounds, while liquid diamonds add a concentrated THC experience.</p><p>Pairing the AIO with a live resin-infused preroll gives you two complementary ways to enjoy the same strain profile.</p></Section>
    <Section title="How to Enjoy the Manhattan Midnight AIO Dual Pack"><p><strong>The AIO:</strong> Take a slow, even draw and let the vapor settle before taking another. The rechargeable all-in-one design keeps the session simple.</p><p><strong>The preroll:</strong> Use it when you have time for a longer, more intentional session and want the fuller character of infused flower.</p><p><strong>Storage:</strong> Keep both formats cool, dark, and dry. Store the preroll in an airtight container.</p></Section>
    <Section title="How Manhattan Midnight Compares to Distillate Vapes"><p>Distillate products may rely on added flavor to recreate a strain profile. Live resin keeps more of the natural character intact, so the earthy, sweet, and lightly spiced notes feel more connected to the plant.</p><p>The dual pack also gives you a second format, making it easier to choose between quick convenience and a slower flower session.</p></Section>
    <Section title="Premium Live Resin at a $30 Price Point"><p>A 1G live resin liquid diamond disposable and a 0.5G live resin-infused preroll can quickly add up when purchased separately. LUIGI brings both into one $30.00 dual pack.</p><p>With formulation, production, packaging, and distribution handled in-house, the focus stays on consistent quality and a straightforward price.</p></Section>
    <Section title="Why LUIGI?"><p>LUIGI was born in Los Angeles for people who care about quality without the pretense. We pair premium inputs with practical formats, thoughtful hardware, and flavor-forward experiences.</p><p>Every pack is designed to make the choice simple: more character, more flexibility, and better value in one package.</p></Section>
    <section className="mx-auto max-w-4xl px-6 py-8 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Frequently Asked Questions</h2><div className="mt-5 space-y-3">{faqs.map(([question, answer]) => <details key={question} itemScope itemProp="mainEntity" itemType="https://schema.org/Question" className="rounded-lg border p-4"><summary itemProp="name" className="cursor-pointer font-semibold">{question}</summary><div itemScope itemProp="acceptedAnswer" itemType="https://schema.org/Answer" className="pt-3 leading-7 text-gray-700"><p itemProp="text">{answer}</p></div></details>)}</div></section>
    <section className="mx-auto max-w-4xl px-6 py-12 text-center lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Ready for Manhattan Midnight?</h2><p className="mx-auto mt-5 max-w-2xl leading-8 text-gray-700">A 1G live resin AIO and a 0.5G infused preroll in one premium dual pack. Just $30.00.</p><Link href="/dispensary-locator" className="mt-7 inline-flex rounded-full bg-black px-7 py-3 font-semibold text-white">Find a Dispensary for $30</Link></section>
  </main>
}
