import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import { AddToCartButton } from "@/components/add-to-cart-button"

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.luigiofficialbrand.com"
const productUrl = `${siteUrl}/products/private-reserve-aio-dual-pack`
const images = {
  hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790014743-dubai_family-K8QzPho5h62yKJ2WyjX7PgDo7F4gAN.avif",
  box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dubai_box-qbBVgucWsgmWGzVDbYCh8M5jfpPiZq.avif",
  joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dubai_joint-KEFJBwvmvY4W7iTM8rzxALHfkbLdjY.avif",
  device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dubai_device-GLaRBvRxrv9Lohb7VQECwHTlRfTukt.avif",
}
const keywords = ["private reserve aio", "private reserve dual pack", "private reserve disposable", "private reserve vape", "private reserve preroll", "private reserve strain", "private reserve hybrid", "premium reserve weed", "exclusive weed strains", "rare weed strains", "refined hybrid strains", "layered flavor weed", "luxury cannabis strains", "hybrid vape California", "hybrid disposable", "hybrid AIO", "live resin disposable", "liquid diamond disposable", "live resin vape California", "liquid diamond vape", "aio disposable vape", "all in one vape", "disposable + preroll combo", "vape and preroll pack", "dual pack cannabis", "aio vape + preroll pack", "LUIGI cannabis vapes", "LUIGI AIO", "$30 AIO pack", "premium live resin vape", "California live resin vape", "cannabis vape delivery Los Angeles", "1G disposable vape", "0.5g infused preroll"]
const faqs = [
  ["What's included in the Private Reserve AIO Dual Pack?", "The pack includes a 1G live resin liquid diamond disposable plus a 0.5G live resin-infused preroll of the same strain, Private Reserve. Two formats, one exclusive reserve."],
  ["What strain is in the Private Reserve AIO Dual Pack?", "Private Reserve is a refined hybrid known for rich, layered flavor and an unmistakably premium character. It is built for the moments worth saving."],
  ["Is Private Reserve indica, sativa, or hybrid?", "Hybrid. Expect balanced effects that feel smooth, composed, and elevated, with a gentle body calm that follows."],
  ["What does Private Reserve taste like?", "Rich, layered, and refined, with a smooth, lasting hybrid finish."],
  ["What effects does Private Reserve produce?", "Private Reserve delivers a composed head-lift followed by gentle body calm. It sits between sativa energy and indica relaxation."],
  ["What is an AIO disposable?", "AIO stands for All-In-One. It is a rechargeable, self-contained vape with the cartridge and battery built into one unit."],
  ["What's the difference between the AIO and the preroll?", "The AIO delivers smooth, terpene-rich vapor in a portable format. The preroll delivers the fuller flower experience of smoking Private Reserve."],
  ["How much does the Private Reserve AIO Dual Pack cost?", "The LUIGI Private Reserve AIO Dual Pack retails for $30.00 and includes both formats."],
  ["How strong is the AIO disposable?", "The AIO contains 1G of live resin and liquid diamonds. Check the package or dispensary listing for current batch test results."],
  ["How should I store my AIO and preroll?", "Keep the AIO cool, dark, and dry away from heat and sunlight. Store the preroll in an airtight container."],
  ["Can I buy LUIGI AIO Dual Packs for delivery in Los Angeles?", "LUIGI products are available through licensed California dispensaries and delivery services, subject to local availability."],
  ["What's the difference between live resin and distillate?", "Live resin preserves more natural terpenes for a fuller flavor, while distillate removes most of them and can taste flatter."],
]
const productSchema = { "@context": "https://schema.org", "@type": "Product", name: "Private Reserve AIO Dual Pack", brand: { "@type": "Brand", name: "LUIGI" }, description: "Private Reserve live resin liquid diamond disposable (1G) plus 0.5G live resin-infused preroll. Refined hybrid with rich, layered flavor and balanced, elevated effects. $30.00.", sku: "LUIGI-PR-AIO-DUAL", category: "Cannabis > Vape > Disposables & Dual Packs", image: [images.hero, images.box, images.joint, images.device], offers: { "@type": "Offer", priceCurrency: "USD", price: "30.00", availability: "https://schema.org/InStock", url: productUrl }, keywords: keywords.join(", ") }
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }

export const metadata: Metadata = { title: "Private Reserve AIO Dual Pack | LUIGI Live Resin + Preroll for $30", description: "Private Reserve live resin liquid diamond disposable + 0.5g infused preroll. 1G AIO + 0.5G preroll. Just $30. Shop LUIGI in California.", keywords, alternates: { canonical: productUrl }, openGraph: { title: "Private Reserve AIO Dual Pack | LUIGI Cannabis for $30", description: "Private Reserve live resin liquid diamond disposable + 0.5g infused preroll. 1G AIO + 0.5G preroll. Just $30.", url: productUrl, siteName: "LUIGI", type: "website", images: [{ url: images.hero, alt: "LUIGI Private Reserve AIO Dual Pack" }] } }
function ImageCard({ src, alt }: { src: string; alt: string }) { return <div className="relative aspect-square overflow-hidden rounded-xl bg-gray-100"><Image src={src} alt={alt} fill className="object-contain p-6" sizes="(max-width: 768px) 100vw, 33vw" /></div> }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mx-auto max-w-4xl px-6 py-8 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">{title}</h2><div className="mt-5 space-y-5 leading-8 text-gray-700">{children}</div></section> }

export default function PrivateReservePage() {
  const product = { id: "private-reserve-aio-dual-pack", name: "Private Reserve AIO Dual Pack", fullName: "Private Reserve AIO Dual Pack", image: images.hero }
  return <main className="bg-white text-gray-900"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <nav aria-label="Breadcrumb" className="mx-auto max-w-7xl px-6 pt-6 text-sm text-gray-600 lg:px-8"><ol className="flex flex-wrap gap-2"><li><Link href="/products">Products</Link></li><li aria-hidden="true">/</li><li><Link href="/products/lrld-aio">LRLD AIO</Link></li><li aria-hidden="true">/</li><li aria-current="page">Private Reserve AIO Dual Pack</li></ol></nav>
    <section className="mx-auto grid max-w-7xl gap-10 px-6 py-10 lg:grid-cols-2 lg:px-8"><div>{/* Slot 1: Hero */}<ImageCard src={images.hero} alt="LUIGI Private Reserve AIO Dual Pack: live resin disposable and preroll" /></div><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#9a7b16]">LRLD AIO Dual Pack</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-gray-950 lg:text-6xl">Private Reserve AIO Dual Pack: Live Resin Liquid Diamond Disposable + Infused Preroll</h1><p className="mt-5 text-xl font-medium">For the moments worth saving.</p><p className="mt-5 leading-8 text-gray-700">A 1G live resin liquid diamond disposable plus a 0.5G live resin-infused preroll of the same strain, Private Reserve. Rare in spirit, bold in character, with a rich hybrid profile and a refined edge.</p><p className="mt-5 font-semibold">Hybrid | 1G AIO Disposable + 0.5G Preroll | Live Resin + Liquid Diamonds</p><p className="mt-5 text-3xl font-bold">$30.00</p><AddToCartButton product={product} price="30" priceNumber={30} className="mt-6" /></div></section>
    <section aria-label="Private Reserve product gallery" className="mx-auto max-w-7xl px-6 pb-10 lg:px-8"><div className="grid gap-6 sm:grid-cols-3"><div>{/* Slot 2: Pack Contents */}<ImageCard src={images.box} alt="Private Reserve 1G live resin liquid diamond disposable and 0.5g infused preroll" /></div><div>{/* Slot 3: AIO Device Close-Up */}<ImageCard src={images.device} alt="Close-up of LUIGI Private Reserve live resin liquid diamond AIO disposable" /></div><div>{/* Slot 4: Preroll Close-Up */}<ImageCard src={images.joint} alt="LUIGI Private Reserve 0.5g live resin infused preroll" /></div></div></section>
    <Section title="Two Ways to Experience Private Reserve in One Pack"><p>This isn&apos;t just a vape or just a preroll. It&apos;s a paired experience. The AIO delivers smooth, potent, terpene-rich vapor with the convenience of a rechargeable all-in-one device. The preroll delivers the full-flavor, full-spectrum experience of smoking Private Reserve flower.</p><p>Two formats give you two premium ways to experience the same refined hybrid. At $30.00, you get a 1G AIO and a 0.5G preroll with premium inputs and in-house production.</p></Section>
    <Section title="What&apos;s Inside the Private Reserve AIO Dual Pack"><div className="overflow-x-auto"><table className="w-full text-left"><tbody>{[["AIO Disposable", "1 × 1G live resin liquid diamond disposable"], ["Preroll", "1 × 0.5G live resin-infused preroll"], ["Total Formats", "2 (vape + preroll)"], ["Strain", "Private Reserve"], ["Type", "Hybrid"], ["Flavor Profile", "Rich, layered, refined hybrid finish"], ["Price", "$30.00"]].map(([label, value]) => <tr key={label} className="border-b"><th className="py-3 pr-4 font-semibold">{label}</th><td className="py-3">{value}</td></tr>)}</tbody></table></div></Section>
    <Section title="Private Reserve: Rare in Spirit, Bold in Character"><p>Private Reserve is a hybrid built for people who save the best for the moments that matter. The flavor opens rich and layered, bold, complex, and unmistakably premium. Refined notes come forward as the profile develops, adding depth without overwhelming the palate.</p><p>It feels like an occasion: sophisticated, rare, and crafted for the moments worth saving. Whether you draw from the AIO or light the preroll, Private Reserve delivers an elevated, layered hybrid experience.</p><p><strong>A quick format note:</strong> the preroll delivers the closest expression of Private Reserve&apos;s classic flower profile.</p></Section>
    <Section title="Private Reserve Effects: Balanced, Refined, Elevated"><p>Private Reserve starts smooth and composed, with the kind of head-lift that pairs well with meaningful moments, good company, or a quiet evening. As the experience settles in, a gentle body calm follows without weighing you down.</p><p>It is not a heavy indica or a racy sativa. It sits in the sweet spot between the two, making it a natural fit for celebrations, quiet evenings, creative sessions, or any time you want to feel elevated and present.</p></Section>
    <Section title="Rich, Layered, Refined: A Flavor Experience Worth Savoring"><p>The first notes are rich, layered, and unmistakably premium. As the smoke or vapor develops, refined notes add depth and sophistication. The finish is clean and lasting, rewarding slow, intentional draws.</p><p>Both the AIO and the preroll deliver a full-flavor, terpene-rich experience that gives the profile room to develop.</p></Section>
    <Section title="Why We Use Live Resin and Liquid Diamonds"><p>Most disposable vapes use distillate, a refined THC extract that is potent but stripped of much of the plant&apos;s natural terpene character. The result can feel flat and one-dimensional.</p><p>LUIGI uses live resin and liquid diamonds instead. Live resin preserves natural terpenes for a flavorful, aromatic vape, while liquid diamonds add a potent crystalline THC punch. The live resin-infused preroll gives you a second full-spectrum experience.</p></Section>
    <Section title="How to Enjoy the Private Reserve AIO Dual Pack"><p><strong>The AIO:</strong> Draw slowly and evenly for a smooth, terpene-rich hit. The rechargeable device delivers consistent vapor from the first draw to the last.</p><p><strong>The preroll:</strong> Save it for a slower, more intentional session and enjoy the full-flavor experience of Private Reserve flower.</p><p><strong>The pairing:</strong> Use the AIO for a quick lift and follow up with the preroll for a deeper session. Store both formats cool, dark, and dry.</p></Section>
    <Section title="How Private Reserve Compares to Distillate Vapes"><p>Distillate often has flavor added back artificially. LUIGI uses live resin and liquid diamonds, so the rich, layered character comes from the extract itself rather than a flavor additive.</p><p>With the 0.5G live resin-infused preroll included, you get two full-spectrum experiences for $30.00.</p></Section>
    <Section title="Premium Live Resin AIO + Preroll at a $30 Price Point"><p>A 1G live resin disposable and a preroll can quickly cost more when purchased separately. LUIGI delivers both in one $30.00 dual pack.</p><p>Formulation, production, packaging, and distribution happen in-house. No middlemen and no inflated wholesale markups, just a premium product priced fairly.</p></Section>
    <Section title="Why LUIGI?"><p>Born in Los Angeles and built from the ground up, LUIGI is for people who appreciate quality without the pretense. We combine premium inputs, innovative hardware, and unique formats to create experiences that stand out.</p><p>When you choose LUIGI, you are choosing flavor, potency, consistency, and value in every package.</p></Section>
    <section className="mx-auto max-w-4xl px-6 py-8 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Frequently Asked Questions</h2><div className="mt-5 space-y-3">{faqs.map(([question, answer]) => <details key={question} itemScope itemProp="mainEntity" itemType="https://schema.org/Question" className="rounded-lg border p-4"><summary itemProp="name" className="cursor-pointer font-semibold">{question}</summary><div itemScope itemProp="acceptedAnswer" itemType="https://schema.org/Answer" className="pt-3 leading-7 text-gray-700"><p itemProp="text">{answer}</p></div></details>)}</div></section>
    <section className="mx-auto max-w-4xl px-6 py-12 text-center lg:px-8">{/* Slot 8: Final CTA */}<h2 className="text-3xl font-bold text-gray-950">Ready to Experience the Private Reserve AIO Dual Pack?</h2><p className="mx-auto mt-5 max-w-2xl leading-8 text-gray-700">A 1G live resin liquid diamond disposable. A 0.5G live resin-infused preroll. Two ways to experience a rare, refined hybrid. Just $30.00.</p><Link href="/dispensary-locator" className="mt-7 inline-flex rounded-full bg-black px-7 py-3 font-semibold text-white">Find a Dispensary for $30</Link></section>
  </main>
}
