import Image from "next/image"
import Link from "next/link"
import type { Metadata } from "next"
import Script from "next/script"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { AgeVerification } from "@/components/age-verification"
import { AddToCartButton } from "@/components/add-to-cart-button"

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.luigiofficialbrand.com"
const productUrl = `${siteUrl}/products/acapulco-gold-aio-dual-pack`
const images = {
  hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790013755-mexico_city_family-YROupYzATIAGnoHEHdzEkN11s8U5tB.avif",
  joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mexico-city_joint-RZAkmzZVTi9TwHTLXyG67uA5wButB8.avif",
  device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mexico-city_device-sM9kgoJU1VaN0SJXLDyN6ecOrOpTAD.avif",
  box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mexico-city_box-iGc6DShubz5uy7kEn79zSNcMwjC2rs.avif",
}
const keywords = ["acapulco gold aio", "acapulco gold dual pack", "acapulco gold disposable", "acapulco gold vape", "acapulco gold preroll", "acapulco gold strain", "acapulco gold sativa", "live resin disposable", "liquid diamond disposable", "live resin vape California", "liquid diamond vape", "aio disposable vape", "all in one vape", "disposable + preroll combo", "vape and preroll pack", "dual pack cannabis", "sativa vape California", "sativa disposable", "legendary sativa strains", "landrace sativa strains", "mexican landrace strains", "aio vape + preroll pack", "LUIGI cannabis vapes", "LUIGI AIO", "$30 AIO pack", "premium live resin vape", "California live resin vape", "cannabis vape delivery Los Angeles", "1G disposable vape", "0.5g infused preroll"]
const faq = [
  ["What's included in the Acapulco Gold AIO Dual Pack?", "The pack includes a 1G live resin liquid diamond disposable plus a 0.5G live resin-infused preroll of the same strain — Acapulco Gold. Two formats, one iconic experience."],
  ["What strain is in the Acapulco Gold AIO Dual Pack?", "Acapulco Gold is a legendary Mexican landrace sativa, bred from Mexican and Nepalese genetics. It is known for chunky golden-brown colas, a burnt toffee aroma, and bright, energetic effects."],
  ["Is Acapulco Gold indica, sativa, or hybrid?", "Sativa. Acapulco Gold delivers bright, cerebral effects that lean energetic, creative, and happy — ideal for daytime, outdoor, or creative sessions."],
  ["What does Acapulco Gold taste like?", "Earthy, pungent, and skunky up front, with blueberry notes and bold earthy-citrus undertones. Bright, tropical, and unmistakably Acapulco Gold."],
  ["What effects does Acapulco Gold produce?", "Consumers consistently report feeling happy, creative, and energetic. The high is bright and cerebral, mood-lifting, and creativity-sparking."],
  ["What is an AIO disposable?", "AIO stands for All-In-One. It is a rechargeable, self-contained vape device with the cartridge and battery built into a single unit."],
  ["What's the difference between the AIO and the preroll?", "The AIO delivers smooth, terpene-rich vapor with portable convenience. The preroll delivers the full-flavor, full-spectrum experience of smoking Acapulco Gold flower."],
  ["How much does the Acapulco Gold AIO Dual Pack cost?", "The LUIGI Acapulco Gold AIO Dual Pack retails for $30.00 and includes a 1G live resin liquid diamond disposable plus a 0.5G live resin-infused preroll."],
  ["How strong is the AIO disposable?", "The AIO contains 1G of live resin and liquid diamonds. Exact THC percentage varies by batch, so check the packaging or dispensary listing for current test results."],
  ["How should I store my AIO and preroll?", "Keep the AIO cool, dark, and dry away from direct sunlight and heat. Store the preroll in an airtight container."],
  ["Can I buy LUIGI AIO Dual Packs for delivery in Los Angeles?", "LUIGI products are available through licensed California dispensaries. Check your local retailer or delivery service for availability."],
  ["What's the difference between live resin and distillate?", "Live resin preserves natural terpenes for a flavorful, aromatic vape. Distillate strips most terpenes out, resulting in flatter flavor and a more one-dimensional effect."]
] as const
const schema = { "@context": "https://schema.org", "@type": "Product", "name": "Acapulco Gold AIO Dual Pack", "brand": { "@type": "Brand", "name": "LUIGI" }, "description": "Acapulco Gold live resin liquid diamond disposable (1G) plus 0.5G live resin-infused preroll. Legendary Mexican landrace sativa with happy, creative, energetic effects. $30.00.", "sku": "LUIGI-AG-AIO-DUAL", "category": "Cannabis > Vape > Disposables & Dual Packs", "image": Object.values(images), "keywords": keywords.join(", "), "offers": { "@type": "Offer", "priceCurrency": "USD", "price": "30.00", "availability": "https://schema.org/InStock", "url": productUrl } }
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }
function SlotImage({ src, alt, comment }: { src: string; alt: string; comment: string }) { return <div className="relative aspect-square overflow-hidden rounded-xl bg-gray-100">{/* {comment} */}<Image src={src} alt={alt} fill className="object-contain p-6" sizes="(max-width: 768px) 100vw, 50vw" /></div> }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold tracking-tight text-gray-950">{title}</h2><div className="mt-5 space-y-5 text-lg leading-8 text-gray-700">{children}</div></section> }
export const metadata: Metadata = { title: "Acapulco Gold AIO Dual Pack | LUIGI Live Resin + Preroll — $30", description: "Acapulco Gold live resin liquid diamond disposable + 0.5g infused preroll. 1G AIO + 0.5G preroll. Just $30. Shop LUIGI in California.", keywords, alternates: { canonical: productUrl }, openGraph: { title: "Acapulco Gold AIO Dual Pack | LUIGI Cannabis — $30", description: "Acapulco Gold live resin liquid diamond disposable + 0.5G infused preroll. 1G AIO + 0.5G preroll. Just $30.", url: productUrl, siteName: "LUIGI", type: "website", images: [{ url: images.hero, alt: "LUIGI Acapulco Gold AIO Dual Pack" }] } }
export default function AcapulcoGoldAioPage() { return <><Script id="acapulco-product-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><Script id="acapulco-faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><AgeVerification /><Header /><main className="bg-white pt-16 lg:pt-20">
<section className="mx-auto max-w-7xl px-6 py-12 lg:px-8"><nav aria-label="Breadcrumb" className="mb-8 text-sm text-gray-500"><Link href="/products">Products</Link><span className="px-2">/</span><Link href="/products/lrld-aio">LRLD AIO</Link><span className="px-2">/</span><span className="text-gray-950">Acapulco Gold</span></nav><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><SlotImage src={images.hero} alt="LUIGI Acapulco Gold AIO Dual Pack — live resin disposable + preroll" comment="Slot 1 — Hero" /><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#9a7b16]">LRLD AIO Dual Pack</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-gray-950 lg:text-6xl">Acapulco Gold AIO Dual Pack — Live Resin Liquid Diamond Disposable + Infused Preroll</h1><p className="mt-5 text-2xl font-semibold text-gray-950">Chase the sun.</p><p className="mt-5 text-lg leading-8 text-gray-600">A 1G live resin liquid diamond disposable plus a 0.5G live resin-infused pre-roll of the same strain. Double the flavor, one iconic experience. Acapulco Gold is a legendary sativa celebrated for its bright, tropical character and bold, earthy-citrus flavor.</p><p className="mt-5 font-medium text-gray-700">Sativa | 1G AIO Disposable + 0.5G Preroll | Live Resin + Liquid Diamonds</p><p className="mt-6 text-3xl font-bold text-gray-950">$30.00</p><AddToCartButton product={{ id: "acapulco-gold-aio-dual-pack", name: "Acapulco Gold AIO Dual Pack", fullName: "Acapulco Gold AIO Dual Pack", image: images.hero }} price="30" priceNumber={30} className="mt-6" /></div></div></section>
<Section title="Two Ways to Experience Acapulco Gold — One Pack"><p>This isn&apos;t just a vape or just a preroll. It&apos;s a paired experience. Each LUIGI V11 AIO Dual Pack pairs a 1G live resin liquid diamond disposable with a 0.5G live resin-infused preroll of the same strain — Acapulco Gold.</p><p>The AIO delivers smooth, potent, terpene-rich vapor with the convenience of a rechargeable all-in-one device. The preroll delivers the full-flavor, full-spectrum experience of smoking Acapulco Gold flower. Together, they give you two ways to experience the same legendary sativa — chase the sun with the vape, savor the flower with the preroll.</p><p>At $30.00, you&apos;re getting a 1G AIO and a 0.5G preroll in one package — premium inputs and in-house production, without the inflated markup most dual-format packs carry.</p></Section>
<section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><SlotImage src={images.box} alt="Acapulco Gold 1G live resin liquid diamond disposable and 0.5g infused preroll" comment="Slot 2 — Pack Contents" /><h2 className="mt-10 text-3xl font-bold text-gray-950">What&apos;s Inside the Acapulco Gold AIO Dual Pack</h2><div className="mt-5 overflow-x-auto"><table className="w-full border-collapse text-left"><tbody>{[["AIO Disposable","1× 1G live resin liquid diamond disposable"],["Preroll","1× 0.5G live resin-infused preroll"],["Total Formats","2 (vape + preroll)"],["Strain","Acapulco Gold"],["Type","Sativa"],["Genetics","Mexican × Nepalese (landrace)"],["Effects","Happy, Creative, Energetic"],["Flavor Profile","Skunk, blueberry, pungent, earthy-citrus"],["Price","$30.00"]].map(([a,b]) => <tr key={a} className="border-b border-gray-200"><th className="p-4 font-semibold text-gray-950">{a}</th><td className="p-4 text-gray-700">{b}</td></tr>)}</tbody></table></div></section>
<Section title="Acapulco Gold — A Legendary Mexican Landrace"><p>Acapulco Gold is one of the most iconic strains in cannabis history — a legendary Mexican landrace that has become increasingly rare as indoor cultivation dominates the market. Its chunky, golden-brown colas carry a distinctive burnt toffee aroma that translates to earthy, pungent flavors with bright, tropical undertones.</p><p>A cross of Mexican and Nepalese genetics, Acapulco Gold has earned its place in cannabis lore. The effects are energetic and cerebral — the kind of sativa that sparks creativity, elevates mood, and keeps you engaged from start to finish. If you&apos;ve never tried a true landrace sativa, this is the one.</p><p><strong>Format note:</strong> The experience may not reflect the strain in this category due to the format of the AIO disposable. The preroll delivers the closest expression of Acapulco Gold&apos;s classic flower profile.</p><SlotImage src={images.joint} alt="Acapulco Gold strain — golden-brown landrace sativa flower" comment="Slot 5 — Strain / Flower Detail" /></Section>
<Section title="Acapulco Gold Effects: Happy, Creative, Energetic"><p>Consumers consistently report three signature effects from Acapulco Gold: happy, creative, and energetic. The high is bright and cerebral — a mood-lifting, creativity-sparking experience that&apos;s perfect for daytime sessions, outdoor adventures, or anytime you want to feel elevated and inspired without being weighed down.</p><p>It&apos;s not a racy or anxious sativa. The high is smooth and easygoing, with a natural lift that keeps you engaged with whatever you&apos;re doing. Whether you&apos;re chasing a creative project or chasing the sun, Acapulco Gold delivers the kind of legendary sativa experience that made it famous.</p></Section>
<Section title="Skunk, Blueberry, Pungent — A Flavor Experience Worth Savoring"><p>Acapulco Gold delivers a flavor profile that&apos;s as legendary as its name. The first notes are earthy and pungent — grounded and classic. As the smoke or vapor develops, skunk and blueberry notes come forward, adding depth and brightness. Bold, earthy-citrus undertones round out the profile, giving the experience a bright, tropical character that&apos;s unmistakable.</p><p>Whether you&apos;re drawing from the AIO or lighting the preroll, Acapulco Gold delivers a full-flavor, terpene-rich experience that rewards slow, intentional draws.</p></Section>
<Section title="Why We Use Live Resin and Liquid Diamonds"><p>Most disposable vapes use distillate — a refined THC extract that&apos;s potent but stripped of the plant&apos;s natural terpenes and minor cannabinoids. The result is a vape that gets you high, but the flavor feels flat and the effect feels one-dimensional.</p><p>LUIGI AIO Dual Packs use live resin and liquid diamonds instead. Live resin preserves natural terpenes for a flavorful, aromatic vape. Liquid diamonds add a potent, crystalline THC punch. Together, they create a vape that&apos;s both smooth and strong. Because the pack also includes a live resin-infused preroll, you get two full-spectrum experiences instead of one.</p><SlotImage src={images.device} alt="Close-up of LUIGI Acapulco Gold live resin liquid diamond AIO disposable" comment="Slot 3 — AIO Device Close-Up" /></Section>
<Section title="How to Enjoy the Acapulco Gold AIO Dual Pack"><p><strong>The AIO Disposable:</strong> Draw slowly and evenly for a smooth, terpene-rich hit. The rechargeable device delivers consistent vapor from the first draw to the last.</p><p><strong>The Preroll:</strong> Save it for a slower, more intentional session. The live resin-infused preroll delivers the full-flavor, full-spectrum experience of smoking Acapulco Gold flower.</p><p><strong>The Pairing:</strong> Use the AIO for a quick lift and follow up with the preroll for a deeper, more layered session. The combination gives you both formats of the same strain.</p><p><strong>Storage:</strong> Keep the AIO in a cool, dark, dry place away from direct sunlight and heat. Store the preroll in an airtight container.</p></Section>
<Section title="How the Acapulco Gold AIO Dual Pack Compares to Distillate Vapes"><p>Most disposable vapes use distillate — a refined THC extract stripped of most natural terpenes and minor cannabinoids. Flavor is typically added back artificially and the effect can feel flat.</p><p>The LUIGI Acapulco Gold AIO Dual Pack uses live resin and liquid diamonds. Live resin retains terpenes, flavonoids, and minor cannabinoids, so the skunk, blueberry, and earthy-citrus flavor comes from the same place as the effect — not a flavor additive. Add a 0.5G live resin-infused preroll and you&apos;re getting two full-spectrum experiences for $30.00.</p></Section>
<Section title="Premium Live Resin AIO + Preroll at a $30 Price Point"><p>Most live resin disposable vapes in California retail between $35 and $50 for a 1G format. Adding a preroll typically pushes the total past $40. LUIGI delivers both — a 1G live resin liquid diamond disposable and a 0.5G live resin-infused preroll — for just $30.00.</p><p>Everything starts in-house: formulation, production, packaging, and distribution. No middlemen. No inflated wholesale markups. Just premium cannabis products priced fairly for the people who actually smoke them.</p></Section>
<Section title="Why LUIGI?"><p>Born in Los Angeles and built from the ground up, LUIGI is a cannabis brand for people who appreciate quality without the pretense. Everything starts in-house, giving us complete control over every product that carries our name.</p><p>We combine premium inputs, innovative hardware, and unique formats to create experiences that stand out. Whether it&apos;s our signature Dual Packs, rosin-infused products, Fattone collections, or limited-edition drops, LUIGI is committed to flavor, potency, consistency, and value.</p><p>We&apos;re inspired by art, culture, hospitality, and the communities that support us. LUIGI isn&apos;t just a cannabis brand — it&apos;s a movement built around bringing people together and making every session more memorable.</p><SlotImage src={images.box} alt="LUIGI cannabis brand — quality without pretense, Los Angeles" comment="Slot 7 — Brand / Lifestyle" /></Section>
<section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Frequently Asked Questions</h2><div className="mt-5 space-y-3">{faq.map(([question, answer]) => <details key={question} className="rounded-lg border border-gray-200 p-5" itemScope itemProp="mainEntity" itemType="https://schema.org/Question"><summary className="cursor-pointer font-semibold text-gray-950" itemProp="name">{question}</summary><div className="mt-3 leading-7 text-gray-700" itemScope itemProp="acceptedAnswer" itemType="https://schema.org/Answer"><p itemProp="text">{answer}</p></div></details>)}</div></section>
<Section title="Ready to Experience the Acapulco Gold AIO Dual Pack?"><p>A 1G live resin liquid diamond disposable. A 0.5G live resin-infused preroll. Two ways to experience a legendary sativa. Just $30.00. Find LUIGI at a licensed California dispensary near you.</p><SlotImage src={images.hero} alt="Buy LUIGI Acapulco Gold AIO Dual Pack at a California dispensary for $30" comment="Slot 8 — Final CTA" /><Link href="/products/lrld-aio" className="mt-6 inline-flex rounded-full bg-black px-7 py-4 font-semibold text-white">Find a Dispensary — $30</Link></Section>
</main><Footer /></> }
export const runtime = "nodejs"
export { productUrl }
