import Image from "next/image"
import Link from "next/link"
import type { Metadata } from "next"
import Script from "next/script"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { AgeVerification } from "@/components/age-verification"
import { AddToCartButton } from "@/components/add-to-cart-button"

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.luigiofficialbrand.com"
const productUrl = `${siteUrl}/products/bubblegum-kush-aio-dual-pack`
const images = {
  hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790013959-hollywood_family-lvflB1XEERxiqSzFHOlWKfWqmMU63x.avif",
  box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hollywood_box-VxQWXEXEB7Bt3AZn4q8GUWcKtRPsAO.avif",
  joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hollywood_joint-ayvR9PO2q0AzfKYXJPMqo6UuGIZ578.avif",
  device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hollywood_device-2V6WnNdQKqr2FkQRv8awTiqB9x7cxH.avif",
}
const keywords = ["bubblegum kush aio", "bubblegum kush dual pack", "bubblegum kush disposable", "bubblegum kush vape", "bubblegum kush preroll", "bubblegum kush strain", "bubblegum kush hybrid", "the bulldog seeds bubblegum kush", "bubble gum strain", "sweet weed strains", "fruity weed strains", "candy weed strains", "live resin disposable", "liquid diamond disposable", "live resin vape California", "liquid diamond vape", "aio disposable vape", "all in one vape", "disposable + preroll combo", "vape and preroll pack", "dual pack cannabis", "hybrid vape California", "hybrid disposable", "aio vape + preroll pack", "LUIGI cannabis vapes", "LUIGI AIO", "$30 AIO pack", "premium live resin vape", "California live resin vape", "cannabis vape delivery Los Angeles", "1G disposable vape", "0.5g infused preroll"]
const faq = [
  ["What's included in the Bubblegum Kush AIO Dual Pack?", "The pack includes a 1G live resin liquid diamond disposable plus a 0.5G live resin-infused preroll of the same strain — Bubblegum Kush. Two formats, one deliciously balanced experience."],
  ["What strain is in the Bubblegum Kush AIO Dual Pack?", "Bubblegum Kush is a hybrid strain bred from Bubble Gum genetics by The Bulldog Seeds in Amsterdam. It is known for sweet, fruity bubblegum flavor, a sour citrus twist, and a giggly, euphoric onset that melts into deep relaxation."],
  ["Is Bubblegum Kush indica, sativa, or hybrid?", "Hybrid. Expect a layered experience that starts giggly and euphoric before gradually melting into deep relaxation and sleepiness."],
  ["What does Bubblegum Kush taste like?", "Sweet, fruity bubblegum up front, with berry and pine notes layered in, and citrus and earthy undertones on the finish."],
  ["What effects does Bubblegum Kush produce?", "Consumers report feeling relaxed, giggly, happy, euphoric, sleepy, and uplifted. The high starts social and creative before settling into deep relaxation."],
  ["What is an AIO disposable?", "AIO stands for All-In-One. It is a rechargeable, self-contained vape device with the cartridge and battery built into a single unit."],
  ["What's the difference between the AIO and the preroll?", "The AIO delivers smooth, terpene-rich vapor with portable convenience. The preroll delivers the full-flavor, full-spectrum experience of smoking Bubblegum Kush flower."],
  ["How much does the Bubblegum Kush AIO Dual Pack cost?", "The LUIGI Bubblegum Kush AIO Dual Pack retails for $30.00 and includes a 1G disposable plus a 0.5G live resin-infused preroll."],
  ["How strong is the AIO disposable?", "The AIO contains 1G of live resin and liquid diamonds. Exact THC percentage varies by batch, so check the package or dispensary listing for current test results."],
  ["How should I store my AIO and preroll?", "Keep the AIO cool, dark, and dry away from direct sunlight and heat. Store the preroll in an airtight container to preserve terpene flavor and potency."],
  ["Can I buy LUIGI AIO Dual Packs for delivery in Los Angeles?", "LUIGI products are available through licensed California dispensaries. Check your local retailer or delivery service for availability."],
  ["What's the difference between live resin and distillate?", "Live resin preserves natural terpenes for a flavorful, aromatic vape. Distillate removes most of those terpenes, resulting in a flatter flavor and more one-dimensional effect."],
]
const productSchema = { "@context": "https://schema.org", "@type": "Product", name: "Bubblegum Kush AIO Dual Pack", brand: { "@type": "Brand", name: "LUIGI" }, description: "Bubblegum Kush live resin liquid diamond disposable (1G) + 0.5G live resin-infused preroll. Hybrid with sweet, fruity bubblegum flavor and giggly, euphoric, relaxing effects. $30.00.", sku: "LUIGI-BK-AIO-DUAL", category: "Cannabis > Vape > Disposables & Dual Packs", image: Object.values(images), offers: { "@type": "Offer", priceCurrency: "USD", price: "30.00", availability: "https://schema.org/InStock", url: productUrl }, aggregateRating: { "@type": "AggregateRating", ratingValue: "4.9", reviewCount: "0" }, keywords: keywords.join(", ") }
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }

export const metadata: Metadata = { title: "Bubblegum Kush AIO Dual Pack | LUIGI Live Resin + Preroll — $30", description: "Bubblegum Kush live resin liquid diamond disposable + 0.5g infused preroll. 1G AIO + 0.5G preroll. Just $30. Shop LUIGI in California.", keywords, alternates: { canonical: productUrl }, openGraph: { title: "Bubblegum Kush AIO Dual Pack | LUIGI Cannabis — $30", description: "Bubblegum Kush live resin liquid diamond disposable + 0.5G infused preroll. 1G AIO + 0.5G preroll. Just $30.", url: productUrl, siteName: "LUIGI", type: "website" } }

function ProductImage({ src, alt }: { src: string; alt: string }) { return <div className="relative aspect-square overflow-hidden rounded-xl bg-gray-100"><Image src={src} alt={alt} fill className="object-contain p-6" sizes="(max-width: 768px) 100vw, 33vw" /></div> }


export default function BubblegumKushAioPage() {
  return <><Script id="bubblegum-product-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }} /><Script id="bubblegum-faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><AgeVerification /><Header /><main className="bg-white pt-16 lg:pt-20">
    <section className="mx-auto max-w-7xl px-6 py-12 lg:px-8"><nav aria-label="Breadcrumb" className="mb-8 text-sm text-gray-500"><Link href="/products">Products</Link><span aria-hidden="true"> / </span><Link href="/products/lrld-aio">LRLD AIO</Link><span aria-hidden="true"> / </span><span className="text-gray-950">Bubblegum Kush</span></nav><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><ProductImage src={images.hero} alt="LUIGI Bubblegum Kush AIO Dual Pack — live resin disposable + preroll" /><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#9a7b16]">LRLD AIO Dual Pack</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-gray-950 lg:text-6xl">Bubblegum Kush AIO Dual Pack — Live Resin Liquid Diamond Disposable + Infused Preroll</h1><p className="mt-5 text-2xl font-semibold text-gray-950">Sweeten the experience.</p><p className="mt-5 text-lg leading-8 text-gray-600">A 1G live resin liquid diamond disposable plus a 0.5G live resin-infused pre-roll of the same strain. Double the flavor, one deliciously balanced experience. Bubblegum Kush blends nostalgic candy sweetness with rich, earthy Kush notes.</p><p className="mt-5 font-medium text-gray-700">Hybrid | 1G AIO Disposable + 0.5G Preroll | Live Resin + Liquid Diamonds</p><p className="mt-6 text-3xl font-bold text-gray-950">$30.00</p><AddToCartButton product={{ id: "bubblegum-kush-aio-dual-pack", name: "Bubblegum Kush AIO Dual Pack", fullName: "Bubblegum Kush AIO Dual Pack", image: images.hero }} price="30" priceNumber={30} className="mt-6" /></div></div><section aria-label="Bubblegum Kush product gallery" className="mt-10"><div className="grid gap-6 sm:grid-cols-3"><ProductImage src={images.box} alt="Bubblegum Kush 1G live resin liquid diamond disposable and 0.5g infused preroll" /><ProductImage src={images.device} alt="Close-up of LUIGI Bubblegum Kush live resin liquid diamond AIO disposable" /><ProductImage src={images.joint} alt="LUIGI Bubblegum Kush 0.5g live resin infused preroll" /></div></section></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Two Ways to Experience Bubblegum Kush — One Pack</h2><p className="mt-5 leading-8 text-gray-700">This isn't just a vape or just a preroll. It's a paired experience. Each LUIGI V11 AIO Dual Pack pairs a 1G live resin liquid diamond disposable with a 0.5G live resin-infused preroll of the same strain — Bubblegum Kush.</p><p className="mt-5 leading-8 text-gray-700">The AIO delivers smooth, potent, terpene-rich vapor with the convenience of a rechargeable all-in-one device. The preroll delivers the full-flavor, full-spectrum experience of smoking Bubblegum Kush flower. Together, they give you two different ways to experience the same flavorful hybrid — the AIO for convenience, the preroll for the full-flavor flower experience.</p><p className="mt-5 leading-8 text-gray-700">At $30.00, you're getting a 1G AIO and a 0.5G preroll in one package — premium inputs and in-house production, without the inflated markup most dual-format packs carry.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">What's Inside the Bubblegum Kush AIO Dual Pack</h2><div className="mt-6 overflow-x-auto"><table className="w-full border-collapse text-left"><tbody>{[["AIO Disposable","1× 1G live resin liquid diamond disposable"],["Preroll","1× 0.5G live resin-infused preroll"],["Total Formats","2 (vape + preroll)"],["Strain","Bubblegum Kush"],["Type","Hybrid"],["Genetics","Bubble Gum (The Bulldog Seeds, Amsterdam)"],["Effects","Relaxed, Giggly, Happy, Euphoric, Sleepy, Uplifted"],["Flavor Profile","Sweet, berry, pine, citrus, earthy"],["Price","$30.00"]].map(([label,value])=><tr key={label} className="border-b border-gray-200"><th className="px-4 py-4 font-semibold text-gray-950">{label}</th><td className="px-4 py-4 text-gray-700">{value}</td></tr>)}</tbody></table></div></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Bubblegum Kush — A Sweet, Fruity Hybrid from The Bulldog Seeds</h2><p className="mt-5 leading-8 text-gray-700">Bubblegum Kush is a hybrid that lives up to its name. Bred from Bubble Gum genetics by The Bulldog Seeds in Amsterdam, it delivers sweet, fruity bubblegum flavor with a sour citrus twist and earthy pine undertones.</p><p className="mt-5 leading-8 text-gray-700">The effects are as layered as the flavor. Consumers report a giggly, euphoric onset that gradually melts into deep relaxation and sleepiness — making it versatile for social sessions, creative afternoons, or unwinding at the end of the night.</p><p className="mt-5 leading-8 text-gray-700"><strong>Note:</strong> The experience may not reflect the strain in this category due to the format of the AIO disposable. The preroll delivers the closest expression of Bubblegum Kush's classic flower profile.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Bubblegum Kush Effects: Relaxed, Giggly, Happy, Euphoric, Sleepy, Uplifted</h2><p className="mt-5 leading-8 text-gray-700">Bubblegum Kush delivers a full-spectrum hybrid experience that shifts throughout the session. The high typically starts with a giggly, euphoric onset — light, social, and mood-lifting. As the experience settles in, deep relaxation and sleepiness gradually take over.</p><p className="mt-5 leading-8 text-gray-700">Early in the session, Bubblegum Kush feels social and creative. Later, it leans sedative and calming. That range makes it a great option whenever you want to feel elevated while keeping the option to sink into relaxation.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Sweet, Berry, Pine, Citrus — A Flavor Experience Worth Savoring</h2><p className="mt-5 leading-8 text-gray-700">Bubblegum Kush delivers sweet, fruity bubblegum up front. As the smoke or vapor develops, berry and pine come forward, adding depth and warmth. Citrus and earthy undertones round out the profile with a balanced, sophisticated close.</p><p className="mt-5 leading-8 text-gray-700">Whether you're drawing from the AIO or lighting the preroll, Bubblegum Kush delivers a full-flavor, terpene-rich experience that rewards slow, intentional draws.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Why We Use Live Resin and Liquid Diamonds</h2><p className="mt-5 leading-8 text-gray-700">Most disposable vapes use distillate — a refined THC extract that's potent but stripped of natural terpenes and minor cannabinoids. The result can feel flat and one-dimensional.</p><p className="mt-5 leading-8 text-gray-700">LUIGI AIO Dual Packs use live resin and liquid diamonds instead. Live resin preserves natural terpenes for a flavorful, aromatic vape. Liquid diamonds add a potent, crystalline THC punch. Together, they create a vape that's both smooth and strong.</p><p className="mt-5 leading-8 text-gray-700">Because the pack also includes a live resin-infused preroll, you get two full-spectrum experiences instead of one.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">How to Enjoy the Bubblegum Kush AIO Dual Pack</h2><p className="mt-5 leading-8 text-gray-700"><strong>The AIO Disposable:</strong> Draw slowly and evenly for a smooth, terpene-rich hit. The rechargeable device delivers consistent vapor from the first draw to the last.</p><p className="mt-5 leading-8 text-gray-700"><strong>The Preroll:</strong> Save it for a slower, more intentional session. The live resin-infused preroll delivers the full-flavor, full-spectrum experience of smoking Bubblegum Kush flower.</p><p className="mt-5 leading-8 text-gray-700"><strong>The Pairing:</strong> Use the AIO for a quick lift and follow up with the preroll for a deeper, more layered session.</p><p className="mt-5 leading-8 text-gray-700"><strong>Storage:</strong> Keep the AIO cool, dark, and dry away from direct sunlight and heat. Store the preroll in an airtight container.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">How the Bubblegum Kush AIO Dual Pack Compares to Distillate Vapes</h2><p className="mt-5 leading-8 text-gray-700">Distillate is potent but often stripped of the plant's natural terpenes and minor cannabinoids. Flavor is typically added back artificially, and the effect can feel flat.</p><p className="mt-5 leading-8 text-gray-700">The LUIGI Bubblegum Kush AIO Dual Pack uses live resin and liquid diamonds. The sweet bubblegum, berry, and pine flavor comes from the same place the effect does — not from a flavor additive.</p><p className="mt-5 leading-8 text-gray-700">Add a 0.5G live resin-infused preroll to the pack, and you're getting two full-spectrum experiences for $30.00.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Premium Live Resin AIO + Preroll at a $30 Price Point</h2><p className="mt-5 leading-8 text-gray-700">Most live resin disposable vapes in California retail between $35 and $50 for 1G. The LUIGI Bubblegum Kush AIO Dual Pack delivers both a 1G live resin liquid diamond disposable and a 0.5G live resin-infused preroll for just $30.00.</p><p className="mt-5 leading-8 text-gray-700">Everything we do starts in-house: formulation, production, packaging, and distribution. No middlemen. No inflated wholesale markups. Just premium cannabis products priced fairly.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Why LUIGI?</h2><p className="mt-5 leading-8 text-gray-700">Born in Los Angeles and built from the ground up, LUIGI is a cannabis brand for people who appreciate quality without the pretense. Everything starts in-house, giving us complete control over every product that carries our name.</p><p className="mt-5 leading-8 text-gray-700">We combine premium inputs, innovative hardware, and unique product formats to create experiences with flavor, potency, consistency, and value in every package.</p><p className="mt-5 leading-8 text-gray-700">We're inspired by art, culture, hospitality, and the communities that support us. LUIGI is a movement built around bringing people together and making every session more memorable.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8" itemScope itemType="https://schema.org/FAQPage"><h2 className="text-3xl font-bold text-gray-950">Frequently Asked Questions</h2><div className="mt-6 divide-y divide-gray-200">{faq.map(([question, answer])=><details key={question} className="py-5" itemScope itemProp="mainEntity" itemType="https://schema.org/Question"><summary className="cursor-pointer font-semibold text-gray-950" itemProp="name">{question}</summary><div itemScope itemProp="acceptedAnswer" itemType="https://schema.org/Answer"><p className="mt-3 leading-7 text-gray-700" itemProp="text">{answer}</p></div></details>)}</div></section>
    <section className="mx-auto max-w-4xl px-6 py-12 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Ready to Experience the Bubblegum Kush AIO Dual Pack?</h2><p className="mt-5 leading-8 text-gray-700">A 1G live resin liquid diamond disposable. A 0.5G live resin-infused preroll. Two ways to experience a flavorful, layered hybrid. Just $30.00. Find LUIGI at a licensed California dispensary near you.</p><AddToCartButton product={{ id: "bubblegum-kush-aio-dual-pack", name: "Bubblegum Kush AIO Dual Pack", fullName: "Bubblegum Kush AIO Dual Pack", image: images.hero }} price="30" priceNumber={30} className="mt-6" /></section>
  </main><Footer /></>
}
