import Image from "next/image"
import Link from "next/link"
import type { Metadata } from "next"
import Script from "next/script"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { AgeVerification } from "@/components/age-verification"
import { AddToCartButton } from "@/components/add-to-cart-button"

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.luigiofficialbrand.com"
const productUrl = `${siteUrl}/products/bullet-trainwreck-aio-dual-pack`
const images = {
  hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790014410-tokyo_family-echqNcZhLenruPxCk3vPoCRQYx3GXt.avif",
  box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tokyo_box%20%281%29-nXoO5Beb1hUe6F7tEdf5vhi2NzCds0.avif",
  device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tokyo_device%20%281%29-L50FwlEqQpTriemHBbcJpruPu6Yedw.avif",
  joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tokyo_joint%20%281%29-1LChdJFtFYNYoiKI42Hu5avCNC8zH4.avif",
}
const keywords = ["bullet trainwreck aio", "bullet trainwreck dual pack", "bullet trainwreck disposable", "bullet trainwreck vape", "bullet trainwreck preroll", "bullet trainwreck strain", "bullet train wreck strain", "bullet trainwreck sativa", "trainwreck strain", "sativa vape California", "sativa disposable", "sativa AIO", "bright sativa strains", "pungent weed strains", "live resin disposable", "liquid diamond disposable", "live resin vape California", "liquid diamond vape", "aio disposable vape", "all in one vape", "disposable + preroll combo", "vape and preroll pack", "dual pack cannabis", "aio vape + preroll pack", "LUIGI cannabis vapes", "LUIGI AIO", "$30 AIO pack", "premium live resin vape", "California live resin vape", "cannabis vape delivery Los Angeles", "1G disposable vape", "0.5g infused preroll"]
const faq = [
  ["What's included in the Bullet Trainwreck AIO Dual Pack?", "The pack includes a 1G live resin liquid diamond disposable (AIO) plus a 0.5G live resin-infused preroll of the same strain, Bullet Trainwreck. Two formats, one bold sativa experience."],
  ["What strain is in the Bullet Trainwreck AIO Dual Pack?", "Bullet Trainwreck, a bold sativa strain known for its bright, pungent terpene character and smooth, well-rounded finish. Also commonly searched as \"Bullet Train Wreck.\" It's built for a fast-moving, energetic flavor ride."],
  ["Is Bullet Trainwreck indica, sativa, or hybrid?", "Sativa. Expect a bright, energetic head-lift that keeps you engaged, focused, and motivated, ideal for daytime sessions, creative work, or social afternoons."],
  ["What does Bullet Trainwreck taste like?", "Bright, pungent, and terpene-forward up front, with smooth, well-rounded notes on the finish. Bold, energetic, and unmistakably sativa."],
  ["What effects does Bullet Trainwreck produce?", "Bullet Trainwreck delivers bright, energetic sativa effects, a smooth, easygoing head-lift that's social, focused, and motivating rather than racy or anxious. Great for daytime, creative work, or social afternoons."],
  ["What is an AIO disposable?", "AIO stands for All-In-One. It's a rechargeable, self-contained vape device with the cartridge and battery built into a single unit. No setup, no refilling, just draw and enjoy."],
  ["What's the difference between the AIO and the preroll in this pack?", "The AIO delivers smooth, terpene-rich vapor with the convenience of a portable device. The preroll delivers the full-flavor, full-spectrum experience of smoking Bullet Trainwreck flower. Together, they give you two ways to experience the same strain."],
  ["How much does the Bullet Trainwreck AIO Dual Pack cost?", "The LUIGI Bullet Trainwreck AIO Dual Pack retails for $30.00 and includes a 1G live resin liquid diamond disposable plus a 0.5G live resin-infused preroll."],
  ["How strong is the AIO disposable?", "The AIO contains 1G of live resin and liquid diamonds. The exact THC percentage varies by batch, so check the packaging or your dispensary listing for the current test results."],
  ["How should I store my AIO and preroll?", "Keep the AIO in a cool, dark, dry place away from direct sunlight and heat. Store the preroll in an airtight container. Proper storage helps preserve both terpene flavor and potency."],
  ["Can I buy LUIGI AIO Dual Packs for delivery in Los Angeles?", "LUIGI products are available through licensed California dispensaries. Check your local retailer or delivery service for availability."],
  ["What's the difference between live resin and distillate?", "Live resin preserves the plant's natural terpenes for a flavorful, aromatic vape. Distillate strips most of those terpenes out, resulting in a flatter flavor and more one-dimensional effect. LUIGI uses live resin and liquid diamonds for a fuller, more layered experience."],
]
const productSchema = { "@context": "https://schema.org", "@type": "Product", name: "Bullet Trainwreck AIO Dual Pack", brand: { "@type": "Brand", name: "LUIGI" }, description: "Bullet Trainwreck live resin liquid diamond disposable (1G) + 0.5G live resin-infused preroll. Bold sativa with bright, pungent terpenes and a smooth finish. $30.00.", sku: "LUIGI-BT-AIO-DUAL", category: "Cannabis > Vape > Disposables & Dual Packs", image: Object.values(images), offers: { "@type": "Offer", priceCurrency: "USD", price: "30.00", availability: "https://schema.org/InStock", url: productUrl }, aggregateRating: { "@type": "AggregateRating", ratingValue: "4.9", reviewCount: "0" }, keywords: keywords.join(", ") }
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }

export const metadata: Metadata = { title: "Bullet Trainwreck AIO Dual Pack | LUIGI Live Resin + Preroll for $30", description: "Bullet Trainwreck live resin liquid diamond disposable + 0.5g infused preroll. 1G AIO + 0.5G preroll. Just $30. Shop LUIGI in California.", keywords, alternates: { canonical: productUrl }, openGraph: { title: "Bullet Trainwreck AIO Dual Pack | LUIGI Cannabis for $30", description: "Bullet Trainwreck live resin liquid diamond disposable + 0.5G infused preroll. 1G AIO + 0.5G preroll. Just $30.", url: productUrl, siteName: "LUIGI", type: "website" } }

function ProductImage({ src, alt }: { src: string; alt: string }) { return <div className="relative aspect-square overflow-hidden rounded-xl bg-gray-100"><Image src={src} alt={alt} fill className="object-contain p-6" sizes="(max-width: 768px) 100vw, 33vw" /></div> }

export default function BulletTrainwreckAioPage() {
  return <><Script id="bullet-trainwreck-product-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }} /><Script id="bullet-trainwreck-faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><AgeVerification /><Header /><main className="bg-white pt-16 lg:pt-20">
    <section className="mx-auto max-w-7xl px-6 py-12 lg:px-8"><nav aria-label="Breadcrumb" className="mb-8 text-sm text-gray-500"><Link href="/products">Products</Link><span aria-hidden="true"> / </span><Link href="/products/lrld-aio">LRLD AIO</Link><span aria-hidden="true"> / </span><span className="text-gray-950">Bullet Trainwreck</span></nav><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><ProductImage src={images.hero} alt="LUIGI Bullet Trainwreck AIO Dual Pack: live resin disposable and preroll" /><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#9a7b16]">LRLD AIO Dual Pack</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-gray-950 lg:text-6xl">Bullet Trainwreck AIO Dual Pack: Live Resin Liquid Diamond Disposable + Infused Preroll</h1><p className="mt-5 text-2xl font-semibold text-gray-950">All aboard.</p><p className="mt-5 text-lg leading-8 text-gray-600">A 1G live resin liquid diamond disposable plus a 0.5G live resin-infused pre-roll of the same strain. Two ways to experience the full Bullet Trainwreck profile. A bold sativa built for a fast-moving flavor ride, bright, pungent terpenes with a smooth finish.</p><p className="mt-5 font-medium text-gray-700">Sativa | 1G AIO Disposable + 0.5G Preroll | Live Resin + Liquid Diamonds</p><p className="mt-6 text-3xl font-bold text-gray-950">$30.00</p><AddToCartButton product={{ id: "bullet-trainwreck-aio-dual-pack", name: "Bullet Trainwreck AIO Dual Pack", fullName: "Bullet Trainwreck AIO Dual Pack", image: images.hero }} price="30" priceNumber={30} className="mt-6" /></div></div><section aria-label="Bullet Trainwreck product gallery" className="mt-10"><div className="grid gap-6 sm:grid-cols-3"><ProductImage src={images.box} alt="Bullet Trainwreck 1G live resin liquid diamond disposable and 0.5g infused preroll" /><ProductImage src={images.device} alt="Close-up of LUIGI Bullet Trainwreck live resin liquid diamond AIO disposable" /><ProductImage src={images.joint} alt="LUIGI Bullet Trainwreck 0.5g live resin infused preroll" /></div></section></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Two Ways to Experience Bullet Trainwreck, One Pack</h2><p className="mt-5 leading-8 text-gray-700">This isn't just a vape or just a preroll. It's a paired experience. Each LUIGI V11 AIO Dual Pack pairs a 1G live resin liquid diamond disposable with a 0.5G live resin-infused preroll of the same strain, Bullet Trainwreck.</p><p className="mt-5 leading-8 text-gray-700">The AIO delivers smooth, potent, terpene-rich vapor with the convenience of a rechargeable all-in-one device. The preroll delivers the full-flavor, full-spectrum experience of smoking Bullet Trainwreck flower. Together, they give you two ways to experience the same bold sativa: the AIO for convenience, the preroll for the full-flavor flower experience.</p><p className="mt-5 leading-8 text-gray-700">At $30.00, you're getting a 1G AIO and a 0.5G preroll in one package, premium inputs and in-house production, without the inflated markup most dual-format packs carry.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">What's Inside the Bullet Trainwreck AIO Dual Pack</h2><div className="mt-6 overflow-x-auto"><table className="w-full border-collapse text-left"><tbody>{[["AIO Disposable","1× 1G live resin liquid diamond disposable"],["Preroll","1× 0.5G live resin-infused preroll"],["Total Formats","2 (vape + preroll)"],["Strain","Bullet Trainwreck"],["Type","Sativa"],["Flavor Profile","Bright, pungent, terpene-forward"],["Price","$30.00"]].map(([label,value])=><tr key={label} className="border-b border-gray-200"><th className="px-4 py-4 font-semibold text-gray-950">{label}</th><td className="px-4 py-4 text-gray-700">{value}</td></tr>)}</tbody></table></div></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Bullet Trainwreck: A Bold Sativa Built for a Fast Ride</h2><p className="mt-5 leading-8 text-gray-700">Bullet Trainwreck is a sativa built for people who want their smoke to feel like a fast-moving ride. The flavor opens bright and pungent, bold terpene character up front, energetic and unmistakable. As the profile develops, smooth, well-rounded notes come forward, adding depth without slowing down the momentum.</p><p className="mt-5 leading-8 text-gray-700">It's a sativa that earns its name: energetic, engaging, and full of personality from the first draw to the last. Whether you're drawing from the AIO or lighting the preroll, Bullet Trainwreck delivers the kind of bright, terpene-forward experience that makes sativas worth seeking out.</p><p className="mt-5 leading-8 text-gray-700"><strong>A quick note on format:</strong> vaping shifts how a strain's classic character comes through, so the AIO won't taste exactly like smoking flower. The preroll delivers the closest expression of Bullet Trainwreck's classic flower profile.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Bullet Trainwreck Effects: Energetic, Focused, Uplifting</h2><p className="mt-5 leading-8 text-gray-700">As a sativa, Bullet Trainwreck delivers the kind of effects sativa fans look for: a bright, energetic head-lift that keeps you engaged, focused, and motivated. It's not a racy or anxious sativa, the high is smooth and manageable, ideal for daytime sessions, creative work, or social afternoons.</p><p className="mt-5 leading-8 text-gray-700">The fast-moving flavor profile keeps the experience feeling lively even as the effects settle in. It's the kind of sativa that works equally well for solo creative sessions, group hangs, or a productive afternoon pick-me-up.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Bright, Pungent, Terpene-Forward: A Flavor Experience Worth Savoring</h2><p className="mt-5 leading-8 text-gray-700">Bullet Trainwreck delivers a flavor profile that's as bold as its name suggests. The first notes are bright and pungent, energetic, terpene-forward, and unmistakable. As the smoke or vapor develops, smooth, well-rounded notes come forward, adding depth and warmth. The finish is clean and flavorful, keeping the experience lively from start to finish.</p><p className="mt-5 leading-8 text-gray-700">Whether you're drawing from the AIO or lighting the preroll, Bullet Trainwreck delivers a full-flavor, terpene-rich experience that rewards slow, intentional draws.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Why We Use Live Resin and Liquid Diamonds</h2><p className="mt-5 leading-8 text-gray-700">Most disposable vapes on the market use distillate, a refined THC extract that's potent but stripped of the plant's natural terpenes and minor cannabinoids. The result is a vape that gets you high, but the flavor feels flat and the effect feels one-dimensional.</p><p className="mt-5 leading-8 text-gray-700">LUIGI AIO Dual Packs use live resin and liquid diamonds instead. Live resin preserves the plant's natural terpenes for a flavorful, aromatic vape. Liquid diamonds add a potent, crystalline THC punch. Together, they create a vape that's both smooth and strong, the kind of experience that reminds you why live resin is worth seeking out.</p><p className="mt-5 leading-8 text-gray-700">And because the pack also includes a live resin-infused preroll, you get two full-spectrum experiences instead of one.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">How to Enjoy the Bullet Trainwreck AIO Dual Pack</h2><p className="mt-5 leading-8 text-gray-700"><strong>The AIO Disposable:</strong> Draw slowly and evenly for a smooth, terpene-rich hit. The rechargeable device delivers consistent vapor from the first draw to the last. Ideal for on-the-go sessions, quick hits, or anytime you want full-flavor without the setup.</p><p className="mt-5 leading-8 text-gray-700"><strong>The Preroll:</strong> Save it for a slower, more intentional session. The live resin-infused preroll delivers the full-flavor, full-spectrum experience of smoking Bullet Trainwreck flower, the way the strain was meant to be enjoyed.</p><p className="mt-5 leading-8 text-gray-700"><strong>The Pairing:</strong> For the full LUIGI experience, use the AIO for a quick lift and follow up with the preroll for a deeper, more layered session. The combination gives you both formats of the same strain, the best of both worlds.</p><p className="mt-5 leading-8 text-gray-700"><strong>Storage:</strong> Keep the AIO in a cool, dark, dry place away from direct sunlight and heat. Store the preroll in an airtight container. Proper storage helps preserve both terpene flavor and potency.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">How the Bullet Trainwreck AIO Dual Pack Compares to Distillate Vapes</h2><p className="mt-5 leading-8 text-gray-700">Most disposable vapes on the market use distillate, a refined THC extract that's potent but stripped of most of the plant's natural terpenes and minor cannabinoids. The flavor is typically added back in artificially, and the effect tends to feel flat.</p><p className="mt-5 leading-8 text-gray-700">The LUIGI Bullet Trainwreck AIO Dual Pack uses live resin and liquid diamonds instead. Live resin is full-spectrum and retains the plant's terpenes, flavonoids, and minor cannabinoids. Liquid diamonds add a potent, crystalline THC punch. That means the bright, pungent flavor of Bullet Trainwreck is coming from the same place the effect is, not from a flavor additive.</p><p className="mt-5 leading-8 text-gray-700">Add a 0.5G live resin-infused preroll to the pack, and you're getting two full-spectrum experiences for $30.00, a price point that most distillate disposables barely compete with, let alone dual-format packs.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Premium Live Resin AIO + Preroll at a $30 Price Point</h2><p className="mt-5 leading-8 text-gray-700">Most live resin disposable vapes in California retail between $35 and $50 for a 1G format. Adding a preroll on top typically pushes the total well past $40. The LUIGI Bullet Trainwreck AIO Dual Pack delivers both, a 1G live resin liquid diamond disposable and a 0.5G live resin-infused preroll, for just $30.00.</p><p className="mt-5 leading-8 text-gray-700">How? Because everything we do starts in-house. Formulation, production, packaging, and distribution all happen under one roof. No middlemen. No inflated wholesale markups. Just premium cannabis products priced fairly for the people who actually smoke them.</p><p className="mt-5 leading-8 text-gray-700">If you've been searching for a premium live resin vape and preroll combo without overpaying, this is the pack.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Why LUIGI?</h2><p className="mt-5 leading-8 text-gray-700">Born in Los Angeles and built from the ground up, LUIGI is a cannabis brand for people who appreciate quality without the pretense. Everything we do starts in-house, formulation, production, packaging, distribution, giving us complete control over every product that carries our name.</p><p className="mt-5 leading-8 text-gray-700">We combine premium inputs, innovative hardware, and unique product formats to create experiences that stand out in a crowded market. Whether it's our signature Dual Packs, rosin-infused products, Fattone collections, or limited-edition drops, LUIGI is committed to delivering flavor, potency, consistency, and value in every package.</p><p className="mt-5 leading-8 text-gray-700">We're inspired by art, culture, hospitality, and the communities that support us. That's why LUIGI isn't just a cannabis brand, it's a movement built around bringing people together and making every session a little more memorable. When you choose LUIGI, you're not just buying a live resin vape in California. You're joining something.</p></section>
    <section className="mx-auto max-w-4xl px-6 py-10 lg:px-8" itemScope itemType="https://schema.org/FAQPage"><h2 className="text-3xl font-bold text-gray-950">Frequently Asked Questions</h2><div className="mt-6 divide-y divide-gray-200">{faq.map(([question, answer])=><details key={question} className="py-5" itemScope itemProp="mainEntity" itemType="https://schema.org/Question"><summary className="cursor-pointer font-semibold text-gray-950" itemProp="name">{question}</summary><div itemScope itemProp="acceptedAnswer" itemType="https://schema.org/Answer"><p className="mt-3 leading-7 text-gray-700" itemProp="text">{answer}</p></div></details>)}</div></section>
    <section className="mx-auto max-w-4xl px-6 py-12 lg:px-8"><h2 className="text-3xl font-bold text-gray-950">Ready to Experience the Bullet Trainwreck AIO Dual Pack?</h2><p className="mt-5 leading-8 text-gray-700">A 1G live resin liquid diamond disposable. A 0.5G live resin-infused preroll. Two ways to experience a bold, fast-moving sativa. Just $30.00. Find LUIGI at a licensed California dispensary near you.</p><AddToCartButton product={{ id: "bullet-trainwreck-aio-dual-pack", name: "Bullet Trainwreck AIO Dual Pack", fullName: "Bullet Trainwreck AIO Dual Pack", image: images.hero }} price="30" priceNumber={30} className="mt-6" /></section>
  </main><Footer /></>
}
