import type { Metadata } from "next"
import Script from "next/script"
import Link from "next/link"
import Image from "next/image"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { AgeVerification } from "@/components/age-verification"
import { AddToCartButton } from "@/components/add-to-cart-button"

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.luigiofficialbrand.com"
const productUrl = `${siteUrl}/products/berry-amarillo-blunt-2pk`
const images = {
  hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790269924-berry_amarillo_family-XHqPtoIFbssAsb3BvPhh4Fqg7U71uz.avif",
  pack: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/berry-amarillo_tube-vbgnMLUliVjKWqyj0UHh9QcpNNTFUn.avif",
  close: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/berry-amarillo_blunt-KvbxJzq9VUfi2eZhdmaweZVzr2WYVP.avif",
}
const product = { id: "berry-amarillo-blunt-2pk", name: "Berry Amarillo Blunt 2-Pack", fullName: "Berry Amarillo Blunt 2-Pack", image: images.hero }
const details = [["Blunts", "2× 1.25g rosin-infused blunts"], ["Total Weight", "2.5g total"], ["Strain", "Berry Amarillo"], ["Type", "Indica"], ["Flavor Profile", "Ripe berry, zesty citrus, bright lively terps"], ["Price", "$30.00"]]
const faq = [
  ["What's included in the Berry Amarillo Blunt 2-Pack?", "The pack includes two 1.25g rosin-infused blunts, 2.5g total. Both blunts are packed with Berry Amarillo indica flower infused with premium rosin."],
  ["What strain is in the Berry Amarillo Blunt 2-Pack?", "Berry Amarillo, an indica strain known for ripe berry flavor, zesty citrus notes, and bright, lively terpenes."],
  ["Is Berry Amarillo indica, sativa, or hybrid?", "Indica. Expect a relaxing, body-forward experience with a slow, unwinding finish."],
  ["What does Berry Amarillo taste like?", "Ripe, juicy berry and zesty citrus with bright, lively terps. Sweet, vibrant, and full of flavor."],
  ["What effects does Berry Amarillo produce?", "A relaxing, body-forward calm that settles in gently and lingers. It is substantial but manageable, rather than a couch-lock experience."],
  ["How much does the Berry Amarillo Blunt 2-Pack cost?", "The LUIGI Berry Amarillo Blunt 2-Pack retails for $30.00 and includes two 1.25g rosin-infused indica blunts."],
  ["How strong are LUIGI rosin-infused blunts?", "Each blunt contains 1.25g of Berry Amarillo flower infused with premium rosin. Exact THC varies by batch, so check the package or dispensary listing."],
  ["How should I store my blunts?", "Store them in a cool, dark, dry place, ideally in an airtight container away from direct sunlight and heat."],
  ["Can I buy LUIGI blunts for delivery in Los Angeles?", "LUIGI products are available through licensed California dispensaries. Check your local retailer or delivery service."],
  ["What's the difference between a rosin-infused blunt and a regular blunt?", "A regular blunt is flower. A rosin-infused blunt adds premium solventless rosin, boosting potency and flavor complexity for a richer, more layered smoke."],
]
export const metadata: Metadata = {
  title: "Berry Amarillo Rosin Blunt 2-Pack | LUIGI Indica, $30",
  description: "Two 1.25g rosin-infused Berry Amarillo indica blunts. 2.5g total. Ripe berry, zesty citrus, bright terps. Just $30. Shop LUIGI in California.",
  keywords: ["berry amarillo blunt", "berry amarillo 2 pack", "berry amarillo strain", "rosin infused blunts", "indica blunts California", "berry blunts California", "citrus blunts California", "premium rosin blunts", "2.5g blunt pack", "infused blunt pack California", "LUIGI cannabis blunts", "LUIGI blunt 2 pack", "best rosin blunts California", "affordable rosin blunts", "$30 blunt pack", "fruity indica blunts", "berry weed strains", "citrus indica blunts", "California rosin blunts", "buy blunts online California", "cannabis blunt delivery Los Angeles", "premium infused blunts", "1.25g blunts"],
  alternates: { canonical: productUrl },
  openGraph: { title: "Berry Amarillo Rosin Blunt 2-Pack | LUIGI Cannabis, $30", description: "Two 1.25g rosin-infused Berry Amarillo indica blunts. 2.5g total. Ripe berry, zesty citrus, bright terps. Just $30.", url: productUrl, siteName: "LUIGI", type: "website", images: [{ url: images.hero, alt: "LUIGI Berry Amarillo Rosin Infused Indica Blunt 2-Pack" }] },
}
const schema = { "@context": "https://schema.org", "@type": "Product", "@id": `${productUrl}#product`, name: product.name, url: productUrl, brand: { "@type": "Brand", name: "LUIGI" }, description: "Two 1.25g rosin-infused Berry Amarillo indica blunts, 2.5g total. Ripe berry, zesty citrus, bright lively terps with relaxing, body-forward effects. $30.00.", sku: "LUIGI-BA-BLUNT-2PK", category: "Cannabis > Pre-Rolls > Infused Blunts", image: Object.values(images), offers: { "@type": "Offer", url: productUrl, priceCurrency: "USD", price: "30.00", priceValidUntil: "2026-12-31", availability: "https://schema.org/InStock", seller: { "@type": "Organization", name: "LUIGI" } }, keywords: "berry amarillo blunt, berry amarillo 2 pack, berry amarillo strain, rosin infused blunts, indica blunts California, berry blunts California, citrus blunts California, premium rosin blunts, 2.5g blunt pack, infused blunt pack California, LUIGI cannabis blunts, LUIGI blunt 2 pack, best rosin blunts California, affordable rosin blunts, $30 blunt pack, fruity indica blunts, berry weed strains, citrus indica blunts, California rosin blunts, buy blunts online California, cannabis blunt delivery Los Angeles, premium infused blunts" }
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }
function SlotImage({ src, alt, comment }: { src: string; alt: string; comment: string }) { return <div className="relative aspect-square overflow-hidden rounded-xl bg-gray-100">{/* {comment} */}<Image src={src} alt={alt} fill className="object-contain p-5" sizes="(max-width: 768px) 100vw, 50vw" /></div> }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border-t border-gray-200 py-12"><h2 className="mb-6 text-3xl font-bold text-gray-950">{title}</h2><div className="max-w-4xl space-y-5 leading-8 text-gray-600">{children}</div></section> }

export default function BerryAmarilloBluntPage() {
  return <><Script id="berry-amarillo-product-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><Script id="berry-amarillo-faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><AgeVerification /><Header /><main className="bg-white pt-16 lg:pt-20"><section className="mx-auto max-w-7xl px-6 py-12 lg:px-8 lg:py-20"><Link href="/products/blunt-2pk" className="text-sm font-semibold text-gray-600 hover:text-black">Back to Blunt 2pk</Link><div className="mt-8 grid gap-12 lg:grid-cols-2 lg:items-center"><SlotImage src={images.hero} alt="LUIGI Berry Amarillo Rosin Infused Indica Blunt 2-Pack" comment="Slot 1, Hero" /><div><p className="text-sm font-semibold uppercase tracking-[0.22em] text-[#9a7b16]">LUIGI Blunt 2pk</p><h1 className="mt-4 text-4xl font-bold tracking-tight text-gray-950 md:text-6xl">Berry Amarillo Blunt 2-Pack, Rosin-Infused Indica Blunts</h1><p className="mt-5 text-xl font-semibold text-gray-700">A juicy little getaway.</p><p className="mt-5 leading-8 text-gray-600">Two 1.25g indica blunts infused with premium rosin, 2.5g total. Waves of ripe berry, zesty citrus, and bright, lively terps. Sweet, vibrant, and bursting with flavor from the first spark to the last.</p><div className="my-7 grid grid-cols-2 gap-3 border-y border-gray-200 py-5 text-sm font-semibold text-gray-700"><span>Indica</span><span>2 × 1.25g Blunts</span><span>2.5g Total</span><span>Rosin Infused</span></div><p className="text-3xl font-bold text-gray-950">$30.00</p><div className="mt-6"><AddToCartButton product={product} price="$30.00" priceNumber={30} units="2 × 1.25g" perUnit="per 2-pack" /></div></div></div><nav aria-label="Product page sections" className="mt-8 flex flex-wrap gap-4 text-sm font-semibold"><a href="#product-details" className="text-gray-600 underline underline-offset-4 hover:text-black">Product details</a><a href="#frequently-asked-questions" className="text-gray-600 underline underline-offset-4 hover:text-black">Frequently asked questions</a></nav></section><div className="mx-auto grid max-w-7xl gap-6 px-6 pb-4 md:grid-cols-2 lg:px-8"><SlotImage src={images.pack} alt="Two 1.25g Berry Amarillo rosin blunts, 2.5g total" comment="Slot 2, Pack Contents" /><SlotImage src={images.close} alt="Close-up of Berry Amarillo rosin-infused blunt with visible oil ring" comment="Slot 3, Blunt Close-Up" /></div><div className="mx-auto max-w-7xl px-6 lg:px-8">
    <Section title="Two Blunts. One Bright, Berry-Forward Strain. Double the Fun."><p>The LUIGI Rosin Infused Double Blunt Pack comes loaded with two 1.25g blunts, packing a total of 2.5g of bold, flavorful goodness. Perfect for sharing, or keeping both for yourself. Game on.</p><p>Berry Amarillo is a juicy little getaway in blunt form. Waves of ripe berry and zesty citrus lead the experience, backed by bright, lively terps that keep the flavor vibrant from the first spark to the last. It's an indica that leans fruity and refreshing rather than heavy and sedating.</p><p>At $30.00, you're getting 2.5g of rosin-infused flower across two full blunts, premium inputs and in-house production, without the inflated markup most rosin blunt packs carry.</p></Section>
    <div id="product-details"><Section title="What's Inside the Berry Amarillo Blunt 2-Pack"><div className="overflow-x-auto"><table className="w-full min-w-[560px] border-collapse text-left text-sm"><tbody>{details.map(([label, value]) => <tr key={label} className="border-b border-gray-200"><th className="py-4 pr-5 font-semibold text-gray-950">{label}</th><td className="py-4">{value}</td></tr>)}</tbody></table></div></Section></div>
    <Section title="Berry Amarillo, A Juicy, Berry-Forward Indica"><p>Berry Amarillo is what happens when an indica leans bright instead of heavy. The strain leads with ripe berry sweetness and a burst of zesty citrus, backed by lively terpenes that keep the flavor vibrant and refreshing.</p><p>Where many indica strains go earthy and dense, Berry Amarillo goes sweet and bright. The result is a smoke that feels like a juicy getaway, light on the palate, rich in flavor, and smooth from start to finish.</p><SlotImage src={images.close} alt="Berry Amarillo strain, frosty indica flower with berry and citrus terpenes" comment="Slot 4, Strain / Flower Detail" /></Section>
    <Section title="Berry Amarillo Effects: Relaxing, Body-Forward, Unwinding"><p>As an indica, Berry Amarillo delivers a slow, unwinding body calm that settles in gently and lingers. It's not a couch-lock strain, making it a good fit for evenings, weekends, or anytime you want to decompress without being fully sidelined.</p><p>The bright, citrus-forward flavor keeps the experience feeling lively even as the effects settle in. It works equally well for solo wind-downs, small gatherings, or pairing with a meal or a movie.</p></Section>
    <Section title="Ripe Berry, Zesty Citrus, A Flavor Experience Worth Savoring"><p>Berry Amarillo delivers ripe, juicy berry notes that are sweet and full-bodied. As the smoke develops, zesty citrus comes forward, adding brightness and lift. Bright, lively terps tie the profile together, keeping the flavor fresh from the first spark to the final exhale.</p><p>It's a flavor journey that rewards slow, intentional draws, the kind of blunt you actually want to sit with and enjoy rather than rush through.</p></Section>
    <Section title="Why We Infuse with Premium Rosin"><p>Most infused blunts use distillate, a refined THC extract that's potent but stripped of natural terpenes and minor cannabinoids. The result can feel flat and one-dimensional.</p><p>LUIGI blunts are infused with premium rosin instead. Rosin is solventless, full-spectrum, and retains the plant's natural terpenes, flavonoids, and minor cannabinoids. That means the berry and citrus flavor of Berry Amarillo comes from the same place the effect does, not from an artificial additive.</p><p>The result is a smoother, richer, more layered smoke.</p></Section>
    <Section title="How to Enjoy the Berry Amarillo Blunt 2-Pack"><p><strong>Sharing:</strong> With two 1.25g blunts in every pack, this is built for sharing. Pass one around with friends and save the second for later, or keep both for yourself. Game on.</p><p><strong>Solo Session:</strong> One blunt is plenty for a full session. Start slow, take your time, and let the strain's bright, berry-forward flavor do its thing.</p><p><strong>Storage:</strong> Keep your blunts in a cool, dark, dry place, ideally in an airtight container away from direct sunlight and heat.</p><SlotImage src={images.hero} alt="Sharing LUIGI Berry Amarillo blunts with friends" comment="Slot 5, Lifestyle / Sharing" /></Section>
    <Section title="How the Berry Amarillo Blunt 2-Pack Compares to Distillate Blunts"><p>Most infused blunts use distillate, and the flavor is often added back artificially. The effect tends to feel flat.</p><p>The LUIGI Berry Amarillo Blunt 2-Pack uses premium rosin. It is solventless, full-spectrum, and retains the plant's terpenes, flavonoids, and minor cannabinoids, so the berry and citrus flavor comes from the flower and rosin together.</p><p>Two 1.25g blunts for $30.00 gives you 2.5g of rosin-infused flower at a price point that is hard to beat.</p></Section>
    <Section title="Premium Rosin Blunts at a $30 Price Point"><p>Most rosin-infused blunt packs in California retail between $40 and $60 for a similar 2.5g format. LUIGI delivers solventless-infused quality and two full 1.25g blunts for $30.00.</p><p>Everything starts in-house, from formulation and production to packaging and distribution. No middlemen and no inflated wholesale markups.</p><p>If you've been searching for quality rosin blunts in California without overpaying, this is the pack.</p></Section>
    <Section title="Why LUIGI?"><p>Born in Los Angeles, LUIGI is a cannabis brand for people who appreciate quality without the pretense. Everything starts in-house, giving us complete control over every product that carries our name.</p><p>We combine premium inputs, innovative hardware, and unique product formats to create experiences that stand out. LUIGI is committed to flavor, potency, consistency, and value in every package.</p><p>We're inspired by art, culture, hospitality, and the communities that support us. LUIGI is more than a cannabis brand, it's a movement built around bringing people together.</p><SlotImage src={images.pack} alt="LUIGI cannabis brand, quality without pretense, Los Angeles" comment="Slot 6, Brand / Lifestyle" /></Section>
    <section id="frequently-asked-questions" className="scroll-mt-24 border-t border-gray-200 py-12" itemScope itemType="https://schema.org/FAQPage"><h2 className="mb-8 text-3xl font-bold text-gray-950">Frequently Asked Questions</h2><div className="max-w-4xl divide-y divide-gray-200 rounded-xl border border-gray-200">{faq.map(([question, answer]) => <details key={question} itemScope itemProp="mainEntity" itemType="https://schema.org/Question" className="group p-5 open:bg-gray-50"><summary itemProp="name" className="flex cursor-pointer list-none items-center justify-between gap-6 text-lg font-semibold text-gray-950"><span>{question}</span><span aria-hidden="true" className="text-2xl font-normal text-gray-500 transition-transform group-open:rotate-45">+</span></summary><div itemScope itemProp="acceptedAnswer" itemType="https://schema.org/Answer"><p itemProp="text" className="mt-4 leading-7 text-gray-600">{answer}</p></div></details>)}</div></section>
    <section className="mb-16 rounded-xl bg-black px-6 py-14 text-center text-white"><SlotImage src={images.hero} alt="Buy LUIGI Berry Amarillo Blunt 2-Pack at a California dispensary for $30" comment="Slot 7, Final CTA" /><h2 className="mt-8 text-3xl font-bold md:text-4xl">Ready to Experience the Berry Amarillo Blunt 2-Pack?</h2><p className="mx-auto mt-5 max-w-2xl leading-8 text-gray-300">Two 1.25g rosin-infused indica blunts. 2.5g total. Ripe berry, zesty citrus, and a juicy little getaway in every spark. Just $30.00. Find LUIGI at a licensed California dispensary near you.</p><Link href="/products/berry-amarillo-blunt-2pk" className="mt-7 inline-flex rounded-full bg-[#D4AF37] px-7 py-3 font-bold text-black">Find a Dispensary, $30</Link></section>
  </div></main><Footer /></>
}

// All canonical, internal, Open Graph, and offer URLs use https://www.luigiofficialbrand.com.
// The supplied image URLs are retained exactly as provided for the requested assets.
