import Image from "next/image"
import Link from "next/link"
import { AddToCartButton } from "@/components/add-to-cart-button"
import { AIO_PRODUCTS, SITE_URL, aioKeywords, productUrl, type AioProduct } from "@/lib/aio-products"

const articles = [
  ["/blog/live-rosin-vs-liquid-diamonds", "Live Rosin vs. Liquid Diamonds"],
  ["/blog/infused-pre-rolls-vs-regular", "Infused Pre-Rolls vs. Regular Pre-Rolls"],
  ["/blog/how-long-do-luigi-disposables-last", "How Long Do LUIGI Disposables Last?"],
] as const

function Card({ href, title, image, alt }: { href: string; title: string; image: string; alt: string }) {
  return <Link href={href} className="group overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="relative aspect-[4/3] bg-gray-100"><Image src={image} alt={alt} fill className="object-contain p-5 transition group-hover:scale-105" sizes="(max-width: 768px) 100vw, 33vw" /></div><div className="p-4"><h3 className="font-semibold text-gray-950">{title}</h3><span className="mt-2 inline-block text-sm text-gray-600">Explore more</span></div></Link>
}

const faqQuestions = ["What's included?", "What strain is this?", "Is it indica, sativa, or hybrid?", "What does it taste like?", "What effects can I expect?", "What is an AIO disposable?", "What is the difference between the AIO and preroll?", "How much does it cost?", "How strong is it?", "How should I store it?", "Is it available in Los Angeles?", "How does live resin compare with distillate?"]

export function AioProductPage({ product }: { product: AioProduct }) {
  const others = AIO_PRODUCTS.filter((item) => item.slug !== product.slug)
  const url = productUrl(product)
  const cart = { id: product.slug, name: `${product.name} AIO Dual Pack`, fullName: `${product.name} AIO Dual Pack`, price: 30, image: product.images.hero }
  const answer = (index: number) => [
    `The pack includes a 1G live resin liquid diamond disposable and a 0.5G live resin-infused preroll of ${product.name}.`,
    `${product.name} is a ${product.type.toLowerCase()} profile built around ${product.genetics.toLowerCase()}.`,
    `${product.name} is a ${product.type.toLowerCase()} product with ${product.effects.toLowerCase()} effects.`,
    `${product.name} tastes ${product.flavor.toLowerCase()}.`,
    `Reported effects include ${product.effects.toLowerCase()}. Start low and go slowly.`,
    `AIO means all-in-one: the rechargeable battery and cartridge are together in one device.`,
    `The AIO is convenient and portable, while the preroll offers a slower, flower-forward session.`,
    `The ${product.name} AIO Dual Pack costs $30.00.`,
    `The pack contains 1G in the AIO and 0.5G in the infused preroll. Check the package for current test results.`,
    `Keep both formats cool, dark, dry, and away from heat and direct light.`,
    `LUIGI products are available through licensed California retailers where stocked.`,
    `Live resin preserves more natural terpene character than typical distillate, while liquid diamonds add potency.`,
  ][index]
  const productSchema = { "@context": "https://schema.org", "@type": "Product", "@id": `${url}#product`, name: `${product.name} AIO Dual Pack`, url, brand: { "@type": "Brand", name: "LUIGI" }, description: `${product.name} live resin liquid diamond disposable plus a 0.5G infused preroll.`, sku: product.sku, category: "Cannabis > Vape > Disposables & Dual Packs", image: Object.values(product.images), keywords: aioKeywords(product).join(", "), offers: { "@type": "Offer", url, priceCurrency: "USD", price: "30.00", availability: "https://schema.org/InStock" } }
  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: SITE_URL }, { "@type": "ListItem", position: 2, name: "Products", item: `${SITE_URL}/products` }, { "@type": "ListItem", position: 3, name: "LRLD AIO", item: `${SITE_URL}/products/lrld-aio` }, { "@type": "ListItem", position: 4, name: `${product.name} AIO Dual Pack`, item: url }] }
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqQuestions.map((name, index) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text: answer(index) } })) }
  return <main className="bg-white text-gray-950"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <nav aria-label="Breadcrumb" className="mx-auto max-w-7xl px-6 py-5 text-sm text-gray-600"><Link href="/">Home</Link><span className="px-2">/</span><Link href="/products">Products</Link><span className="px-2">/</span><Link href="/products/lrld-aio">LRLD AIO</Link><span className="px-2">/</span><span aria-current="page">{product.name}</span></nav>
    <section className="mx-auto grid max-w-7xl gap-10 px-6 py-10 lg:grid-cols-2 lg:items-center"><div><Image src={product.images.hero} alt={`LUIGI ${product.name} AIO Dual Pack`} width={1000} height={1000} priority className="aspect-square w-full rounded-2xl bg-gray-100 object-contain p-8" /></div><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#9a7b16]">LUIGI V11 AIO Dual Pack</p><h1 className="mt-4 text-4xl font-bold tracking-tight md:text-6xl">{product.name} AIO Dual Pack</h1><p className="mt-5 text-xl leading-8 text-gray-700">1G live resin liquid diamond disposable plus a 0.5G live resin-infused preroll. Two premium formats, one strain, and a $30 price point.</p><p className="mt-5 font-semibold">{product.type} · {product.flavor} · $30.00</p><div className="mt-6"><AddToCartButton product={cart} price="$30" priceNumber={30} /></div></div></section>
    <section aria-label={`${product.name} product gallery`} className="mx-auto grid max-w-7xl gap-6 px-6 pb-14 sm:grid-cols-3"><Image src={product.images.box} alt={`${product.name} retail box`} width={800} height={800} className="aspect-square rounded-xl bg-gray-100 object-contain p-6" /><Image src={product.images.device} alt={`${product.name} AIO device`} width={800} height={800} className="aspect-square rounded-xl bg-gray-100 object-contain p-6" /><Image src={product.images.joint} alt={`${product.name} infused preroll`} width={800} height={800} className="aspect-square rounded-xl bg-gray-100 object-contain p-6" /></section>
    <section className="mx-auto max-w-4xl space-y-12 px-6 py-12"><article><h2 className="text-3xl font-bold">Two Ways to Experience {product.name}</h2><p className="mt-4 leading-8 text-gray-700">This is a paired experience built around convenience and full flavor. The AIO delivers smooth, terpene-rich vapor in a rechargeable all-in-one device, while the infused preroll gives you a slower flower-forward session. Together, they make it easy to choose the format that fits the moment.</p><p className="mt-4 leading-8 text-gray-700">At $30.00, the pack brings premium inputs and in-house production together without the inflated markup common to dual-format products.</p></article><article><h2 className="text-3xl font-bold">What&apos;s Inside</h2><table className="mt-4 w-full text-left"><tbody>{[["AIO Disposable", "1× 1G live resin liquid diamond disposable"], ["Preroll", "1× 0.5G live resin-infused preroll"], ["Total Formats", "2 (vape + preroll)"], ["Strain Type", product.type], ["Flavor", product.flavor], ["Price", "$30.00"]].map(([label, value]) => <tr key={label} className="border-b border-gray-200"><th className="py-3 pr-4 font-semibold">{label}</th><td className="py-3">{value}</td></tr>)}</tbody></table></article><article><h2 className="text-3xl font-bold">{product.name} Strain Profile</h2><p className="mt-4 leading-8 text-gray-700">{product.name} is a {product.type.toLowerCase()} profile with {product.genetics.toLowerCase()} and {product.flavor.toLowerCase()} flavor. The experience develops gradually, giving the product a distinct character from the first draw through the finish.</p></article><article><h2 className="text-3xl font-bold">Effects and Flavor</h2><p className="mt-4 leading-8 text-gray-700">Expect {product.effects.toLowerCase()} effects alongside a {product.flavor.toLowerCase()} profile. Draw slowly and give the terpene character time to develop.</p></article><article><h2 className="text-3xl font-bold">Why Live Resin and Liquid Diamonds?</h2><p className="mt-4 leading-8 text-gray-700">Live resin preserves more of the plant&apos;s natural terpene character than standard distillate. Liquid diamonds add a concentrated crystalline THC experience, creating a smoother and more expressive vape.</p></article><article><h2 className="text-3xl font-bold">How to Enjoy</h2><p className="mt-4 leading-8 text-gray-700">Use the AIO for a portable session or save the preroll for a slower, more intentional experience. Store both formats in a cool, dark, dry place away from heat and direct sunlight.</p></article><article><h2 className="text-3xl font-bold">Why LUIGI?</h2><p className="mt-4 leading-8 text-gray-700">Born in Los Angeles, LUIGI combines premium inputs, thoughtful formats, and in-house production to create cannabis products with flavor, consistency, and personality.</p></article></section>
    <section className="mx-auto max-w-7xl px-6 py-12"><h2 className="text-3xl font-bold">Explore More LRLD AIO Products</h2><div className="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{others.map((item) => <Card key={item.slug} href={`/products/${item.slug}`} title={`${item.name} AIO Dual Pack`} image={item.images.hero} alt={`${item.name} LUIGI product`} />)}</div></section>
    <section className="mx-auto max-w-7xl px-6 py-12"><h2 className="text-3xl font-bold">Learn More</h2><div className="mt-6 grid gap-6 md:grid-cols-3">{articles.map(([href, title], index) => <Card key={href} href={href} title={title} image={product.images[(["box", "device", "joint"] as const)[index]]} alt={title} />)}</div></section>
    <section className="mx-auto max-w-4xl space-y-3 px-6 py-12"><h2 className="text-3xl font-bold">Frequently Asked Questions</h2>{faqQuestions.map((question, index) => <details key={question} className="rounded-lg border border-gray-200 p-4" itemScope itemProp="mainEntity" itemType="https://schema.org/Question"><summary className="cursor-pointer font-semibold" itemProp="name">{question}</summary><div itemScope itemProp="acceptedAnswer" itemType="https://schema.org/Answer"><p className="mt-3 leading-7 text-gray-700" itemProp="text">{answer(index)}</p></div></details>)}</section>
    <section className="mx-6 mb-16 rounded-2xl bg-gray-950 px-6 py-14 text-center text-white"><h2 className="text-3xl font-bold">Ready to Experience {product.name}?</h2><p className="mx-auto mt-4 max-w-2xl leading-8 text-gray-300">A 1G live resin liquid diamond disposable and a 0.5G infused preroll for $30. Find LUIGI at a licensed California dispensary near you.</p><Link href="/products/lrld-aio" className="mt-6 inline-flex rounded-full bg-[#d4af37] px-6 py-3 font-semibold text-black">Find a Dispensary</Link></section>
  </main>
}

export { metadataFor } from "@/lib/aio-products"
export type { AioProduct } from "@/lib/aio-products"
export { AIO_PRODUCTS } from "@/lib/aio-products"
