import type { Metadata } from "next"
import Image from "next/image"
import Script from "next/script"
import Link from "next/link"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { AgeVerification } from "@/components/age-verification"
import { AddToCartButton } from "@/components/add-to-cart-button"

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.luigiofficialbrand.com"
const productUrl = `${siteUrl}/products/blue-berries-gummy-pack`
const blueBerriesImages = [
  "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/blue-beries_joint-cyKlqoWypaboFiW5aKJGpfNbkGMLW0.avif",
  "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1789583518-blue_beries-01J7OcwNphj1liB08a5GKnv9G8hoW0.avif",
]

export const metadata: Metadata = {
  title: "Blue Berries Sativa Gummies + Preroll | LUIGI Rosin Pack — $15",
  description: "Ten 10mg bubble hash rosin blueberry sativa gummies paired with a .5g Blue Razz Lime live resin preroll. Just $15. Bright, euphoric, focused. Shop LUIGI in California.",
  keywords: ["blueberry THC gummies", "blueberry sativa gummies", "rosin infused gummies", "THC gummies with preroll", "sativa gummies", "bubble hash rosin gummies California", "blueberry OG preroll", "live resin preroll", "liquid diamonds preroll", "10mg THC gummies", "infused preroll pack", "blueberry gummies California", "rosin edibles California", "blueberry sativa gummies with preroll", "bubble hash rosin infused gummies 100mg", "THC gummy and preroll combo pack", "best rosin gummies Los Angeles", "LUIGI cannabis Los Angeles", "affordable rosin gummies", "$15 THC gummy pack", "euphoric THC gummies", "focused sativa gummies"],
  alternates: { canonical: productUrl },
  openGraph: { title: "Blue Berries Gummy Pack | LUIGI Cannabis — $15", description: "Ten 10mg bubble hash rosin–infused blueberry sativa gummies + a .5g Blue Razz Lime live resin preroll. Just $15. Bright, euphoric, focused.", url: productUrl, siteName: "LUIGI", type: "website", images: [{ url: blueBerriesImages[1], alt: "LUIGI Blue Berries Sativa THC Gummies 10-pack with rosin infusion" }] },
  twitter: { card: "summary_large_image", images: [blueBerriesImages[1]] },
}

const faqs = [
  ["What does bubble hash rosin–infused mean?", "Bubble hash rosin is a solventless cannabis extract prized for its purity and full-spectrum flavor. Infusing it into gummies delivers a cleaner taste and more nuanced effect than distillate-based alternatives."],
  ["Are the Blue Berries Gummies sativa, sativa, or sativa?", "The gummies are sativa, and the paired Blue Razz Lime preroll is also sativa. Expect an uplifting, focused, and euphoric experience."],
  ["What effects do the Blue Berries Sativa Gummies produce?", "Consumers report feeling relaxed, focused, and euphoric. The high is bright and uplifting rather than sedating, making it well-suited for daytime use."],
  ["What does the Blue Berries Gummy Pack taste like?", "The gummies taste like ripe, juicy strawberries with a bright, subtly tangy finish. The Blue Razz Lime preroll adds earthy pine, citrus, gassy undertones, and sweetness."],
  ["How much THC is in each gummy?", "Each gummy contains 10mg THC. The full pack is rated medium potency at 9.5mg THC per pack."],
  ["How much does the Blue Berries Gummy Pack cost?", "The pack retails for $15.00 and includes ten 10mg bubble hash rosin–infused sativa gummies plus one 0.5g Blue Razz Lime live resin and liquid diamonds infused preroll."],
  ["How long do the effects last?", "Edible effects typically begin within 30–90 minutes and can last 4–6 hours. Start low and go slow."],
  ["Can I buy this pack for delivery in Los Angeles?", "LUIGI products are available through licensed California dispensaries. Check your local retailer or delivery service for availability."],
] as const

const productSchema = { "@context": "https://schema.org", "@type": "Product", name: "Blue Berries Gummy Pack", brand: { "@type": "Brand", name: "LUIGI" }, description: "Ten 10mg bubble hash rosin–infused blueberry sativa gummies paired with a .5g Blue Razz Lime live resin and liquid diamonds infused preroll. Medium potency, 9.5mg THC per pack. $15.00. Effects: happy, creative, euphoric.", image: blueBerriesImages, sku: "LUIGI-BB-GUMMY-PACK", category: "Cannabis Edibles > Gummy Packs", keywords: "blueberry THC gummies, blueberry sativa gummies, rosin infused gummies, THC gummies with preroll, sativa gummies, bubble hash rosin gummies California, blueberry OG preroll, live resin preroll, liquid diamonds preroll, 10mg THC gummies, infused preroll pack, blueberry gummies California, rosin edibles California, LUIGI cannabis Los Angeles, affordable rosin gummies, $15 THC gummy pack, euphoric THC gummies, focused sativa gummies", offers: { "@type": "Offer", priceCurrency: "USD", price: "15.00", availability: "https://schema.org/InStock", url: productUrl } }
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }
const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="border-b border-gray-200 py-14 md:py-20"><h2 className="text-3xl font-bold tracking-tight text-black md:text-4xl">{title}</h2><div className="mt-6 flex flex-col gap-5 text-lg leading-8 text-gray-700">{children}</div></section>

export default function PinkLemonadeGummyPackPage() {
  return <>
    <Script id="blue-berries-product-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }} />
    <Script id="blue-berries-faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <AgeVerification /><Header />
    <main className="pt-16 lg:pt-20">
      <section className="bg-black py-16 text-white md:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-2 lg:items-center lg:px-8"><div className="order-2 lg:order-1"><p className="mb-4 text-sm font-semibold uppercase tracking-[0.25em] text-[#D4AF37]">Sativa Gummies</p><h1 className="text-4xl font-bold tracking-tight md:text-6xl">Blue Berries Gummy Pack — Sativa Rosin Gummies + Blue Razz Lime Live Resin Preroll</h1><p className="mt-5 text-xl text-gray-300"><strong>Dangerously delicious. Seriously good.</strong></p><p className="mt-5 text-sm font-semibold uppercase tracking-wide text-gray-400">Medium Potency | 9.5mg THC per pack | 10 Gummies + 1 Preroll</p><p className="mt-5 text-lg text-gray-300">Happy · Creative · Euphoric</p><div className="mt-6 flex flex-wrap items-center gap-4"><span className="text-3xl font-bold">$15.00</span><span className="rounded-full border border-[#D4AF37]/50 px-4 py-2 text-sm text-[#D4AF37]">10 Gummies + 1 Preroll</span></div><AddToCartButton className="mt-6 w-full max-w-sm" product={{ id: "luigi-blueberry-gummy-pack", name: "Blue Berries Gummy Pack", fullName: "LUIGI Blue Berries Gummy Pack", image: blueBerriesImages[1] }} price="$15" priceNumber={15} units="10 gummies + 1 preroll" /><p className="mt-5 max-w-xl text-lg leading-8 text-gray-300">Ten 10mg bubble hash rosin–infused blueberry sativa gummies. One matching .5g Blue Razz Lime live resin preroll. Two ways to experience the same bright, berry-forward flavor — and twice the reason to reach for LUIGI.</p></div><div className="order-1 grid grid-cols-2 gap-4 lg:order-2">{/* Image slot 1 — Hero: full Blue Berries pack and preroll. */}{blueBerriesImages.map((src, index) => <div key={src} className="relative aspect-square overflow-hidden rounded-lg bg-white/10"><Image src={src} alt={index === 0 ? "LUIGI Blue Razz Lime live resin infused sativa preroll" : "LUIGI Blue Berries Sativa THC Gummies 10-pack with rosin infusion"} fill className="object-contain p-4" priority={index === 1} /></div>)}</div></div></section>
      <div className="mx-auto max-w-5xl px-6 lg:px-8">
        <Section title="Two Ways to Experience Blue Berries — One Pack"><p>This isn&apos;t just a blueberry THC gummy pack. It&apos;s a paired experience. Each LUIGI Blue Berries Gummy Pack pairs ten sativa gummies — infused with bubble hash rosin for a cleaner, more flavorful high — with a .5g preroll made from live resin and liquid diamonds.</p><p>The gummies deliver a sweet, juicy, freshly picked blueberry rush. The Blue Razz Lime preroll layers earthy pine, citrus, and classic gassy undertones with a sweet finish. Together, they create a session that goes from first bite to final exhale. This is what a THC gummy and preroll combo pack should feel like — intentional, balanced, and memorable.</p><p>At just <strong>$15.00</strong>, it&apos;s one of the most value-forward rosin-infused gummy packs in California. Premium inputs, in-house production, and a paired preroll — without the premium markup.</p></Section>
        <Section title="What&apos;s Inside the Blue Berries Gummy Pack">{/* Image slot 2 — Pack contents: gummy pack paired with Blue Razz Lime preroll. */}<div className="overflow-x-auto"><table className="w-full border-collapse text-left text-base"><thead><tr className="border-b-2 border-black"><th className="py-3 pr-6">Component</th><th className="py-3">Details</th></tr></thead><tbody>{[["Gummies", "10× 10mg bubble hash rosin–infused blueberry sativa gummies"], ["Preroll", "1× 0.5g Blue Razz Lime live resin + liquid diamonds infused preroll"], ["Total THC", "9.5mg per pack (medium potency)"], ["Type", "Sativa"], ["Effects", "Happy, Creative, Euphoric"], ["Flavor Profile", "Blue Berries, skunk, spicy/herbal, sweet, berry"], ["Price", "$15.00"]].map(([a, b]) => <tr key={a} className="border-b border-gray-200"><td className="py-4 pr-6 font-semibold">{a}</td><td className="py-4">{b}</td></tr>)}</tbody></table></div></Section>
        <Section title="Blue Berries Gummy: Sweet, Juicy, Bursting with Berry">{/* Image slot 3 — Gummy close-up: blueberry rosin gummy texture. */}<p>Sweet, juicy, and bursting with berry goodness, our Blue Berries THC Sativa Gummies capture the irresistible flavor of juicy blueberries. Each soft, chewy bite delivers ripe blueberry sweetness with a bright, subtly tangy finish — a nostalgic fruit-forward flavor transformed into a refined edible experience.</p><p>Bubble hash rosin is a solventless cannabis extract prized for purity and full-spectrum flavor. Infusing it into gummies delivers a cleaner taste and more nuanced effect than distillate-based alternatives. The result is a 10mg THC gummy that tastes like real fruit — not chemicals — and hits with the consistency LUIGI is known for.</p><p>Each gummy is a standard 10mg serving, making dosing simple whether you&apos;re a seasoned connoisseur or new to sativa gummies. For a milder experience, split the gummy in half. Effects typically begin within 30–90 minutes — give it time before reaching for another.</p></Section>
        <Section title="High Potency Meets Full-Spectrum Flavor"><p>The Blue Berries Gummy Pack is built for daytime sessions and creative flow. The sativa-leaning gummies deliver a bright, uplifting high that starts with gentle euphoria, settles into focused clarity, and finishes with a relaxed body calm that never tips into sedation.</p><p>That combination makes this pack ideal for social settings, creative work, outdoor afternoons, or anytime you want to feel elevated without being weighed down. The paired Blue Razz Lime preroll leans into the same sativa energy, with earthy pine and citrus notes adding a grounded counterpoint to the gummies&apos; bright berry profile.</p></Section>
        <Section title="Blue Razz Lime PreRoll: A Refreshing Escape">{/* Image slot 4 — Preroll close-up: Blue Razz Lime live resin infused sativa preroll. */}<p>Sweet blueberry meets the unmistakable character of OG in this flavorful live resin-infused sativa pre-roll. Bright berry notes are followed by earthy pine, citrus, and classic gassy undertones. A touch of sweetness rounds out the finish, balancing fruity freshness with deep, savory cannabis notes.</p><p>Live resin preserves the plant&apos;s natural terpenes for a flavorful, aromatic smoke. Liquid diamonds add a potent, crystalline THC punch. Together, they create an infused preroll that&apos;s both smooth and strong — the kind of Blue Razz Lime preroll that reminds you why extract-infused flower is worth seeking out.</p></Section>
        <Section title="How to Enjoy the Blue Berries Gummy Pack">{/* Image slot 5 — Lifestyle / pairing: gummies and Blue Razz Lime preroll. */}<p><strong>The Gummies:</strong> Start with one. Each gummy is a standard 10mg serving. For a milder experience, split the gummy in half. Effects typically begin within 30–90 minutes.</p><p><strong>The Preroll:</strong> Save it for the come-up, peak, or wind-down. The Blue Razz Lime live resin and liquid diamonds deliver a smooth, flavorful smoke that complements the gummy experience.</p><p><strong>The Pairing:</strong> Enjoy the preroll while the gummies take effect. The combination of edible sativa high and inhalable terpene profile creates a layered, memorable session.</p><p><strong>Dosing Tip for New Consumers:</strong> Start with half a gummy (5mg) and wait a full 90 minutes before deciding whether to take more.</p></Section>
        <Section title="How the Blue Berries Gummy Pack Compares to Distillate Gummies"><p>Most gummies use distillate — a refined THC extract that is potent but stripped of most natural terpenes and minor cannabinoids. The flavor is typically added back artificially, and the effect can feel flatter and more one-dimensional.</p><p>LUIGI uses bubble hash rosin instead. Rosin is solventless, full-spectrum, and retains terpenes, flavonoids, and minor cannabinoids. That means the blueberry flavor is coming from the same place the effect is — not a flavor additive. Add a Blue Razz Lime live resin preroll, and you get two full-spectrum experiences for $15.00.</p></Section>
        <Section title="Premium Rosin Gummies at a $15 Price Point"><p>Most rosin-infused edible packs in California retail between $25 and $40. The LUIGI Blue Berries Gummy Pack delivers the same solventless-infused quality — plus a live resin and liquid diamonds preroll — for just $15.00.</p><p>Everything we do starts in-house: formulation, production, packaging, and distribution. No middlemen. No inflated wholesale markups. Just premium cannabis products priced for the people who actually smoke them.</p><p>If you&apos;ve been searching for affordable rosin gummies in California without sacrificing flavor or potency, this is the pack.</p></Section>
        <Section title="Why LUIGI?">{/* Image slot 6 — Brand and lifestyle: LUIGI quality without pretense in Los Angeles. */}<p>Born in Los Angeles and built from the ground up, LUIGI is a cannabis brand for people who appreciate quality without the pretense. Everything starts in-house, giving us complete control over every product that carries our name.</p><p>We combine premium inputs, innovative hardware, and unique product formats to create experiences that stand out. Whether it&apos;s signature Dual Packs, rosin-infused products, Fattone collections, or limited-edition drops, LUIGI delivers flavor, potency, consistency, and value.</p><p>We&apos;re inspired by art, culture, hospitality, and the communities that support us. LUIGI isn&apos;t just a cannabis brand — it&apos;s a movement built around bringing people together.</p></Section>
        <Section title="Frequently Asked Questions"><div className="flex flex-col gap-3">{faqs.map(([question, answer]) => <details key={question} itemScope itemType="https://schema.org/Question" className="group rounded-lg border border-gray-200 bg-white"><summary itemProp="name" className="flex cursor-pointer list-none items-center justify-between gap-4 px-5 py-4 text-lg font-bold text-black marker:content-none"><span>{question}</span><span aria-hidden="true" className="text-2xl font-normal leading-none text-[#B08D24] transition-transform group-open:rotate-45">+</span></summary><div itemScope itemProp="acceptedAnswer" itemType="https://schema.org/Answer" className="border-t border-gray-200 px-5 py-4 leading-7 text-gray-700"><p itemProp="text">{answer}</p></div></details>)}</div></Section>
      </div>
      <section className="bg-black py-16 text-center text-white"><div className="mx-auto max-w-3xl px-6">{/* Image slot 7 — Final CTA: Blue Berries pack at a California dispensary. */}<h2 className="text-3xl font-bold md:text-4xl">Ready to Experience the Blue Berries Gummy Pack?</h2><p className="mt-5 text-lg leading-8 text-gray-300">Ten rosin-infused sativa gummies. One Blue Razz Lime live resin preroll. Twice the flavor. Twice the experience. Just $15.00. Find LUIGI at a licensed California dispensary near you.</p><Link href="/find-luigi" className="mt-8 inline-flex rounded-md bg-[#D4AF37] px-6 py-3 font-semibold text-black transition hover:bg-[#E3C45B]">Find a Dispensary — $15</Link></div></section>
    </main><Footer />
  </>
}
