export const SITE_URL = "https://www.luigiofficialbrand.com"

export type AioProduct = {
  slug: string
  name: string
  type: "Sativa" | "Hybrid" | "Indica"
  sku: string
  flavor: string
  effects: string
  genetics: string
  images: { hero: string; box: string; joint: string; device: string }
}

const assets: Record<string, AioProduct["images"]> = {
  "acapulco-gold-aio-dual-pack": { hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790013755-mexico_city_family-YROupYzATIAGnoHEHdzEkN11s8U5tB.avif", box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mexico_city_box.avif", joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mexico_city_joint.avif", device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mexico_city_device.avif" },
  "bubblegum-kush-aio-dual-pack": { hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790013959-hollywood_family-lvflB1XEERxiqSzFHOlWKfWqmMU63x.avif", box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hollywood_box.avif", joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hollywood_joint.avif", device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/hollywood_device.avif" },
  "bullet-trainwreck-aio-dual-pack": { hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790014410-tokyo_family-echqNcZhLenruPxCk3vPoCRQYx3GXt.avif", box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tokyo_box%20%281%29-nXoO5Beb1hUe6F7tEdf5vhi2NzCds0.avif", joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tokyo_joint%20%281%29-1LChdJFtFYNYoiKI42Hu5avCNC8zH4.avif", device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tokyo_device%20%281%29-L50FwlEqQpTriemHBbcJpruPu6Yedw.avif" },
  "eiffel-lights-aio-dual-pack": { hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790015070-paris_family-38y4dcaon4oUuTYvnfIp9FWpRo24Xz.avif", box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/paris_box-CkMqyP2ZTeKYn8EK73E3xuSTfDYL4V.avif", joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/paris_joint-dXhj0srIG08KEddAdCqmXRuKPXu8B1.avif", device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/paris_device-C1x45lL2miTOIHgtXdzD2tOgGDdOG1.avif" },
  "green-crack-aio-dual-pack": { hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790014557-singapore_family-BpZS90ksyS4kyyqGqEnZOh7E2vkyhq.avif", box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/signapore_box-vJYN19w2CGadIWW7gMenCzEQxDbyuO.avif", joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/singapore_joint-pF4I3illiulkPM9OPI4TQiUlDljeQQ.avif", device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/signapore_device-pAPocjv4nIAxC9hS1szF54fSK3OHEa.avif" },
  "manhattan-midnight-aio-dual-pack": { hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790013592-new_york_family-xQxSK50iaUFDFMh4z6z4VIECReNuBD.avif", box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new-york_box-EeJZniYXLFoJvCKFXthPAd8nJWmsUC.avif", joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new-york_joint-jekLHIDmv9r7OABDNR4Fycvfl5qpwL.avif", device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/new-york_device-2Xoq8hNuTQGX9jBzp8slNVLzBhywBb.avif" },
  "private-reserve-aio-dual-pack": { hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790014743-dubai_family-K8QzPho5h62yKJ2WyjX7PgDo7F4gAN.avif", box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dubai_box-qbBVgucWsgmWGzVDbYCh8M5jfpPiZq.avif", joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dubai_joint-KEFJBwvmvY4W7iTM8rzxALHfkbLdjY.avif", device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dubai_device-GLaRBvRxrv9Lohb7VQECwHTlRfTukt.avif" },
  "thai-blaze-aio-dual-pack": { hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790013166-bangkok_family-d9nkzceWmOdUd52nc23FXNKGtqMa6M.avif", box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bangkok_box-WSsR5cUN7OQFJUl9gA1mrkGxOHoq3Y.avif", joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bangkok_joint-iDtfK2MOFjgH8WR5e9jGBbrLDqQkUW.avif", device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bangkok_device-Q2XNLndyz6W6KqqmdKR7x64c9DsvNp.avif" },
  "tower-fog-og-aio-dual-pack": { hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790014224-london_family-nPv27u5y1HGPsGBKgsplY29m0bGkvg.avif", box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/london_box-ECL2tITG9LDSzWxkUyuJAO8kI5AXh5.avif", joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/london_joint-11kHZo537pt2qTR2QBvmLQ6mjZPytU.avif", device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/london_device-l19cLVYXnOeXUvTfGxjIQ68HoLKZZn.avif" },
  "canal-drift-aio-dual-pack": { hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790014111-venice_family-KOjN79g82qeVL3kEpSwgfJeGODSrHj.avif", box: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venice_box-dcM73clb8w6jzO0FhA5nT7JxqYbBfB.avif", joint: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venice_joint-yGckOwael6xEzloxuO9l7hqoSFnfkb.avif", device: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venice_device-16X65n14IzRgPQqtYaLa6l0YL6wZGt.avif" },
}

const definitions: [string, string, AioProduct["type"], string, string, string, string][] = [
  ["acapulco-gold-aio-dual-pack", "Acapulco Gold", "Sativa", "LUIGI-AG-AIO-DUAL", "Skunk, blueberry, and pungent tropical notes", "Happy, creative, and energetic", "Mexican × Nepalese landrace"],
  ["bubblegum-kush-aio-dual-pack", "Bubblegum Kush", "Hybrid", "LUIGI-BK-AIO-DUAL", "Sweet bubblegum, berry, pine, citrus, and earth", "Relaxed, giggly, happy, euphoric, sleepy, and uplifted", "Bubble Gum genetics from The Bulldog Seeds in Amsterdam"],
  ["bullet-trainwreck-aio-dual-pack", "Bullet Trainwreck", "Sativa", "LUIGI-BT-AIO-DUAL", "Bright, pungent, terpene-forward flavor", "Energetic, focused, and uplifting", "Trainwreck-inspired sativa profile"],
  ["eiffel-lights-aio-dual-pack", "Eiffel Lights", "Hybrid", "LUIGI-EL-AIO-DUAL", "Bold terpene profile with loud flavor", "Balanced, uplifting, and social", "Balanced hybrid profile"],
  ["green-crack-aio-dual-pack", "Green Crack", "Sativa", "LUIGI-GC-AIO-DUAL", "Skunk, citrus, mango, earthy, and sweet", "Energetic, uplifted, happy, creative, euphoric, and focused", "Skunk #1 × Afghani"],
  ["manhattan-midnight-aio-dual-pack", "Manhattan Midnight", "Indica", "LUIGI-MM-AIO-DUAL", "Deep, bold, rich, and smooth", "Relaxing, calm, and unwinding", "Deep indica profile"],
  ["private-reserve-aio-dual-pack", "Private Reserve", "Hybrid", "LUIGI-PR-AIO-DUAL", "Rich, layered, and refined", "Balanced, refined, and elevated", "Balanced hybrid profile"],
  ["thai-blaze-aio-dual-pack", "Thai Blaze", "Sativa", "LUIGI-TB-AIO-DUAL", "Tropical, citrus, and earthy", "Energetic, uplifting, and creative", "Thai-inspired sativa profile"],
  ["tower-fog-og-aio-dual-pack", "Tower Fog OG", "Indica", "LUIGI-TFO-AIO-DUAL", "Deep OG, earthy, and smooth", "Relaxing, calm, and heavy-hitting", "OG indica profile"],
  ["canal-drift-aio-dual-pack", "Canal Drift", "Indica", "LUIGI-CD-AIO-DUAL", "Rich, earthy, smooth, and lingering", "Relaxing, calm, and flowing", "Bold indica profile"],
]

export const AIO_PRODUCTS: AioProduct[] = definitions.map(([slug, name, type, sku, flavor, effects, genetics]) => ({ slug, name, type, sku, flavor, effects, genetics, images: assets[slug] }))
export function getAioProduct(slug: string) { return AIO_PRODUCTS.find((product) => product.slug === slug) }
export function aioKeywords(product: AioProduct) { return [`${product.name.toLowerCase()} aio`, `${product.name.toLowerCase()} dual pack`, `${product.name.toLowerCase()} disposable`, `${product.name.toLowerCase()} vape`, `${product.name.toLowerCase()} preroll`, "live resin disposable", "liquid diamond disposable", "live resin vape California", "liquid diamond vape", "aio disposable vape", "all in one vape", "disposable + preroll combo", "vape and preroll pack", `${product.type.toLowerCase()} vape California`, `${product.type.toLowerCase()} disposable`, `${product.type.toLowerCase()} AIO`, "LUIGI cannabis vapes", "LUIGI AIO", "$30 AIO pack", "premium live resin vape", "California live resin vape", "cannabis vape delivery Los Angeles", "1G disposable vape", "0.5g infused preroll", product.flavor, product.effects, product.genetics, "V11 AIO", "California cannabis vape", "live resin liquid diamonds", "premium cannabis dual pack"] }
export function productUrl(product: AioProduct) { return `${SITE_URL}/products/${product.slug}` }
export function metadataFor(product: AioProduct) { return { title: `${product.name} AIO Dual Pack | LUIGI Live Resin + Preroll — $30`, description: `${product.name} live resin liquid diamond disposable + 0.5g infused preroll. 1G AIO + 0.5G preroll. Just $30. Shop LUIGI in California.`, keywords: aioKeywords(product), alternates: { canonical: productUrl(product) }, openGraph: { title: `${product.name} AIO Dual Pack | LUIGI Live Resin + Preroll — $30`, description: `${product.name} live resin liquid diamond disposable + 0.5g infused preroll. Just $30.`, url: productUrl(product), siteName: "LUIGI", type: "website", images: [{ url: product.images.hero, alt: `LUIGI ${product.name}` }] } } }
