import type { Metadata } from "next"
import Script from "next/script"
import Link from "next/link"
import Image from "next/image"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { AgeVerification } from "@/components/age-verification"
import { AddToCartButton } from "@/components/add-to-cart-button"

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.luigiofficialbrand.com"
const productUrl = `${siteUrl}/products/peanut-butter-breath-blunt-2pk`
const images = {
  hero: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1790271722-peanut_butter_breath_family-C9f1QXq076kJTdiPfKBeQcdYgDQgP2.avif",
  pack: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/peanut-butter-breath_tube-zpFkuvYcHGqtR5s5JH6DpWk9xFTbXT.avif",
  close: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/peanut-butter-breath_blunt-qmQqayyCI2HA4bB4c6PWtOaLZXRrOA.avif",
}

const product = { id: "peanut-butter-breath-blunt-2pk", name: "Peanut Butter Breath Blunt 2-Pack", fullName: "Peanut Butter Breath Blunt 2-Pack", image: images.hero }

export const metadata: Metadata = {
  title: "Peanut Butter Breath Rosin Blunt 2-Pack | LUIGI Hybrid — $30",
  description: "Two 1.25g rosin-infused Peanut Butter Breath hybrid blunts. 2.5g total. Nutty, gassy, smooth. Just $30. Shop LUIGI in California.",
  keywords: ["peanut butter breath blunt", "peanut butter breath 2 pack", "rosin infused blunts", "hybrid blunts California", "peanut butter breath strain", "thugpug genetics peanut butter breath", "do si dos mendo breath cross", "premium rosin blunts", "2.5g blunt pack", "infused blunt pack California", "LUIGI cannabis blunts", "LUIGI blunt 2 pack", "best rosin blunts California", "affordable rosin blunts", "$30 blunt pack", "nutty weed strains", "gassy hybrid blunts", "peanut butter breath effects", "relaxed hybrid blunts", "California rosin blunts", "buy blunts online California", "cannabis blunt delivery Los Angeles", "premium infused blunts", "1.25g blunts"],
  alternates: { canonical: productUrl },
  openGraph: { title: "Peanut Butter Breath Rosin Blunt 2-Pack | LUIGI Cannabis — $30", description: "Two 1.25g rosin-infused Peanut Butter Breath hybrid blunts. 2.5g total. Nutty, gassy, smooth. Just $30.", url: productUrl, siteName: "LUIGI", type: "website", images: [{ url: images.hero, alt: "LUIGI Peanut Butter Breath Rosin Infused Hybrid Blunt 2-Pack" }] },
}

const details = [
  ["Blunts", "2× 1.25g rosin-infused blunts"], ["Total Weight", "2.5g total"], ["Strain", "Peanut Butter Breath"], ["Type", "Hybrid"], ["Genetics", "Do-Si-Dos × Mendo Breath (ThugPug Genetics)"], ["Effects", "Relaxed, Happy, Giggly"], ["Flavor Profile", "Nutty, earthy, woody, gassy"], ["Price", "$30.00"],
]
const faq = [
  ["What's included in the Peanut Butter Breath Blunt 2-Pack?", "The pack includes two 1.25g rosin-infused blunts — 2.5g total. Both blunts are packed with Peanut Butter Breath hybrid flower infused with premium rosin."],
  ["What strain is in the Peanut Butter Breath Blunt 2-Pack?", "Peanut Butter Breath — a hybrid strain from ThugPug Genetics, bred from a Do-Si-Dos and Mendo Breath cross. Known for its nutty flavor, striking frost, and cheerful high with substantial physical weight."],
  ["Is Peanut Butter Breath indica, sativa, or hybrid?", "Hybrid. The strain leans into its indica lineage on the back end but keeps a cheerful, social front end. Effects are typically relaxed, happy, and giggly."],
  ["What does Peanut Butter Breath taste like?", "Nutty, earthy, and woody with a punch of classic gas on the finish. The first notes are creamy and smooth — almost dessert-like — before earthy and woody undertones come forward."],
  ["What effects does Peanut Butter Breath produce?", "Consumers consistently report feeling relaxed, happy, and giggly. The high starts cheerful and social before settling into a slow, unwinding finish with substantial body calm."],
  ["How much does the Peanut Butter Breath Blunt 2-Pack cost?", "The LUIGI Peanut Butter Breath Blunt 2-Pack retails for $30.00 and includes two 1.25g rosin-infused blunts — 2.5g total."],
  ["How strong are LUIGI rosin-infused blunts?", "Each blunt contains 1.25g of Peanut Butter Breath flower infused with premium rosin. The exact THC percentage varies by batch — check the packaging or your dispensary listing for the current test results."],
  ["How should I store my blunts?", "Store your blunts in a cool, dark, dry place — ideally in an airtight container away from direct sunlight and heat. Proper storage helps preserve both the terpene flavor and the potency of the rosin infusion."],
  ["Can I buy LUIGI blunts for delivery in Los Angeles?", "LUIGI products are available through licensed California dispensaries. Check your local retailer or delivery service for availability."],
  ["What's the difference between a rosin-infused blunt and a regular blunt?", "A regular blunt is just flower. A rosin-infused blunt adds premium solventless rosin extract on top of the flower — boosting both potency and flavor complexity. The result is a richer, more layered smoke with fuller terpene expression."],
]

const schema = { "@context": "https://schema.org", "@type": "Product", "@id": `${productUrl}#product`, name: product.name, url: productUrl, mainEntityOfPage: productUrl, brand: { "@type": "Brand", name: "LUIGI" }, description: "Two 1.25g rosin-infused Peanut Butter Breath hybrid blunts — 2.5g total. Nutty, earthy, woody, and gassy with relaxed, happy, giggly effects. $30.00.", sku: "LUIGI-PBB-BLUNT-2PK", category: "Cannabis > Pre-Rolls > Infused Blunts", image: Object.values(images), offers: { "@type": "Offer", url: productUrl, priceCurrency: "USD", price: "30.00", priceValidUntil: "2026-12-31", availability: "https://schema.org/InStock", itemCondition: "https://schema.org/NewCondition", seller: { "@type": "Organization", name: "LUIGI" } }, keywords: "peanut butter breath blunt, peanut butter breath 2 pack, rosin infused blunts, hybrid blunts California, peanut butter breath strain, thugpug genetics, do si dos mendo breath cross, premium rosin blunts, 2.5g blunt pack, infused blunt pack California, LUIGI cannabis blunts, LUIGI blunt 2 pack, best rosin blunts California, $30 blunt pack, nutty weed strains, gassy hybrid blunts, peanut butter breath effects, relaxed hybrid blunts, California rosin blunts, buy blunts online California, cannabis blunt delivery Los Angeles, premium infused blunts" }
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }

function SlotImage({ src, alt, comment }: { src: string; alt: string; comment: string }) {
  return <div className="relative aspect-square overflow-hidden rounded-xl bg-gray-100">{/* {comment} */}<Image src={src} alt={alt} fill className="object-contain p-5" sizes="(max-width: 768px) 100vw, 50vw" /></div>
}
function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="border-t border-gray-200 py-12"><h2 className="mb-6 text-3xl font-bold text-gray-950">{title}</h2><div className="max-w-4xl space-y-5 leading-8 text-gray-600">{children}</div></section>
}

export default function PeanutButterBreathBluntPage() {
  return <>
    <Script id="pbb-product-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <Script id="pbb-faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <AgeVerification /><Header />
    <main className="bg-white pt-16 lg:pt-20">
      <section className="mx-auto max-w-7xl px-6 py-12 lg:px-8 lg:py-20"><Link href="/products/blunt-2pk" className="text-sm font-semibold text-gray-600 hover:text-black">← Back to Blunt 2pk</Link><div className="mt-8 grid gap-12 lg:grid-cols-2 lg:items-center"><SlotImage src={images.hero} alt="LUIGI Peanut Butter Breath Rosin Infused Hybrid Blunt 2-Pack" comment="Slot 1 — Hero" /><div><p className="text-sm font-semibold uppercase tracking-[0.22em] text-[#9a7b16]">LUIGI Blunt 2pk</p><h1 className="mt-4 text-4xl font-bold tracking-tight text-gray-950 md:text-6xl">Peanut Butter Breath Blunt 2-Pack — Rosin-Infused Hybrid Blunts</h1><p className="mt-5 text-xl font-semibold text-gray-700">Nutty, gassy, and oh-so-smooth.</p><p className="mt-5 leading-8 text-gray-600">Two 1.25g blunts loaded with premium rosin — 2.5g total. Creamy peanut butter vibes, earthy terps, and a punch of classic gas. Rich flavor, bold character, and double the fun in every pack.</p><div className="my-7 grid grid-cols-2 gap-3 border-y border-gray-200 py-5 text-sm font-semibold text-gray-700"><span>Hybrid</span><span>2 × 1.25g Blunts</span><span>2.5g Total</span><span>Rosin Infused</span></div><p className="text-3xl font-bold text-gray-950">$30.00</p><div className="mt-6"><AddToCartButton product={product} price="$30.00" priceNumber={30} units="2 × 1.25g" perUnit="per 2-pack" /></div></div></div><nav aria-label="Product page sections" className="mt-8 flex flex-wrap gap-4 text-sm font-semibold"><a href="#product-details" className="text-gray-600 underline underline-offset-4 hover:text-black">Product details</a><a href="#frequently-asked-questions" className="text-gray-600 underline underline-offset-4 hover:text-black">Frequently asked questions</a></nav></section>
      <div className="mx-auto grid max-w-7xl gap-6 px-6 pb-4 md:grid-cols-2 lg:px-8"><SlotImage src={images.pack} alt="Two 1.25g Peanut Butter Breath rosin blunts — 2.5g total" comment="Slot 2 — Pack Contents" /><SlotImage src={images.close} alt="Close-up of Peanut Butter Breath rosin-infused blunt with visible oil ring" comment="Slot 3 — Blunt Close-Up" /></div>
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <Section title="Two Blunts. One Iconic Strain. Double the Fun."><p>The LUIGI Rosin Infused Double Blunt Pack comes loaded with two 1.25g blunts, packing a total of 2.5g of bold, flavorful goodness. Perfect for sharing — or keeping both for yourself. Game on.</p><p>A savory standout from ThugPug Genetics, Peanut Butter Breath combines nutty flavor, striking frost, and a cheerful high with substantial physical weight. Its hybrid classification leaves plenty of room for a decidedly slow finish.</p><p>At $30.00, you're getting 2.5g of rosin-infused flower across two full blunts — premium inputs and in-house production, without the inflated markup most rosin blunt packs carry.</p></Section>
        <div id="product-details"><Section title="What's Inside the Peanut Butter Breath Blunt 2-Pack"><div className="overflow-x-auto"><table className="w-full min-w-[560px] border-collapse text-left text-sm"><tbody>{details.map(([label, value]) => <tr key={label} className="border-b border-gray-200"><th className="py-4 pr-5 font-semibold text-gray-950">{label}</th><td className="py-4">{value}</td></tr>)}</tbody></table></div></Section></div>
        <Section title="Peanut Butter Breath — A Savory Standout from ThugPug Genetics"><p>Peanut Butter Breath is one of those rare strains that earns its reputation on flavor alone — and then backs it up with effect. Bred by ThugPug Genetics from a Do-Si-Dos and Mendo Breath cross, it's a hybrid that leans into its indica lineage on the back end while keeping the front end cheerful and social.</p><p>The flower is known for its striking frost coverage, dense structure, and unmistakable nutty, earthy aroma with a gas-forward finish. When you light up a Peanut Butter Breath blunt, you're getting the full expression of the strain — no shortcuts, no filler.</p><div className="rounded-xl bg-gray-950 p-8 text-white"><p className="text-lg font-semibold">A savory standout from ThugPug Genetics.</p><p className="mt-4 leading-8 text-gray-300">Dense structure, striking frost, nutty terpenes, and a gas-forward finish.</p></div></Section>
        <Section title="Peanut Butter Breath Effects: Relaxed, Happy, Giggly"><p>Consumers consistently report three signature effects from Peanut Butter Breath: relaxed, happy, and giggly. The high starts with a cheerful, mood-lifting wave that's social and easygoing — perfect for sharing with friends or enjoying solo.</p><p>As the experience settles in, the hybrid's physical weight becomes more apparent. It's not a couch-lock indica, but it's not a racy sativa either. Instead, it lands in that sweet spot: substantial body calm paired with a light, playful head high. The slow finish is where Peanut Butter Breath really earns its keep — a gentle, unwinding descent that's ideal for evenings, weekends, or anytime you want to feel good without being overwhelmed.</p></Section>
        <Section title="Nutty, Earthy, Woody — A Flavor Experience Worth Savoring"><p>Peanut Butter Breath delivers a flavor profile that's as distinctive as its name suggests. The first notes are creamy, nutty, and smooth — almost dessert-like in their richness. As the smoke develops, earthy and woody undertones come forward, adding depth and complexity.</p><p>The finish brings a punch of classic gas that cuts through the sweetness and keeps things grounded. It's a flavor journey that rewards slow, intentional draws — the kind of blunt you actually want to sit with and enjoy rather than rush through.</p></Section>
        <Section title="Why We Infuse with Premium Rosin"><p>Most infused blunts on the market use distillate — a refined THC extract that's potent but stripped of the plant's natural terpenes and minor cannabinoids. The result is a blunt that gets you high, but the flavor feels flat and the effect feels one-dimensional.</p><p>LUIGI blunts are infused with premium rosin instead. Rosin is solventless, full-spectrum, and retains the plant's natural terpenes, flavonoids, and minor cannabinoids. That means the nutty, earthy, gassy flavor of Peanut Butter Breath is coming from the same place the effect is — not from an artificial flavor additive.</p><p>The result is a smoother, richer, more layered smoke — the kind of experience that reminds you why rosin-infused flower is worth seeking out.</p></Section>
        <Section title="How to Enjoy the Peanut Butter Breath Blunt 2-Pack"><p><strong>Sharing:</strong> With two 1.25g blunts in every pack, this is built for sharing. Pass one around with friends and save the second for later — or keep both for yourself. Game on.</p><p><strong>Solo Session:</strong> If you're enjoying solo, one blunt is plenty for a full session. Start slow, take your time, and let the strain's slow finish do its thing.</p><p><strong>Storage:</strong> Keep your blunts in a cool, dark, dry place — ideally in an airtight container away from direct sunlight and heat. Proper storage helps preserve both the terpene flavor and the potency of the rosin infusion.</p></Section>
        <Section title="How the Peanut Butter Breath Blunt 2-Pack Compares to Distillate Blunts"><p>Most infused blunts on the market use distillate — a refined THC extract that's potent but stripped of most of the plant's natural terpenes and minor cannabinoids. The flavor is typically added back in artificially, and the effect tends to feel flat.</p><p>The LUIGI Peanut Butter Breath Blunt 2-Pack uses premium rosin instead. Rosin is solventless, full-spectrum, and retains the plant's terpenes, flavonoids, and minor cannabinoids. That means the nutty, gassy flavor of Peanut Butter Breath is coming from the same place the effect is — not from a flavor additive.</p><p>Two 1.25g blunts for $30.00 means you're getting 2.5g of rosin-infused flower at a price point that distillate packs of the same size barely compete with — let alone rosin-infused ones.</p></Section>
        <Section title="Premium Rosin Blunts at a $30 Price Point"><p>Most rosin-infused blunt packs in California retail between $40 and $60 for a similar 2.5g format. The LUIGI Peanut Butter Breath Blunt 2-Pack delivers the same solventless-infused quality — plus two full 1.25g blunts — for just $30.00.</p><p>How? Because everything we do starts in-house. Formulation, production, packaging, and distribution all happen under one roof. No middlemen. No inflated wholesale markups. Just premium cannabis products priced fairly for the people who actually smoke them.</p><p>If you've been searching for quality rosin blunts in California without overpaying, this is the pack.</p></Section>
        <Section title="Why LUIGI?"><p>Born in Los Angeles and built from the ground up, LUIGI is a cannabis brand for people who appreciate quality without the pretense. Everything we do starts in-house — formulation, production, packaging, distribution — giving us complete control over every product that carries our name.</p><p>We combine premium inputs, innovative hardware, and unique product formats to create experiences that stand out in a crowded market. Whether it's our signature Dual Packs, rosin-infused products, Fattone collections, or limited-edition drops, LUIGI is committed to delivering flavor, potency, consistency, and value in every package.</p><p>We're inspired by art, culture, hospitality, and the communities that support us. That's why LUIGI isn't just a cannabis brand — it's a movement built around bringing people together and making every session a little more memorable. When you choose LUIGI, you're not just buying rosin blunts in California. You're joining something.</p></Section>
        <section id="frequently-asked-questions" className="border-t border-gray-200 py-12 scroll-mt-24" itemScope itemType="https://schema.org/FAQPage"><h2 className="mb-8 text-3xl font-bold text-gray-950">Frequently Asked Questions About Peanut Butter Breath Blunts</h2><div className="space-y-7">{faq.map(([question, answer]) => <div key={question} itemScope itemProp="mainEntity" itemType="https://schema.org/Question"><h3 itemProp="name" className="text-lg font-semibold text-gray-950">{question}</h3><div itemScope itemProp="acceptedAnswer" itemType="https://schema.org/Answer"><p itemProp="text" className="mt-2 max-w-4xl leading-7 text-gray-600">{answer}</p></div></div>)}</div></section>
        <section className="mb-16 rounded-xl bg-black px-6 py-14 text-center text-white"><h2 className="text-3xl font-bold md:text-4xl">Ready to Experience the Peanut Butter Breath Blunt 2-Pack?</h2><p className="mx-auto mt-5 max-w-2xl leading-8 text-gray-300">Two 1.25g rosin-infused blunts. 2.5g total. Nutty, gassy, and oh-so-smooth. Just $30.00. Find LUIGI at a licensed California dispensary near you.</p><Link href="/products/peanut-butter-breath-blunt-2pk" className="mt-7 inline-flex rounded-full bg-[#D4AF37] px-7 py-3 font-bold text-black">Find a Dispensary — $30</Link></section>
      </div>
    </main><Footer />
  </>
}
