import type { Metadata } from "next"
import Image from "next/image"
import Script from "next/script"
import Link from "next/link"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { RelatedGummyProducts } from "@/components/related-gummy-products"
import { AgeVerification } from "@/components/age-verification"
import { AddToCartButton } from "@/components/add-to-cart-button"

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.luigiofficialbrand.com"
const productUrl = `${siteUrl}/products/caribbean-fruit-gummy-pack`
const caribbeanImages = [
  "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/caribbean-fruits_joint-MTR6A6xNdZi4wTnOT0XQ0yFbhzkRYz.avif",
  "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1789583174-caribbean_fruits_1___1_-0el80i5SNlRA91IuKKzd5DwyMY7Q8m.avif",
]

export const metadata: Metadata = {
  title: "Caribbean Fruit Indica Gummies + Preroll | LUIGI Rosin Pack — $15",
  description: "Ten 10mg bubble hash rosin Caribbean fruit indica gummies paired with a .5g Blood Orange live resin preroll. Just $15. Bright, euphoric, focused. Shop LUIGI in California.",
  keywords: ["Caribbean fruit THC gummies", "Caribbean fruit indica gummies", "rosin infused gummies", "THC gummies with preroll", "indica gummies", "bubble hash rosin gummies California", "Caribbean fruit OG preroll", "live resin preroll", "liquid diamonds preroll", "10mg THC gummies", "infused preroll pack", "Caribbean fruit gummies California", "rosin edibles California", "Caribbean fruit indica gummies with preroll", "bubble hash rosin infused gummies 100mg", "THC gummy and preroll combo pack", "best rosin gummies Los Angeles", "LUIGI cannabis Los Angeles", "affordable rosin gummies", "$15 THC gummy pack", "euphoric THC gummies", "focused indica gummies"],
  alternates: { canonical: productUrl },
  openGraph: { title: "Caribbean Fruit Gummy Pack | LUIGI Cannabis — $15", description: "Ten 10mg bubble hash rosin–infused Caribbean fruit indica gummies + a .5g Blood Orange live resin preroll. Just $15. Bright, euphoric, focused.", url: productUrl, siteName: "LUIGI", type: "website", images: [{ url: caribbeanImages[1], alt: "LUIGI Caribbean Fruit Indica THC Gummies 10-pack with rosin infusion" }] },
  twitter: { card: "summary_large_image", images: [caribbeanImages[1]] },
}

const faqs = [
  ["What does bubble hash rosin–infused mean?", "Bubble hash rosin is a solventless cannabis extract prized for its purity and full-spectrum flavor. Infusing it into gummies delivers a cleaner taste and more nuanced effect than distillate-based alternatives."],
  ["Are the Caribbean Fruit Gummies indica, indica, or indica?", "The gummies are indica, and the paired Blood Orange preroll is also indica. Expect an uplifting, focused, and euphoric experience."],
  ["What effects do the Caribbean Fruit Indica Gummies produce?", "Consumers report feeling relaxed, focused, and euphoric. The high is bright and uplifting rather than sedating, making it well-suited for daytime use."],
  ["What does the Caribbean Fruit Gummy Pack taste like?", "The gummies taste like ripe, juicy strawberries with a bright, subtly tangy finish. The Blood Orange preroll adds earthy pine, citrus, gassy undertones, and sweetness."],
  ["How much THC is in each gummy?", "Each gummy contains 10mg THC. The full pack is rated high potency at 10mg THC per pack."],
  ["How much does the Caribbean Fruit Gummy Pack cost?", "The pack retails for $15.00 and includes ten 10mg bubble hash rosin–infused indica gummies plus one 0.5g Blood Orange live resin and liquid diamonds infused preroll."],
  ["How long do the effects last?", "Edible effects typically begin within 30–90 minutes and can last 4–6 hours. Start low and go slow."],
  ["Can I buy this pack for delivery in Los Angeles?", "LUIGI products are available through licensed California dispensaries. Check your local retailer or delivery service for availability."],
] as const

const productSchema = { "@context": "https://schema.org", "@type": "Product", name: "Caribbean Fruit Gummy Pack", brand: { "@type": "Brand", name: "LUIGI" }, description: "Ten 10mg bubble hash rosin–infused Caribbean fruit indica gummies paired with a .5g Blood Orange live resin and liquid diamonds infused preroll. Medium potency, 10mg THC per pack. $15.00. Effects: happy, creative, euphoric.", image: caribbeanImages, sku: "LUIGI-CF-GUMMY-PACK", category: "Cannabis Edibles > Gummy Packs", keywords: "Caribbean fruit THC gummies, Caribbean fruit indica gummies, rosin infused gummies, THC gummies with preroll, indica gummies, bubble hash rosin gummies California, Caribbean fruit OG preroll, live resin preroll, liquid diamonds preroll, 10mg THC gummies, infused preroll pack, Caribbean fruit gummies California, rosin edibles California, LUIGI cannabis Los Angeles, affordable rosin gummies, $15 THC gummy pack, euphoric THC gummies, focused indica gummies", offers: { "@type": "Offer", priceCurrency: "USD", price: "15.00", availability: "https://schema.org/InStock", url: productUrl } }
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }
const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="border-b border-gray-200 py-14 md:py-20"><h2 className="text-3xl font-bold tracking-tight text-black md:text-4xl">{title}</h2><div className="mt-6 flex flex-col gap-5 text-lg leading-8 text-gray-700">{children}</div></section>

export default function PinkLemonadeGummyPackPage() {
  return <>
    <Script id="caribbean-fruit-product-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }} />
    <Script id="caribbean-fruit-faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <AgeVerification /><Header />
    <main className="pt-16 lg:pt-20">
      <section className="bg-black py-16 text-white md:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-2 lg:items-center lg:px-8"><div className="order-2 lg:order-1"><p className="mb-4 text-sm font-semibold uppercase tracking-[0.25em] text-[#D4AF37]">Indica Gummies</p><h1 className="text-4xl font-bold tracking-tight md:text-6xl">Caribbean Fruit Gummy Pack — Indica Rosin Gummies + Blood Orange Live Resin Preroll</h1><p className="mt-5 text-xl text-gray-300"><strong>Dangerously delicious. Seriously good.</strong></p><p className="mt-5 text-sm font-semibold uppercase tracking-wide text-gray-400">Medium Potency | 10mg THC per pack | 10 Gummies + 1 Preroll</p><p className="mt-5 text-lg text-gray-300">Happy · Creative · Euphoric</p><div className="mt-6 flex flex-wrap items-center gap-4"><span className="text-3xl font-bold">$15.00</span><span className="rounded-full border border-[#D4AF37]/50 px-4 py-2 text-sm text-[#D4AF37]">10 Gummies + 1 Preroll</span></div><AddToCartButton className="mt-6 w-full max-w-sm" product={{ id: "luigi-Caribbean fruit-gummy-pack", name: "Caribbean Fruit Gummy Pack", fullName: "LUIGI Caribbean Fruit Gummy Pack", image: caribbeanImages[1] }} price="$15" priceNumber={15} units="10 gummies + 1 preroll" /><p className="mt-5 max-w-xl text-lg leading-8 text-gray-300">Ten 10mg bubble hash rosin–infused Caribbean fruit indica gummies. One matching .5g Blood Orange live resin preroll. Two ways to experience the same bright, berry-forward flavor — and twice the reason to reach for LUIGI.</p></div><div className="order-1 grid grid-cols-2 gap-4 lg:order-2">{/* Image slot 1 — Hero: full Caribbean Fruit pack and preroll. */}{caribbeanImages.map((src, index) => <div key={src} className="relative aspect-square overflow-hidden rounded-lg bg-white/10"><Image src={src} alt={index === 0 ? "LUIGI Blood Orange live resin infused indica preroll" : "LUIGI Caribbean Fruit Indica THC Gummies 10-pack with rosin infusion"} fill className="object-contain p-4" priority={index === 1} /></div>)}</div></div></section>
      <div className="mx-auto max-w-5xl px-6 lg:px-8">
        <Section title="Two Ways to Experience Caribbean Fruit — One Pack"><p>This isn&apos;t just a Caribbean fruit THC gummy pack. It&apos;s a paired experience. Each LUIGI Caribbean Fruit Gummy Pack pairs ten indica gummies — infused with bubble hash rosin for a cleaner, more flavorful high — with a .5g preroll made from live resin and liquid diamonds.</p><p>The gummies deliver a sweet, juicy, freshly picked Caribbean fruit rush. The Blood Orange preroll layers earthy pine, citrus, and classic gassy undertones with a sweet finish. Together, they create a session that goes from first bite to final exhale. This is what a THC gummy and preroll combo pack should feel like — intentional, balanced, and memorable.</p><p>At just <strong>$15.00</strong>, it&apos;s one of the most value-forward rosin-infused gummy packs in California. Premium inputs, in-house production, and a paired preroll — without the premium markup.</p></Section>
        <Section title="What&apos;s Inside the Caribbean Fruit Gummy Pack">{/* Image slot 2 — Pack contents: gummy pack paired with Blood Orange preroll. */}<div className="overflow-x-auto"><table className="w-full border-collapse text-left text-base"><thead><tr className="border-b-2 border-black"><th className="py-3 pr-6">Component</th><th className="py-3">Details</th></tr></thead><tbody>{[["Gummies", "10× 10mg bubble hash rosin–infused Caribbean fruit indica gummies"], ["Preroll", "1× 0.5g Blood Orange live resin + liquid diamonds infused preroll"], ["Total THC", "10mg per pack (high potency)"], ["Type", "Indica"], ["Effects", "Happy, Creative, Euphoric"], ["Flavor Profile", "Caribbean Fruit, skunk, spicy/herbal, sweet, berry"], ["Price", "$15.00"]].map(([a, b]) => <tr key={a} className="border-b border-gray-200"><td className="py-4 pr-6 font-semibold">{a}</td><td className="py-4">{b}</td></tr>)}</tbody></table></div></Section>
        <Section title="Caribbean Fruit Gummy: Sweet, Juicy, Bursting with Berry">{/* Image slot 3 — Gummy close-up: Caribbean fruit rosin gummy texture. */}<p>Sweet, juicy, and bursting with berry goodness, our Caribbean Fruit THC Indica Gummies capture the irresistible flavor of juicy raspberries. Each soft, chewy bite delivers ripe Caribbean fruit sweetness with a bright, subtly tangy finish — a nostalgic fruit-forward flavor transformed into a refined edible experience.</p><p>Bubble hash rosin is a solventless cannabis extract prized for purity and full-spectrum flavor. Infusing it into gummies delivers a cleaner taste and more nuanced effect than distillate-based alternatives. The result is a 10mg THC gummy that tastes like real fruit — not chemicals — and hits with the consistency LUIGI is known for.</p><p>Each gummy is a standard 10mg serving, making dosing simple whether you&apos;re a seasoned connoisseur or new to indica gummies. For a milder experience, split the gummy in half. Effects typically begin within 30–90 minutes — give it time before reaching for another.</p></Section>
        <Section title="High Potency Meets Full-Spectrum Flavor"><p>The Caribbean Fruit Gummy Pack is built for daytime sessions and creative flow. The indica-leaning gummies deliver a bright, uplifting high that starts with gentle euphoria, settles into focused clarity, and finishes with a relaxed body calm that never tips into sedation.</p><p>That combination makes this pack ideal for social settings, creative work, outdoor afternoons, or anytime you want to feel elevated without being weighed down. The paired Blood Orange preroll leans into the same indica energy, with earthy pine and citrus notes adding a grounded counterpoint to the gummies&apos; bright berry profile.</p></Section>
        <Section title="Blood Orange PreRoll: A Refreshing Escape">{/* Image slot 4 — Preroll close-up: Blood Orange live resin infused indica preroll. */}<p>Sweet Caribbean fruit meets the unmistakable character of OG in this flavorful live resin-infused indica pre-roll. Bright berry notes are followed by earthy pine, citrus, and classic gassy undertones. A touch of sweetness rounds out the finish, balancing fruity freshness with deep, savory cannabis notes.</p><p>Live resin preserves the plant&apos;s natural terpenes for a flavorful, aromatic smoke. Liquid diamonds add a potent, crystalline THC punch. Together, they create an infused preroll that&apos;s both smooth and strong — the kind of Blood Orange preroll that reminds you why extract-infused flower is worth seeking out.</p></Section>
        <Section title="How to Enjoy the Caribbean Fruit Gummy Pack">{/* Image slot 5 — Lifestyle / pairing: gummies and Blood Orange preroll. */}<p><strong>The Gummies:</strong> Start with one. Each gummy is a standard 10mg serving. For a milder experience, split the gummy in half. Effects typically begin within 30–90 minutes.</p><p><strong>The Preroll:</strong> Save it for the come-up, peak, or wind-down. The Blood Orange live resin and liquid diamonds deliver a smooth, flavorful smoke that complements the gummy experience.</p><p><strong>The Pairing:</strong> Enjoy the preroll while the gummies take effect. The combination of edible indica high and inhalable terpene profile creates a layered, memorable session.</p><p><strong>Dosing Tip for New Consumers:</strong> Start with half a gummy (5mg) and wait a full 90 minutes before deciding whether to take more.</p></Section>
        <Section title="How the Caribbean Fruit Gummy Pack Compares to Distillate Gummies"><p>Most gummies use distillate — a refined THC extract that is potent but stripped of most natural terpenes and minor cannabinoids. The flavor is typically added back artificially, and the effect can feel flatter and more one-dimensional.</p><p>LUIGI uses bubble hash rosin instead. Rosin is solventless, full-spectrum, and retains terpenes, flavonoids, and minor cannabinoids. That means the Caribbean fruit flavor is coming from the same place the effect is — not a flavor additive. Add a Blood Orange live resin preroll, and you get two full-spectrum experiences for $15.00.</p></Section>
        <Section title="Premium Rosin Gummies at a $15 Price Point"><p>Most rosin-infused edible packs in California retail between $25 and $40. The LUIGI Caribbean Fruit Gummy Pack delivers the same solventless-infused quality — plus a live resin and liquid diamonds preroll — for just $15.00.</p><p>Everything we do starts in-house: formulation, production, packaging, and distribution. No middlemen. No inflated wholesale markups. Just premium cannabis products priced for the people who actually smoke them.</p><p>If you&apos;ve been searching for affordable rosin gummies in California without sacrificing flavor or potency, this is the pack.</p></Section>
        <Section title="Why LUIGI?">{/* Image slot 6 — Brand and lifestyle: LUIGI quality without pretense in Los Angeles. */}<p>Born in Los Angeles and built from the ground up, LUIGI is a cannabis brand for people who appreciate quality without the pretense. Everything starts in-house, giving us complete control over every product that carries our name.</p><p>We combine premium inputs, innovative hardware, and unique product formats to create experiences that stand out. Whether it&apos;s signature Dual Packs, rosin-infused products, Fattone collections, or limited-edition drops, LUIGI delivers flavor, potency, consistency, and value.</p><p>We&apos;re inspired by art, culture, hospitality, and the communities that support us. LUIGI isn&apos;t just a cannabis brand — it&apos;s a movement built around bringing people together.</p></Section>
        <Section title="Frequently Asked Questions"><div className="flex flex-col gap-3">{faqs.map(([question, answer]) => <details key={question} itemScope itemType="https://schema.org/Question" className="group rounded-lg border border-gray-200 bg-white"><summary itemProp="name" className="flex cursor-pointer list-none items-center justify-between gap-4 px-5 py-4 text-lg font-bold text-black marker:content-none"><span>{question}</span><span aria-hidden="true" className="text-2xl font-normal leading-none text-[#B08D24] transition-transform group-open:rotate-45">+</span></summary><div itemScope itemProp="acceptedAnswer" itemType="https://schema.org/Answer" className="border-t border-gray-200 px-5 py-4 leading-7 text-gray-700"><p itemProp="text">{answer}</p></div></details>)}</div></Section>
      </div>
      <section className="bg-black py-16 text-center text-white"><div className="mx-auto max-w-3xl px-6">{/* Image slot 7 — Final CTA: Caribbean Fruit pack at a California dispensary. */}<h2 className="text-3xl font-bold md:text-4xl">Ready to Experience the Caribbean Fruit Gummy Pack?</h2><p className="mt-5 text-lg leading-8 text-gray-300">Ten rosin-infused indica gummies. One Blood Orange live resin preroll. Twice the flavor. Twice the experience. Just $15.00. Find LUIGI at a licensed California dispensary near you.</p><Link href="/find-luigi" className="mt-8 inline-flex rounded-md bg-[#D4AF37] px-6 py-3 font-semibold text-black transition hover:bg-[#E3C45B]">Find a Dispensary — $15</Link></div></section>
    <RelatedGummyProducts currentSlug="caribbean-fruit-gummy-pack" /></main><Footer />
  </>
}
