import type { Metadata } from "next"
import Image from "next/image"
import Script from "next/script"
import Link from "next/link"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { RelatedGummyProducts } from "@/components/related-gummy-products"
import { AgeVerification } from "@/components/age-verification"
import { AddToCartButton } from "@/components/add-to-cart-button"

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.luigiofficialbrand.com"
const productUrl = `${siteUrl}/products/cherry-gummy-pack`
const cherryImages = [
  "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/cherry_joint-rXOqy4fHH7IGjgdVJlkaGUcHR0S4WT.avif",
  "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1789582694-cherry_1_-ylzVNBAEyzA3Uf36Qv2WxBHzjK76zK.avif",
]

export const metadata: Metadata = {
  title: "Cherry Hybrid Gummies + Preroll | LUIGI Rosin Pack — $15",
  description: "Ten 10mg bubble hash rosin cherry hybrid gummies paired with a .5g Cherry Pie live resin preroll. Just $15. Bright, euphoric, focused. Shop LUIGI in California.",
  keywords: ["cherry THC gummies", "cherry hybrid gummies", "rosin infused gummies", "THC gummies with preroll", "hybrid gummies", "bubble hash rosin gummies California", "cherry OG preroll", "live resin preroll", "liquid diamonds preroll", "10mg THC gummies", "infused preroll pack", "cherry gummies California", "rosin edibles California", "cherry hybrid gummies with preroll", "bubble hash rosin infused gummies 100mg", "THC gummy and preroll combo pack", "best rosin gummies Los Angeles", "LUIGI cannabis Los Angeles", "affordable rosin gummies", "$15 THC gummy pack", "euphoric THC gummies", "focused hybrid gummies"],
  alternates: { canonical: productUrl },
  openGraph: { title: "Cherry Gummy Pack | LUIGI Cannabis — $15", description: "Ten 10mg bubble hash rosin–infused cherry hybrid gummies + a .5g Cherry Pie live resin preroll. Just $15. Bright, euphoric, focused.", url: productUrl, siteName: "LUIGI", type: "website", images: [{ url: cherryImages[1], alt: "LUIGI Cherry Hybrid THC Gummies 10-pack with rosin infusion" }] },
  twitter: { card: "summary_large_image", images: [cherryImages[1]] },
}

const faqs = [
  ["What does bubble hash rosin–infused mean?", "Bubble hash rosin is a solventless cannabis extract prized for its purity and full-spectrum flavor. Infusing it into gummies delivers a cleaner taste and more nuanced effect than distillate-based alternatives."],
  ["Are the Cherry Gummies hybrid, hybrid, or hybrid?", "The gummies are hybrid, and the paired Cherry Pie preroll is also hybrid. Expect an uplifting, focused, and euphoric experience."],
  ["What effects do the Cherry Hybrid Gummies produce?", "Consumers report feeling relaxed, focused, and euphoric. The high is bright and uplifting rather than sedating, making it well-suited for daytime use."],
  ["What does the Cherry Gummy Pack taste like?", "The gummies taste like ripe, juicy strawberries with a bright, subtly tangy finish. The Cherry Pie preroll adds earthy pine, citrus, gassy undertones, and sweetness."],
  ["How much THC is in each gummy?", "Each gummy contains 10mg THC. The full pack is rated high potency at 10.1mg THC per pack."],
  ["How much does the Cherry Gummy Pack cost?", "The pack retails for $15.00 and includes ten 10mg bubble hash rosin–infused hybrid gummies plus one 0.5g Cherry Pie live resin and liquid diamonds infused preroll."],
  ["How long do the effects last?", "Edible effects typically begin within 30–90 minutes and can last 4–6 hours. Start low and go slow."],
  ["Can I buy this pack for delivery in Los Angeles?", "LUIGI products are available through licensed California dispensaries. Check your local retailer or delivery service for availability."],
] as const

const productSchema = { "@context": "https://schema.org", "@type": "Product", name: "Cherry Gummy Pack", brand: { "@type": "Brand", name: "LUIGI" }, description: "Ten 10mg bubble hash rosin–infused cherry hybrid gummies paired with a .5g Cherry Pie live resin and liquid diamonds infused preroll. Medium potency, 10.1mg THC per pack. $15.00. Effects: happy, creative, euphoric.", image: cherryImages, sku: "LUIGI-CH-GUMMY-PACK", category: "Cannabis Edibles > Gummy Packs", keywords: "cherry THC gummies, cherry hybrid gummies, rosin infused gummies, THC gummies with preroll, hybrid gummies, bubble hash rosin gummies California, cherry OG preroll, live resin preroll, liquid diamonds preroll, 10mg THC gummies, infused preroll pack, cherry gummies California, rosin edibles California, LUIGI cannabis Los Angeles, affordable rosin gummies, $15 THC gummy pack, euphoric THC gummies, focused hybrid gummies", offers: { "@type": "Offer", priceCurrency: "USD", price: "15.00", availability: "https://schema.org/InStock", url: productUrl } }
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }
const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="border-b border-gray-200 py-14 md:py-20"><h2 className="text-3xl font-bold tracking-tight text-black md:text-4xl">{title}</h2><div className="mt-6 flex flex-col gap-5 text-lg leading-8 text-gray-700">{children}</div></section>

export default function PinkLemonadeGummyPackPage() {
  return <>
    <Script id="cherry-product-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }} />
    <Script id="cherry-faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <AgeVerification /><Header />
    <main className="pt-16 lg:pt-20">
      <section className="bg-black py-16 text-white md:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-2 lg:items-center lg:px-8"><div className="order-2 lg:order-1"><p className="mb-4 text-sm font-semibold uppercase tracking-[0.25em] text-[#D4AF37]">Hybrid Gummies</p><h1 className="text-4xl font-bold tracking-tight md:text-6xl">Cherry Gummy Pack — Hybrid Rosin Gummies + Cherry Pie Live Resin Preroll</h1><p className="mt-5 text-xl text-gray-300"><strong>Dangerously delicious. Seriously good.</strong></p><p className="mt-5 text-sm font-semibold uppercase tracking-wide text-gray-400">Medium Potency | 10.1mg THC per pack | 10 Gummies + 1 Preroll</p><p className="mt-5 text-lg text-gray-300">Happy · Creative · Euphoric</p><div className="mt-6 flex flex-wrap items-center gap-4"><span className="text-3xl font-bold">$15.00</span><span className="rounded-full border border-[#D4AF37]/50 px-4 py-2 text-sm text-[#D4AF37]">10 Gummies + 1 Preroll</span></div><AddToCartButton className="mt-6 w-full max-w-sm" product={{ id: "luigi-cherry-gummy-pack", name: "Cherry Gummy Pack", fullName: "LUIGI Cherry Gummy Pack", image: cherryImages[1] }} price="$15" priceNumber={15} units="10 gummies + 1 preroll" /><p className="mt-5 max-w-xl text-lg leading-8 text-gray-300">Ten 10mg bubble hash rosin–infused cherry hybrid gummies. One matching .5g Cherry Pie live resin preroll. Two ways to experience the same bright, berry-forward flavor — and twice the reason to reach for LUIGI.</p></div><div className="order-1 grid grid-cols-2 gap-4 lg:order-2">{/* Image slot 1 — Hero: full Cherry pack and preroll. */}{cherryImages.map((src, index) => <div key={src} className="relative aspect-square overflow-hidden rounded-lg bg-white/10"><Image src={src} alt={index === 0 ? "LUIGI Cherry Pie live resin infused hybrid preroll" : "LUIGI Cherry Hybrid THC Gummies 10-pack with rosin infusion"} fill className="object-contain p-4" priority={index === 1} /></div>)}</div></div></section>
      <div className="mx-auto max-w-5xl px-6 lg:px-8">
        <Section title="Two Ways to Experience Cherry — One Pack"><p>This isn&apos;t just a cherry THC gummy pack. It&apos;s a paired experience. Each LUIGI Cherry Gummy Pack pairs ten hybrid gummies — infused with bubble hash rosin for a cleaner, more flavorful high — with a .5g preroll made from live resin and liquid diamonds.</p><p>The gummies deliver a sweet, juicy, freshly picked cherry rush. The Cherry Pie preroll layers earthy pine, citrus, and classic gassy undertones with a sweet finish. Together, they create a session that goes from first bite to final exhale. This is what a THC gummy and preroll combo pack should feel like — intentional, balanced, and memorable.</p><p>At just <strong>$15.00</strong>, it&apos;s one of the most value-forward rosin-infused gummy packs in California. Premium inputs, in-house production, and a paired preroll — without the premium markup.</p></Section>
        <Section title="What&apos;s Inside the Cherry Gummy Pack">{/* Image slot 2 — Pack contents: gummy pack paired with Cherry Pie preroll. */}<div className="overflow-x-auto"><table className="w-full border-collapse text-left text-base"><thead><tr className="border-b-2 border-black"><th className="py-3 pr-6">Component</th><th className="py-3">Details</th></tr></thead><tbody>{[["Gummies", "10× 10mg bubble hash rosin–infused cherry hybrid gummies"], ["Preroll", "1× 0.5g Cherry Pie live resin + liquid diamonds infused preroll"], ["Total THC", "10.1mg per pack (high potency)"], ["Type", "Hybrid"], ["Effects", "Happy, Creative, Euphoric"], ["Flavor Profile", "Cherry, skunk, spicy/herbal, sweet, berry"], ["Price", "$15.00"]].map(([a, b]) => <tr key={a} className="border-b border-gray-200"><td className="py-4 pr-6 font-semibold">{a}</td><td className="py-4">{b}</td></tr>)}</tbody></table></div></Section>
        <Section title="Cherry Gummy: Sweet, Juicy, Bursting with Berry">{/* Image slot 3 — Gummy close-up: cherry rosin gummy texture. */}<p>Sweet, juicy, and bursting with berry goodness, our Cherry THC Hybrid Gummies capture the irresistible flavor of juicy raspberries. Each soft, chewy bite delivers ripe cherry sweetness with a bright, subtly tangy finish — a nostalgic fruit-forward flavor transformed into a refined edible experience.</p><p>Bubble hash rosin is a solventless cannabis extract prized for purity and full-spectrum flavor. Infusing it into gummies delivers a cleaner taste and more nuanced effect than distillate-based alternatives. The result is a 10mg THC gummy that tastes like real fruit — not chemicals — and hits with the consistency LUIGI is known for.</p><p>Each gummy is a standard 10mg serving, making dosing simple whether you&apos;re a seasoned connoisseur or new to hybrid gummies. For a milder experience, split the gummy in half. Effects typically begin within 30–90 minutes — give it time before reaching for another.</p></Section>
        <Section title="High Potency Meets Full-Spectrum Flavor"><p>The Cherry Gummy Pack is built for daytime sessions and creative flow. The hybrid-leaning gummies deliver a bright, uplifting high that starts with gentle euphoria, settles into focused clarity, and finishes with a relaxed body calm that never tips into sedation.</p><p>That combination makes this pack ideal for social settings, creative work, outdoor afternoons, or anytime you want to feel elevated without being weighed down. The paired Cherry Pie preroll leans into the same hybrid energy, with earthy pine and citrus notes adding a grounded counterpoint to the gummies&apos; bright berry profile.</p></Section>
        <Section title="Cherry Pie PreRoll: A Refreshing Escape">{/* Image slot 4 — Preroll close-up: Cherry Pie live resin infused hybrid preroll. */}<p>Sweet cherry meets the unmistakable character of OG in this flavorful live resin-infused hybrid pre-roll. Bright berry notes are followed by earthy pine, citrus, and classic gassy undertones. A touch of sweetness rounds out the finish, balancing fruity freshness with deep, savory cannabis notes.</p><p>Live resin preserves the plant&apos;s natural terpenes for a flavorful, aromatic smoke. Liquid diamonds add a potent, crystalline THC punch. Together, they create an infused preroll that&apos;s both smooth and strong — the kind of Cherry Pie preroll that reminds you why extract-infused flower is worth seeking out.</p></Section>
        <Section title="How to Enjoy the Cherry Gummy Pack">{/* Image slot 5 — Lifestyle / pairing: gummies and Cherry Pie preroll. */}<p><strong>The Gummies:</strong> Start with one. Each gummy is a standard 10mg serving. For a milder experience, split the gummy in half. Effects typically begin within 30–90 minutes.</p><p><strong>The Preroll:</strong> Save it for the come-up, peak, or wind-down. The Cherry Pie live resin and liquid diamonds deliver a smooth, flavorful smoke that complements the gummy experience.</p><p><strong>The Pairing:</strong> Enjoy the preroll while the gummies take effect. The combination of edible hybrid high and inhalable terpene profile creates a layered, memorable session.</p><p><strong>Dosing Tip for New Consumers:</strong> Start with half a gummy (5mg) and wait a full 90 minutes before deciding whether to take more.</p></Section>
        <Section title="How the Cherry Gummy Pack Compares to Distillate Gummies"><p>Most gummies use distillate — a refined THC extract that is potent but stripped of most natural terpenes and minor cannabinoids. The flavor is typically added back artificially, and the effect can feel flatter and more one-dimensional.</p><p>LUIGI uses bubble hash rosin instead. Rosin is solventless, full-spectrum, and retains terpenes, flavonoids, and minor cannabinoids. That means the cherry flavor is coming from the same place the effect is — not a flavor additive. Add a Cherry Pie live resin preroll, and you get two full-spectrum experiences for $15.00.</p></Section>
        <Section title="Premium Rosin Gummies at a $15 Price Point"><p>Most rosin-infused edible packs in California retail between $25 and $40. The LUIGI Cherry Gummy Pack delivers the same solventless-infused quality — plus a live resin and liquid diamonds preroll — for just $15.00.</p><p>Everything we do starts in-house: formulation, production, packaging, and distribution. No middlemen. No inflated wholesale markups. Just premium cannabis products priced for the people who actually smoke them.</p><p>If you&apos;ve been searching for affordable rosin gummies in California without sacrificing flavor or potency, this is the pack.</p></Section>
        <Section title="Why LUIGI?">{/* Image slot 6 — Brand and lifestyle: LUIGI quality without pretense in Los Angeles. */}<p>Born in Los Angeles and built from the ground up, LUIGI is a cannabis brand for people who appreciate quality without the pretense. Everything starts in-house, giving us complete control over every product that carries our name.</p><p>We combine premium inputs, innovative hardware, and unique product formats to create experiences that stand out. Whether it&apos;s signature Dual Packs, rosin-infused products, Fattone collections, or limited-edition drops, LUIGI delivers flavor, potency, consistency, and value.</p><p>We&apos;re inspired by art, culture, hospitality, and the communities that support us. LUIGI isn&apos;t just a cannabis brand — it&apos;s a movement built around bringing people together.</p></Section>
        <Section title="Frequently Asked Questions"><div className="flex flex-col gap-3">{faqs.map(([question, answer]) => <details key={question} itemScope itemType="https://schema.org/Question" className="group rounded-lg border border-gray-200 bg-white"><summary itemProp="name" className="flex cursor-pointer list-none items-center justify-between gap-4 px-5 py-4 text-lg font-bold text-black marker:content-none"><span>{question}</span><span aria-hidden="true" className="text-2xl font-normal leading-none text-[#B08D24] transition-transform group-open:rotate-45">+</span></summary><div itemScope itemProp="acceptedAnswer" itemType="https://schema.org/Answer" className="border-t border-gray-200 px-5 py-4 leading-7 text-gray-700"><p itemProp="text">{answer}</p></div></details>)}</div></Section>
      </div>
      <section className="bg-black py-16 text-center text-white"><div className="mx-auto max-w-3xl px-6">{/* Image slot 7 — Final CTA: Cherry pack at a California dispensary. */}<h2 className="text-3xl font-bold md:text-4xl">Ready to Experience the Cherry Gummy Pack?</h2><p className="mt-5 text-lg leading-8 text-gray-300">Ten rosin-infused hybrid gummies. One Cherry Pie live resin preroll. Twice the flavor. Twice the experience. Just $15.00. Find LUIGI at a licensed California dispensary near you.</p><Link href="/find-luigi" className="mt-8 inline-flex rounded-md bg-[#D4AF37] px-6 py-3 font-semibold text-black transition hover:bg-[#E3C45B]">Find a Dispensary — $15</Link></div></section>
    <RelatedGummyProducts currentSlug="cherry-gummy-pack" /></main><Footer />
  </>
}
